import type { IExecuteFunctions, INodeExecutionData } from "n8n-workflow";
import { NodeOperationError } from "n8n-workflow";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

/**
 * Action runner for 'qsv replace'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeReplace(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter(
    "inputPath",
    itemIndex,
    "",
  ) as string;
  const inputPath = rawInputPath
    ? rawInputPath.trim().replace(/^['"]|['"]$/g, "")
    : "";
  if (!inputPath) {
    throw new NodeOperationError(
      this.getNode(),
      "Input CSV file path is required.",
      { itemIndex },
    );
  }

  const args: string[] = ["replace"];

  // Collect options and flags
  try {
    const val = this.getNodeParameter(
      "ignoreCase",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--ignore-case");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("literal", itemIndex, false) as boolean;
    if (val) {
      args.push("--literal");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("exact", itemIndex, false) as boolean;
    if (val) {
      args.push("--exact");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("select", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--select", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("unicode", itemIndex, false) as boolean;
    if (val) {
      args.push("--unicode");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("sizeLimit", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--size-limit", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("dfaSizeLimit", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--dfa-size-limit", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("notOne", itemIndex, false) as boolean;
    if (val) {
      args.push("--not-one");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("jobs", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--jobs", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noHeaders", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-headers");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("delimiter", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--delimiter", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "progressbar",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--progressbar");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("quiet", itemIndex, false) as boolean;
    if (val) {
      args.push("--quiet");
    }
  } catch {}

  try {
    const rawOutputPath = this.getNodeParameter(
      "outputPath",
      itemIndex,
      "",
    ) as string;
    const outputPath = rawOutputPath
      ? rawOutputPath.trim().replace(/^['"]|['"]$/g, "")
      : "";
    if (outputPath) {
      args.push("--output", outputPath);
    }
  } catch {}

  args.push(inputPath);

  const qsvBin =
    process.env.DARTFX_QSV_BIN_PATH ||
    process.env.QSV_BIN_PATH ||
    process.env.QSV_PATH ||
    "qsv";

  try {
    const { stdout, stderr } = await execFileAsync(qsvBin, args, {
      maxBuffer: 50 * 1024 * 1024,
      encoding: "utf8",
    });
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: "qsv replace",
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: "replace",
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    if (error.code === "ENOENT") {
      throw new NodeOperationError(
        this.getNode(),
        `The QSV CLI binary ('${qsvBin}') was not found. Please ensure QSV is installed and in your PATH, or specify its absolute path via the DARTFX_QSV_BIN_PATH or QSV_BIN_PATH environment variables. See: https://github.com/dathere/qsv`,
        { itemIndex },
      );
    }
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv replace': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
