import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv schema'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeSchema(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['schema'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('enumThreshold', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--enum-threshold', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('ignoreCase', itemIndex, false) as boolean;
      if (val) {
        args.push('--ignore-case');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('strictDates', itemIndex, false) as boolean;
      if (val) {
        args.push('--strict-dates');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('strictFormats', itemIndex, false) as boolean;
      if (val) {
        args.push('--strict-formats');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('patternColumns', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--pattern-columns', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('datesWhitelist', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--dates-whitelist', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('preferDmy', itemIndex, false) as boolean;
      if (val) {
        args.push('--prefer-dmy');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('force', itemIndex, false) as boolean;
      if (val) {
        args.push('--force');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('stdout', itemIndex, false) as boolean;
      if (val) {
        args.push('--stdout');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('jobs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--jobs', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('polars', itemIndex, false) as boolean;
      if (val) {
        args.push('--polars');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noHeaders', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-headers');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiter', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('memcheck', itemIndex, false) as boolean;
      if (val) {
        args.push('--memcheck');
      }
    } catch {}

  try {
    const outputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv schema',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'schema',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv schema': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
