import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv blake3'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeBlake3(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['blake3'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('keyed', itemIndex, false) as boolean;
      if (val) {
        args.push('--keyed');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('deriveKey', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--derive-key', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('length', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--length', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noMmap', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-mmap');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noNames', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-names');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('raw', itemIndex, false) as boolean;
      if (val) {
        args.push('--raw');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('tag', itemIndex, false) as boolean;
      if (val) {
        args.push('--tag');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('check', itemIndex, false) as boolean;
      if (val) {
        args.push('--check');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('jobs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--jobs', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('quiet', itemIndex, false) as boolean;
      if (val) {
        args.push('--quiet');
      }
    } catch {}

  try {
    const outputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv blake3',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'blake3',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv blake3': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
