import type { IExecuteFunctions, INodeExecutionData } from "n8n-workflow";
import { NodeOperationError } from "n8n-workflow";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

/**
 * Action runner for 'qsv geoconvert'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeGeoconvert(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter(
    "inputPath",
    itemIndex,
    "",
  ) as string;
  const inputPath = rawInputPath
    ? rawInputPath.trim().replace(/^['"]|['"]$/g, "")
    : "";
  if (!inputPath) {
    throw new NodeOperationError(
      this.getNode(),
      "Input CSV file path is required.",
      { itemIndex },
    );
  }

  const args: string[] = ["geoconvert"];

  // Collect options and flags
  try {
    const val = this.getNodeParameter("geometry", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--geometry", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("latitude", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--latitude", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("longitude", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--longitude", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("maxLength", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--max-length", val);
    }
  } catch {}

  try {
    const rawOutputPath = this.getNodeParameter(
      "outputPath",
      itemIndex,
      "",
    ) as string;
    const outputPath = rawOutputPath
      ? rawOutputPath.trim().replace(/^['"]|['"]$/g, "")
      : "";
    if (outputPath) {
      args.push("--output", outputPath);
    }
  } catch {}

  args.push(inputPath);

  const qsvBin =
    process.env.DARTFX_QSV_BIN_PATH ||
    process.env.QSV_BIN_PATH ||
    process.env.QSV_PATH ||
    "qsv";

  try {
    const { stdout, stderr } = await execFileAsync(qsvBin, args, {
      maxBuffer: 50 * 1024 * 1024,
      encoding: "utf8",
    });
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: "qsv geoconvert",
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: "geoconvert",
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    if (error.code === "ENOENT") {
      throw new NodeOperationError(
        this.getNode(),
        `The QSV CLI binary ('${qsvBin}') was not found. Please ensure QSV is installed and in your PATH, or specify its absolute path via the DARTFX_QSV_BIN_PATH or QSV_BIN_PATH environment variables. See: https://github.com/dathere/qsv`,
        { itemIndex },
      );
    }
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv geoconvert': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
