import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv excel'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeExcel(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  const inputPath = rawInputPath ? rawInputPath.trim().replace(/^['"]|['"]$/g, '') : '';
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['excel'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('sheet', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--sheet', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('headerRow', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--header-row', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('metadata', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--metadata', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('table', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--table', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('range', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--range', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('cell', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--cell', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('errorFormat', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--error-format', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('flexible', itemIndex, false) as boolean;
      if (val) {
        args.push('--flexible');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('trim', itemIndex, false) as boolean;
      if (val) {
        args.push('--trim');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('dateFormat', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--date-format', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('keepZeroTime', itemIndex, false) as boolean;
      if (val) {
        args.push('--keep-zero-time');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('jobs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--jobs', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiter', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('quiet', itemIndex, false) as boolean;
      if (val) {
        args.push('--quiet');
      }
    } catch {}

  try {
    const rawOutputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    const outputPath = rawOutputPath ? rawOutputPath.trim().replace(/^['"]|['"]$/g, '') : '';
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  const qsvBin =
    process.env.DARTFX_QSV_BIN_PATH ||
    process.env.QSV_BIN_PATH ||
    process.env.QSV_PATH ||
    'qsv';

  try {
    const { stdout, stderr } = await execa(qsvBin, args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv excel',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'excel',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    if (error.code === 'ENOENT') {
      throw new NodeOperationError(
        this.getNode(),
        `The QSV CLI binary ('${qsvBin}') was not found. Please ensure QSV is installed and in your PATH, or specify its absolute path via the DARTFX_QSV_BIN_PATH or QSV_BIN_PATH environment variables. See: https://github.com/dathere/qsv`,
        { itemIndex },
      );
    }
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv excel': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
