import type { IExecuteFunctions, INodeExecutionData } from "n8n-workflow";
import { NodeOperationError } from "n8n-workflow";
import { execa } from "execa";

/**
 * Action runner for 'qsv select'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeSelect(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter("inputPath", itemIndex, "") as string;
  if (!inputPath) {
    throw new NodeOperationError(
      this.getNode(),
      "Input CSV file path is required.",
      { itemIndex },
    );
  }

  const args: string[] = ["select"];

  // Collect options and flags
  try {
    const val = this.getNodeParameter("random", itemIndex, false) as boolean;
    if (val) {
      args.push("--random");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("seed", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--seed", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("sort", itemIndex, false) as boolean;
    if (val) {
      args.push("--sort");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noHeaders", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-headers");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("delimiter", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--delimiter", val);
    }
  } catch {}

  try {
    const outputPath = this.getNodeParameter(
      "outputPath",
      itemIndex,
      "",
    ) as string;
    if (outputPath) {
      args.push("--output", outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa("qsv", args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: "qsv select",
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: "select",
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv select': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
