import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv headers'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeHeaders(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['headers'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('justNames', itemIndex, false) as boolean;
      if (val) {
        args.push('--just-names');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('justCount', itemIndex, false) as boolean;
      if (val) {
        args.push('--just-count');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('union', itemIndex, false) as boolean;
      if (val) {
        args.push('--union');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('trim', itemIndex, false) as boolean;
      if (val) {
        args.push('--trim');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiter', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter', val);
      }
    } catch {}

  try {
    const outputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv headers',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'headers',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv headers': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
