import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv diff'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeDiff(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['diff'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('noHeadersLeft', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-headers-left');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noHeadersRight', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-headers-right');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noHeadersOutput', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-headers-output');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiterLeft', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter-left', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiterRight', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter-right', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiterOutput', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter-output', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('key', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--key', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('sortColumns', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--sort-columns', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('dropEqualFields', itemIndex, false) as boolean;
      if (val) {
        args.push('--drop-equal-fields');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('dropEqualColumns', itemIndex, false) as boolean;
      if (val) {
        args.push('--drop-equal-columns');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('jobs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--jobs', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiter', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter', val);
      }
    } catch {}

  try {
    const outputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv diff',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'diff',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv diff': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
