import type { IExecuteFunctions, INodeExecutionData } from "n8n-workflow";
import { NodeOperationError } from "n8n-workflow";
import { execa } from "execa";

/**
 * Action runner for 'qsv foreach'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeForeach(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter(
    "inputPath",
    itemIndex,
    "",
  ) as string;
  const inputPath = rawInputPath
    ? rawInputPath.trim().replace(/^['"]|['"]$/g, "")
    : "";
  if (!inputPath) {
    throw new NodeOperationError(
      this.getNode(),
      "Input CSV file path is required.",
      { itemIndex },
    );
  }

  const args: string[] = ["foreach"];

  // Collect options and flags
  try {
    const val = this.getNodeParameter("unify", itemIndex, false) as boolean;
    if (val) {
      args.push("--unify");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("newColumn", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--new-column", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("dryRun", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--dry-run", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noHeaders", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-headers");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("delimiter", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--delimiter", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "progressbar",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--progressbar");
    }
  } catch {}

  try {
    const rawOutputPath = this.getNodeParameter(
      "outputPath",
      itemIndex,
      "",
    ) as string;
    const outputPath = rawOutputPath
      ? rawOutputPath.trim().replace(/^['"]|['"]$/g, "")
      : "";
    if (outputPath) {
      args.push("--output", outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa("qsv", args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: "qsv foreach",
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: "foreach",
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv foreach': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
