import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv sort'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeSort(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  const inputPath = rawInputPath ? rawInputPath.trim().replace(/^['"]|['"]$/g, '') : '';
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['sort'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('select', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--select', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('numeric', itemIndex, false) as boolean;
      if (val) {
        args.push('--numeric');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('natural', itemIndex, false) as boolean;
      if (val) {
        args.push('--natural');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('reverse', itemIndex, false) as boolean;
      if (val) {
        args.push('--reverse');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('ignoreCase', itemIndex, false) as boolean;
      if (val) {
        args.push('--ignore-case');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('unique', itemIndex, false) as boolean;
      if (val) {
        args.push('--unique');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('random', itemIndex, false) as boolean;
      if (val) {
        args.push('--random');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('seed', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--seed', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('rng', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--rng', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('jobs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--jobs', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('faster', itemIndex, false) as boolean;
      if (val) {
        args.push('--faster');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noHeaders', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-headers');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiter', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('memcheck', itemIndex, false) as boolean;
      if (val) {
        args.push('--memcheck');
      }
    } catch {}

  try {
    const rawOutputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    const outputPath = rawOutputPath ? rawOutputPath.trim().replace(/^['"]|['"]$/g, '') : '';
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  const qsvBin =
    process.env.DARTFX_QSV_BIN_PATH ||
    process.env.QSV_BIN_PATH ||
    process.env.QSV_PATH ||
    'qsv';

  try {
    const { stdout, stderr } = await execa(qsvBin, args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv sort',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'sort',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    if (error.code === 'ENOENT') {
      throw new NodeOperationError(
        this.getNode(),
        `The QSV CLI binary ('${qsvBin}') was not found. Please ensure QSV is installed and in your PATH, or specify its absolute path via the DARTFX_QSV_BIN_PATH or QSV_BIN_PATH environment variables. See: https://github.com/dathere/qsv`,
        { itemIndex },
      );
    }
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv sort': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
