import type { IExecuteFunctions, INodeExecutionData } from "n8n-workflow";
import { NodeOperationError } from "n8n-workflow";
import { execa } from "execa";

/**
 * Action runner for 'qsv frequency'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeFrequency(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter("inputPath", itemIndex, "") as string;
  if (!inputPath) {
    throw new NodeOperationError(
      this.getNode(),
      "Input CSV file path is required.",
      { itemIndex },
    );
  }

  const args: string[] = ["frequency"];

  // Collect options and flags
  try {
    const val = this.getNodeParameter("select", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--select", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("limit", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--limit", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("sketchMethod", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--sketch-method", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("sketchMapSize", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--sketch-map-size", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("unqLimit", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--unq-limit", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("lmtThreshold", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--lmt-threshold", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("rankStrategy", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--rank-strategy", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("pctDecPlaces", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--pct-dec-places", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "otherSorted",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--other-sorted");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("otherText", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--other-text", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noOther", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-other");
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "nullSorted",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--null-sorted");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("asc", itemIndex, false) as boolean;
    if (val) {
      args.push("--asc");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noTrim", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-trim");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("nullText", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--null-text", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noNulls", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-nulls");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("pctNulls", itemIndex, false) as boolean;
    if (val) {
      args.push("--pct-nulls");
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "ignoreCase",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--ignore-case");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noFloat", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--no-float", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("statsFilter", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--stats-filter", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("allUniqueText", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--all-unique-text", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "visWhitespace",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--vis-whitespace");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("jobs", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--jobs", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "frequencyJsonl",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--frequency-jsonl");
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "highCardThreshold",
      itemIndex,
      "",
    ) as string;
    if (val !== undefined && val !== "") {
      args.push("--high-card-threshold", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("highCardPct", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--high-card-pct", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("force", itemIndex, false) as boolean;
    if (val) {
      args.push("--force");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("json", itemIndex, false) as boolean;
    if (val) {
      args.push("--json");
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "prettyJson",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--pretty-json");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("toon", itemIndex, false) as boolean;
    if (val) {
      args.push("--toon");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noStats", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-stats");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("weight", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--weight", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noHeaders", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-headers");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("delimiter", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--delimiter", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("memcheck", itemIndex, false) as boolean;
    if (val) {
      args.push("--memcheck");
    }
  } catch {}

  try {
    const outputPath = this.getNodeParameter(
      "outputPath",
      itemIndex,
      "",
    ) as string;
    if (outputPath) {
      args.push("--output", outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa("qsv", args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: "qsv frequency",
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: "frequency",
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv frequency': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
