import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv profile'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeProfile(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['profile'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('spec', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--spec', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('initialContext', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--initial-context', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noProjection', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-projection');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noCkan', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-ckan');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('croissantFrequency', itemIndex, false) as boolean;
      if (val) {
        args.push('--croissant-frequency');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('dcatLegacyLicense', itemIndex, false) as boolean;
      if (val) {
        args.push('--dcat-legacy-license');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noDcatDiscovery', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-dcat-discovery');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('dcatDiscoveryTimeout', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--dcat-discovery-timeout', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('validate', itemIndex, false) as boolean;
      if (val) {
        args.push('--validate');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('strict', itemIndex, false) as boolean;
      if (val) {
        args.push('--strict');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('catalog', itemIndex, false) as boolean;
      if (val) {
        args.push('--catalog');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('profile', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--profile', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('force', itemIndex, false) as boolean;
      if (val) {
        args.push('--force');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('jobs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--jobs', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noHeaders', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-headers');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiter', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('memcheck', itemIndex, false) as boolean;
      if (val) {
        args.push('--memcheck');
      }
    } catch {}

  try {
    const outputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv profile',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'profile',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv profile': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
