import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv count'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeCount(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  const inputPath = rawInputPath ? rawInputPath.trim().replace(/^['"]|['"]$/g, '') : '';
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['count'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('humanReadable', itemIndex, false) as boolean;
      if (val) {
        args.push('--human-readable');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('width', itemIndex, false) as boolean;
      if (val) {
        args.push('--width');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('widthNoDelims', itemIndex, false) as boolean;
      if (val) {
        args.push('--width-no-delims');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('json', itemIndex, false) as boolean;
      if (val) {
        args.push('--json');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noPolars', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-polars');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('lowMemory', itemIndex, false) as boolean;
      if (val) {
        args.push('--low-memory');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('flexible', itemIndex, false) as boolean;
      if (val) {
        args.push('--flexible');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noHeaders', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-headers');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiter', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter', val);
      }
    } catch {}

  try {
    const rawOutputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    const outputPath = rawOutputPath ? rawOutputPath.trim().replace(/^['"]|['"]$/g, '') : '';
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv count',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'count',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv count': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
