import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv describegpt'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeDescribegpt(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  const inputPath = rawInputPath ? rawInputPath.trim().replace(/^['"]|['"]$/g, '') : '';
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['describegpt'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('dictionary', itemIndex, false) as boolean;
      if (val) {
        args.push('--dictionary');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('description', itemIndex, false) as boolean;
      if (val) {
        args.push('--description');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('tags', itemIndex, false) as boolean;
      if (val) {
        args.push('--tags');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('all', itemIndex, false) as boolean;
      if (val) {
        args.push('--all');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('numExamples', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--num-examples', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('truncateStr', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--truncate-str', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('inferContentType', itemIndex, false) as boolean;
      if (val) {
        args.push('--infer-content-type');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('inferNullValues', itemIndex, false) as boolean;
      if (val) {
        args.push('--infer-null-values');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('twoPass', itemIndex, false) as boolean;
      if (val) {
        args.push('--two-pass');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('addlCols', itemIndex, false) as boolean;
      if (val) {
        args.push('--addl-cols');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('addlColsList', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--addl-cols-list', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('numTags', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--num-tags', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('tagVocab', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--tag-vocab', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('cacheDir', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--cache-dir', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('ckanApi', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--ckan-api', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('ckanToken', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--ckan-token', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('statsOptions', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--stats-options', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('freqOptions', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--freq-options', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('enumThreshold', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--enum-threshold', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('prompt', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--prompt', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('sqlResults', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--sql-results', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('promptFile', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--prompt-file', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('contextFile', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--context-file', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('markdownTemplate', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--markdown-template', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('sampleSize', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--sample-size', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('fewshotExamples', itemIndex, false) as boolean;
      if (val) {
        args.push('--fewshot-examples');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('session', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--session', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('sessionLen', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--session-len', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noScoreSql', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-score-sql');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('scoreThreshold', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--score-threshold', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('scoreMaxRetries', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--score-max-retries', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('baseUrl', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--base-url', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('model', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--model', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('language', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--language', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('addlProps', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--addl-props', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('apiKey', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--api-key', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('maxTokens', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--max-tokens', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('timeout', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--timeout', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('userAgent', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--user-agent', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('exportPrompt', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--export-prompt', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noCache', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-cache');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('diskCacheDir', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--disk-cache-dir', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('redisCache', itemIndex, false) as boolean;
      if (val) {
        args.push('--redis-cache');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('fresh', itemIndex, false) as boolean;
      if (val) {
        args.push('--fresh');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('forget', itemIndex, false) as boolean;
      if (val) {
        args.push('--forget');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('flushCache', itemIndex, false) as boolean;
      if (val) {
        args.push('--flush-cache');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('prepareContext', itemIndex, false) as boolean;
      if (val) {
        args.push('--prepare-context');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('processResponse', itemIndex, false) as boolean;
      if (val) {
        args.push('--process-response');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('format', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--format', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('allowExtraCols', itemIndex, false) as boolean;
      if (val) {
        args.push('--allow-extra-cols');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('strictDates', itemIndex, false) as boolean;
      if (val) {
        args.push('--strict-dates');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('dsSource', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--ds-source', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('dsUpdated', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--ds-updated', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('dsLicense', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--ds-license', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('okfType', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--okf-type', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('quiet', itemIndex, false) as boolean;
      if (val) {
        args.push('--quiet');
      }
    } catch {}

  try {
    const rawOutputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    const outputPath = rawOutputPath ? rawOutputPath.trim().replace(/^['"]|['"]$/g, '') : '';
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv describegpt',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'describegpt',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv describegpt': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
