import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv geoconvert'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeGeoconvert(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['geoconvert'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('geometry', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--geometry', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('latitude', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--latitude', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('longitude', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--longitude', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('maxLength', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--max-length', val);
      }
    } catch {}

  try {
    const outputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv geoconvert',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'geoconvert',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv geoconvert': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
