import type { IExecuteFunctions, INodeExecutionData } from "n8n-workflow";
import { NodeOperationError } from "n8n-workflow";
import { execa } from "execa";

/**
 * Action runner for 'qsv dedup'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeDedup(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter(
    "inputPath",
    itemIndex,
    "",
  ) as string;
  const inputPath = rawInputPath
    ? rawInputPath.trim().replace(/^['"]|['"]$/g, "")
    : "";
  if (!inputPath) {
    throw new NodeOperationError(
      this.getNode(),
      "Input CSV file path is required.",
      { itemIndex },
    );
  }

  const args: string[] = ["dedup"];

  // Collect options and flags
  try {
    const val = this.getNodeParameter("select", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--select", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("numeric", itemIndex, false) as boolean;
    if (val) {
      args.push("--numeric");
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "ignoreCase",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--ignore-case");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("sorted", itemIndex, false) as boolean;
    if (val) {
      args.push("--sorted");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("dupesOutput", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--dupes-output", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "humanReadable",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--human-readable");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("jobs", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--jobs", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noHeaders", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-headers");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("delimiter", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--delimiter", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("quiet", itemIndex, false) as boolean;
    if (val) {
      args.push("--quiet");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("memcheck", itemIndex, false) as boolean;
    if (val) {
      args.push("--memcheck");
    }
  } catch {}

  try {
    const rawOutputPath = this.getNodeParameter(
      "outputPath",
      itemIndex,
      "",
    ) as string;
    const outputPath = rawOutputPath
      ? rawOutputPath.trim().replace(/^['"]|['"]$/g, "")
      : "";
    if (outputPath) {
      args.push("--output", outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa("qsv", args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: "qsv dedup",
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: "dedup",
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv dedup': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
