import type { IExecuteFunctions, INodeExecutionData } from "n8n-workflow";
import { NodeOperationError } from "n8n-workflow";
import { execa } from "execa";

/**
 * Action runner for 'qsv searchset'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeSearchset(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter(
    "inputPath",
    itemIndex,
    "",
  ) as string;
  const inputPath = rawInputPath
    ? rawInputPath.trim().replace(/^['"]|['"]$/g, "")
    : "";
  if (!inputPath) {
    throw new NodeOperationError(
      this.getNode(),
      "Input CSV file path is required.",
      { itemIndex },
    );
  }

  const args: string[] = ["searchset"];

  // Collect options and flags
  try {
    const val = this.getNodeParameter(
      "ignoreCase",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--ignore-case");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("literal", itemIndex, false) as boolean;
    if (val) {
      args.push("--literal");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("exact", itemIndex, false) as boolean;
    if (val) {
      args.push("--exact");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("select", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--select", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "invertMatch",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--invert-match");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("unicode", itemIndex, false) as boolean;
    if (val) {
      args.push("--unicode");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("flag", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--flag", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "flagMatchesOnly",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--flag-matches-only");
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "unmatchedOutput",
      itemIndex,
      "",
    ) as string;
    if (val !== undefined && val !== "") {
      args.push("--unmatched-output", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("quick", itemIndex, false) as boolean;
    if (val) {
      args.push("--quick");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("count", itemIndex, false) as boolean;
    if (val) {
      args.push("--count");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("json", itemIndex, false) as boolean;
    if (val) {
      args.push("--json");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("sizeLimit", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--size-limit", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("dfaSizeLimit", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--dfa-size-limit", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("notOne", itemIndex, false) as boolean;
    if (val) {
      args.push("--not-one");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("jobs", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--jobs", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter("noHeaders", itemIndex, false) as boolean;
    if (val) {
      args.push("--no-headers");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("delimiter", itemIndex, "") as string;
    if (val !== undefined && val !== "") {
      args.push("--delimiter", val);
    }
  } catch {}

  try {
    const val = this.getNodeParameter(
      "progressbar",
      itemIndex,
      false,
    ) as boolean;
    if (val) {
      args.push("--progressbar");
    }
  } catch {}

  try {
    const val = this.getNodeParameter("quiet", itemIndex, false) as boolean;
    if (val) {
      args.push("--quiet");
    }
  } catch {}

  try {
    const rawOutputPath = this.getNodeParameter(
      "outputPath",
      itemIndex,
      "",
    ) as string;
    const outputPath = rawOutputPath
      ? rawOutputPath.trim().replace(/^['"]|['"]$/g, "")
      : "";
    if (outputPath) {
      args.push("--output", outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa("qsv", args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: "qsv searchset",
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: "searchset",
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv searchset': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
