import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv moarstats'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeMoarstats(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  const inputPath = rawInputPath ? rawInputPath.trim().replace(/^['"]|['"]$/g, '') : '';
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['moarstats'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('advanced', itemIndex, false) as boolean;
      if (val) {
        args.push('--advanced');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('epsilon', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--epsilon', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('statsOptions', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--stats-options', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('round', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--round', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('usePercentiles', itemIndex, false) as boolean;
      if (val) {
        args.push('--use-percentiles');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('pctThresholds', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--pct-thresholds', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('xsdGdateScan', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--xsd-gdate-scan', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('bivariate', itemIndex, false) as boolean;
      if (val) {
        args.push('--bivariate');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('bivariateStats', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--bivariate-stats', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('cardinalityThreshold', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--cardinality-threshold', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('bivariateBatch', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--bivariate-batch', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('joinInputs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--join-inputs', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('joinKeys', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--join-keys', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('joinType', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--join-type', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('progressbar', itemIndex, false) as boolean;
      if (val) {
        args.push('--progressbar');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('force', itemIndex, false) as boolean;
      if (val) {
        args.push('--force');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('jobs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--jobs', val);
      }
    } catch {}

  try {
    const rawOutputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    const outputPath = rawOutputPath ? rawOutputPath.trim().replace(/^['"]|['"]$/g, '') : '';
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  const qsvBin =
    process.env.DARTFX_QSV_BIN_PATH ||
    process.env.QSV_BIN_PATH ||
    process.env.QSV_PATH ||
    'qsv';

  try {
    const { stdout, stderr } = await execa(qsvBin, args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv moarstats',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'moarstats',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    if (error.code === 'ENOENT') {
      throw new NodeOperationError(
        this.getNode(),
        `The QSV CLI binary ('${qsvBin}') was not found. Please ensure QSV is installed and in your PATH, or specify its absolute path via the DARTFX_QSV_BIN_PATH or QSV_BIN_PATH environment variables. See: https://github.com/dathere/qsv`,
        { itemIndex },
      );
    }
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv moarstats': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
