import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv explode'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeExplode(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const rawInputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  const inputPath = rawInputPath ? rawInputPath.trim().replace(/^['"]|['"]$/g, '') : '';
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['explode'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('rename', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--rename', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('noHeaders', itemIndex, false) as boolean;
      if (val) {
        args.push('--no-headers');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('delimiter', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--delimiter', val);
      }
    } catch {}

  try {
    const rawOutputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    const outputPath = rawOutputPath ? rawOutputPath.trim().replace(/^['"]|['"]$/g, '') : '';
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv explode',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'explode',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    if (error.code === 'ENOENT') {
      throw new NodeOperationError(
        this.getNode(),
        "The 'qsv' CLI binary was not found in the system PATH. Please ensure QSV is installed on the host running n8n (e.g. 'brew install qsv' or add to Docker image). See: https://github.com/dathere/qsv",
        { itemIndex },
      );
    }
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv explode': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
