import type { IExecuteFunctions, INodeExecutionData } from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { execa } from 'execa';

/**
 * Action runner for 'qsv moarstats'
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export async function executeMoarstats(
  this: IExecuteFunctions,
  itemIndex: number,
): Promise<INodeExecutionData[]> {
  const inputPath = this.getNodeParameter('inputPath', itemIndex, '') as string;
  if (!inputPath) {
    throw new NodeOperationError(this.getNode(), 'Input CSV file path is required.', { itemIndex });
  }

  const args: string[] = ['moarstats'];

  // Collect options and flags
  try {
      const val = this.getNodeParameter('advanced', itemIndex, false) as boolean;
      if (val) {
        args.push('--advanced');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('epsilon', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--epsilon', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('statsOptions', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--stats-options', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('round', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--round', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('usePercentiles', itemIndex, false) as boolean;
      if (val) {
        args.push('--use-percentiles');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('pctThresholds', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--pct-thresholds', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('xsdGdateScan', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--xsd-gdate-scan', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('bivariate', itemIndex, false) as boolean;
      if (val) {
        args.push('--bivariate');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('bivariateStats', itemIndex, false) as boolean;
      if (val) {
        args.push('--bivariate-stats');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('cardinalityThreshold', itemIndex, false) as boolean;
      if (val) {
        args.push('--cardinality-threshold');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('bivariateBatch', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--bivariate-batch', val);
      }
    } catch {}

    try {
      const val = this.getNodeParameter('joinInputs', itemIndex, false) as boolean;
      if (val) {
        args.push('--join-inputs');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('joinKeys', itemIndex, false) as boolean;
      if (val) {
        args.push('--join-keys');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('joinType', itemIndex, false) as boolean;
      if (val) {
        args.push('--join-type');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('progressbar', itemIndex, false) as boolean;
      if (val) {
        args.push('--progressbar');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('force', itemIndex, false) as boolean;
      if (val) {
        args.push('--force');
      }
    } catch {}

    try {
      const val = this.getNodeParameter('jobs', itemIndex, '') as string;
      if (val !== undefined && val !== '') {
        args.push('--jobs', val);
      }
    } catch {}

  try {
    const outputPath = this.getNodeParameter('outputPath', itemIndex, '') as string;
    if (outputPath) {
      args.push('--output', outputPath);
    }
  } catch {}

  args.push(inputPath);

  try {
    const { stdout, stderr } = await execa('qsv', args);
    let resultJson: any;

    try {
      resultJson = JSON.parse(stdout);
    } catch {
      resultJson = {
        command: 'qsv moarstats',
        inputPath,
        rawOutput: stdout,
      };
    }

    return [
      {
        json: {
          success: true,
          command: 'moarstats',
          inputPath,
          result: resultJson,
        },
      },
    ];
  } catch (error: any) {
    throw new NodeOperationError(
      this.getNode(),
      `Failed executing 'qsv moarstats': ${error.stderr || error.message}`,
      { itemIndex },
    );
  }
}
