import type { INodeProperties } from 'n8n-workflow';

export const ApplyDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['apply'],
      },
    },
  },
  {
    displayName: 'Subcommand',
    name: 'subcommand',
    type: 'options',
    required: true,
    default: 'calcconv',
    options: [
        { name: 'calcconv', value: 'calcconv' },
        { name: 'dynfmt', value: 'dynfmt' },
        { name: 'emptyreplace', value: 'emptyreplace' },
        { name: 'operations', value: 'operations' },
        { name: 'summarize', value: 'summarize' },
    ],
    description: 'Subcommand to execute. Valid values: calcconv, dynfmt, emptyreplace, operations, summarize',
    displayOptions: {
      show: {
        operation: ['apply'],
      },
    },
  },
  {
    displayName: 'Operations',
    name: 'operations',
    type: 'string',
    required: false,
    default: '',
    description: 'The operation/s to apply.',
    displayOptions: {
      show: {
        operation: ['apply'],
      },
    },
  },
  {
    displayName: 'Column',
    name: 'column',
    type: 'string',
    required: false,
    default: '',
    description: 'The column/s whose values are summarized by the LLM. Used to build the default prompt. With a custom prompt (via the --prompt/--prompt-file options), any column can be referenced.',
    displayOptions: {
      show: {
        operation: ['apply'],
      },
    },
  },
  {
    displayName: 'Output File Path',
    name: 'outputPath',
    type: 'string',
    default: '',
    description: 'Optional path to write output file directly to disk (if omitted, results are returned in node output)',
    displayOptions: {
      show: {
        operation: ['apply'],
      },
    },
  },
  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv apply [⚡ Runs faster when CSV index (.qsv.idx) is present.] (Docs: https://github.com/dathere/qsv/blob/master/docs/help/apply.md)',
    displayOptions: {
      show: {
        operation: ['apply'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['apply'],
      },
    },
    options: [
    {
      displayName: 'Addl Props',
      name: 'addlProps',
      type: 'string',
      default: '',
      description: 'Additional model properties as a JSON object, e.g. \'{"reasoning_effort": "high", "temperature": 0.2}\'',
    },
    {
      displayName: 'Base Url',
      name: 'baseUrl',
      type: 'string',
      default: '',
      description: 'Base URL of the OpenAI API-compatible endpoint. Precedence: this flag > QSV_LLM_BASE_URL env var > http://localhost:1234/v1',
    },
    {
      displayName: 'Batch',
      name: 'batch',
      type: 'number',
      default: 50000,
      description: 'The number of rows per batch to load into memory, before running in parallel. Automatically determined for CSV files with more than 50000 rows. Set to 0 to load all rows in one batch. Set to 1 to force batch optimization even for files with less than 50000 rows.',
    },
    {
      displayName: 'Cache Dir',
      name: 'cacheDir',
      type: 'string',
      default: '~/.qsv-cache/apply-summarize',
      description: 'Directory for the disk cache. The cache TTL defaults to 28 days; set the QSV_DISKCACHE_TTL_SECS env var to change it. A value of 0 disables time-based expiration (entries are cached indefinitely). Use --no-cache to disable caching.',
    },
    {
      displayName: 'Comparand',
      name: 'comparand',
      type: 'string',
      default: '',
      description: 'The string to compare against for replace & similarity operations. Also used with numtocurrency operation to specify currency symbol.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Formatstr',
      name: 'formatstr',
      type: 'string',
      default: '',
      description: 'This option is used by several subcommands:',
    },
    {
      displayName: 'Fresh',
      name: 'fresh',
      type: 'boolean',
      default: false,
      description: 'Force fresh LLM calls, refreshing any cached values.',
    },
    {
      displayName: 'Max Tokens',
      name: 'maxTokens',
      type: 'number',
      default: 10000,
      description: 'Maximum number of tokens in the LLM output. Set to 0 to not send a max_tokens limit (automatically used for localhost endpoints).',
    },
    {
      displayName: 'Model',
      name: 'model',
      type: 'string',
      default: '',
      description: 'Model name compatible with the OpenAI API spec. Precedence: this flag > QSV_LLM_MODEL env var > openai/gpt-oss-20b',
    },
    {
      displayName: 'New Column',
      name: 'newColumn',
      type: 'string',
      default: '',
      description: 'Put the transformed values in a new column instead.',
    },
    {
      displayName: 'No Cache',
      name: 'noCache',
      type: 'boolean',
      default: false,
      description: 'Disable the disk cache (one LLM call per row, always).',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      description: 'When set, the first row will not be interpreted as headers.',
    },
    {
      displayName: 'On Error',
      name: 'onError',
      type: 'string',
      default: 'fail',
      description: 'What to do when an LLM request fails: "fail" aborts; "skip" writes an "<ERROR: ...>" cell and continues.',
    },
    {
      displayName: 'Prompt',
      name: 'prompt',
      type: 'string',
      default: '',
      description: 'MiniJinja prompt template rendered per record. Overrides the default prompt. Reference columns by their safe name.',
    },
    {
      displayName: 'Prompt File',
      name: 'promptFile',
      type: 'string',
      default: '',
      description: 'Read the prompt template from a file. Ignored if --prompt is set.',
    },
    {
      displayName: 'Rate Limit',
      name: 'rateLimit',
      type: 'number',
      default: 0,
      description: 'Seconds to sleep between LLM requests to avoid provider rate limits. Accepts fractional seconds (e.g. 0.5).',
    },
    {
      displayName: 'Rename',
      name: 'rename',
      type: 'string',
      default: '',
      description: 'New name for the transformed column.',
    },
    {
      displayName: 'Replacement',
      name: 'replacement',
      type: 'string',
      default: '',
      description: 'The string to use for the replace & emptyreplace operations. Also used with numtocurrency operation to conversion rate.',
    },
    {
      displayName: 'Stats',
      name: 'stats',
      type: 'boolean',
      default: false,
      description: 'Append two extra columns per row alongside --new-column: "<new-column>_elapsed_ms" (inference time in milliseconds) and "<new-column>_tokens" (total tokens used). For cached rows, these report the values captured when the summary was first computed.',
    },
    {
      displayName: 'Timeout',
      name: 'timeout',
      type: 'number',
      default: 300,
      description: 'Timeout for each LLM request in seconds (0 = no timeout).',
    },
    ],
  },
];
