import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv blake3' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const Blake3Description: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Keyed',
      name: 'keyed',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Use the keyed mode, reading the 32-byte key from stdin.',
    },
    {
      displayName: 'Derive Key',
      name: 'deriveKey',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Use the key derivation mode, with the given context string.',
    },
    {
      displayName: 'Length',
      name: 'length',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'The number of output bytes, before hex encoding.',
    },
    {
      displayName: 'No Mmap',
      name: 'noMmap',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Disable memory mapping. Also disables multithreading.',
    },
    {
      displayName: 'No Names',
      name: 'noNames',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Omit filenames in the output.',
    },
    {
      displayName: 'Raw',
      name: 'raw',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Write raw output bytes to stdout, rather than hex.',
    },
    {
      displayName: 'Tag',
      name: 'tag',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Output checksums in tagged format.',
    },
    {
      displayName: 'Check',
      name: 'check',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Read blake3 sums from the input files and check them.',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'The number of jobs to run in parallel for hashing.',
    },
    {
      displayName: 'Quiet',
      name: 'quiet',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['blake3'],
        },
      },
      description: 'Skip printing OK for each checked file.',
    },
];
