import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv cat' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const CatDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["cat"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["cat"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Pad",
    name: "pad",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["cat"],
      },
    },
    description:
      "When concatenating columns, this flag will cause all records to appear. It will pad each row if other CSV data isn't long enough.",
  },
  {
    displayName: "Flexible",
    name: "flexible",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["cat"],
      },
    },
    description:
      "When concatenating rows, this flag turns off validation that the input and output CSVs have the same number of columns. This is faster, but may result in invalid CSV data.",
  },
  {
    displayName: "Group",
    name: "group",
    type: "string",
    default: "none",
    displayOptions: {
      show: {
        operation: ["cat"],
      },
    },
    description:
      "When concatenating with rowskey, you can specify a grouping value which will be used as the first column in the output. This is useful when you want to know which file a row came from. Valid values are 'fullpath', 'parentdirfname', 'parentdirfstem', 'fname', 'fstem' and 'none'. A new column will be added to the beginning of each row using --group-name. If 'none' is specified, no grouping column will be added. [default: none]",
  },
  {
    displayName: "Group Name",
    name: "groupName",
    type: "string",
    default: "file",
    displayOptions: {
      show: {
        operation: ["cat"],
      },
    },
    description:
      "When concatenating with rowskey, this flag provides the name for the new grouping column. [default: file]",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["cat"],
      },
    },
    description:
      "When set, the first row will NOT be interpreted as column names. Note that this has no effect when concatenating columns.",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["cat"],
      },
    },
    description:
      "The field delimiter for reading CSV data. Must be a single character. (default: ,)",
  },
];
