import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv clipboard' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ClipboardDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["clipboard"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["clipboard"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Save",
    name: "save",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["clipboard"],
      },
    },
    description: "Save output to clipboard.",
  },
];
