import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv color' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ColorDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['color'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['color'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Color',
      name: 'color',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['color'],
        },
      },
      description: 'Force color on, even in situations where colors',
    },
    {
      displayName: 'Row Numbers',
      name: 'rowNumbers',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['color'],
        },
      },
      description: 'Show row numbers.',
    },
    {
      displayName: 'Title',
      name: 'title',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['color'],
        },
      },
      description: 'Add a title row above the headers.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['color'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
    {
      displayName: 'Memcheck',
      name: 'memcheck',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['color'],
        },
      },
      description: 'Check if there is enough memory to load the entire',
    },
];
