import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv count' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const CountDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Human Readable",
    name: "humanReadable",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description: "Comma separate counts.",
  },
  {
    displayName: "Width",
    name: "width",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description: "Also return the estimated widths of each record.",
  },
  {
    displayName: "Width No Delims",
    name: "widthNoDelims",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description:
      "Same as --width but does not count the delimiters in the width.",
  },
  {
    displayName: "Json",
    name: "json",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description: "Output the width stats in JSON format.",
  },
  {
    displayName: "No Polars",
    name: "noPolars",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description:
      'Use the "regular", single-threaded, streaming CSV reader instead',
  },
  {
    displayName: "Low Memory",
    name: "lowMemory",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description: "Use the Polars CSV Reader's low-memory mode. This mode",
  },
  {
    displayName: "Flexible",
    name: "flexible",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description: "Do not validate if the CSV has different number of",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description: "When set, the first row will be included in",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["count"],
      },
    },
    description: "The delimiter to use when reading CSV data.",
  },
];
