import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv datefmt' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const DatefmtDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Formatstr',
      name: 'formatstr',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: '=<string>        The date format to use for the datefmt operation. The date format to use. For formats, see https://docs.rs/chrono/latest/chrono/format/strftime/ Default to ISO 8601 / RFC 3339 date & time format - "%Y-%m-%dT%H:%M:%S%z" - e.g. 2001-07-08T00:34:60.026490+09:30 [default: %+]',
    },
    {
      displayName: 'New Column',
      name: 'newColumn',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'Put the transformed values in new column(s) instead of replacing the source column(s). When the selection has multiple columns, pass a comma-separated list of new column names that match the selection count (e.g. --new-column \'open_iso,close_iso\' for \'OpenDate,CloseDate\'). To rename in place instead, use --rename.',
    },
    {
      displayName: 'Rename',
      name: 'rename',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'New name for the transformed column.',
    },
    {
      displayName: 'Prefer Dmy',
      name: 'preferDmy',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'Prefer to parse dates in dmy format. Otherwise, use mdy format.',
    },
    {
      displayName: 'Keep Zero Time',
      name: 'keepZeroTime',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'If a formatted date ends with "T00:00:00+00:00", keep the time instead of removing it.',
    },
    {
      displayName: 'Input Tz',
      name: 'inputTz',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: '=<string>         The timezone to use for the input date if the date does not have timezone specified. The timezone must be a valid IANA timezone name or the string "local" for the local timezone. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a list of valid timezone names. [default: UTC]',
    },
    {
      displayName: 'Output Tz',
      name: 'outputTz',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: '=<string>        The timezone to use for the output date. The timezone must be a valid IANA timezone name or the string "local". [default: UTC]',
    },
    {
      displayName: 'Default Tz',
      name: 'defaultTz',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: '=<string>       Fallback timezone consulted only when --input-tz or --output-tz is set to "local" but local-timezone detection fails. Defaults to UTC. Does NOT override the --input-tz / --output-tz defaults — use --utc to force both input and output to UTC. The timezone must be a valid IANA timezone name or the string "local".',
    },
    {
      displayName: 'Utc',
      name: 'utc',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'Shortcut for --input-tz and --output-tz set to UTC.',
    },
    {
      displayName: 'Zulu',
      name: 'zulu',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'Shortcut for --output-tz set to UTC and --formatstr set to "%Y-%m-%dT%H:%M:%SZ".',
    },
    {
      displayName: 'Ts Resolution',
      name: 'tsResolution',
      type: 'string',
      default: 'sec',
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'The resolution to use when parsing Unix timestamps. Valid values are "sec", "milli", "micro", "nano". [default: sec]',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'The number of jobs to run in parallel. When not set, the number of jobs is set to the number of CPUs detected.',
    },
    {
      displayName: 'Batch',
      name: 'batch',
      type: 'string',
      default: '50000',
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'The number of rows per batch to load into memory, before running in parallel. Automatically determined for CSV files with more than 50000 rows. Set to 0 to load all rows in one batch. Set to 1 to force batch optimization even for files with less than 50000 rows. [default: 50000]',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'When set, the first row will not be interpreted as headers.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Progressbar',
      name: 'progressbar',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['datefmt'],
        },
      },
      description: 'Show progress bars. Not valid for stdin.',
    },
];
