import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv enum' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const EnumDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'New Column',
      name: 'newColumn',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Name of the column to create.',
    },
    {
      displayName: 'Start',
      name: 'start',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'The value to start the enumeration from.',
    },
    {
      displayName: 'Increment',
      name: 'increment',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'The value to increment the enumeration by.',
    },
    {
      displayName: 'Constant',
      name: 'constant',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Fill a new column with the given value.',
    },
    {
      displayName: 'Copy',
      name: 'copy',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Name of a column to copy.',
    },
    {
      displayName: 'Uuid4',
      name: 'uuid4',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'When set, the column will be populated with',
    },
    {
      displayName: 'Uuid7',
      name: 'uuid7',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'When set, the column will be populated with',
    },
    {
      displayName: 'Hash',
      name: 'hash',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Create a new column filled with the hash of the',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'When set, the first row will not be interpreted',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
];
