import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv enum' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const EnumDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'New Column',
      name: 'newColumn',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Name of the column to create. Will default to "index".',
    },
    {
      displayName: 'Start',
      name: 'start',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'The value to start the enumeration from. Only applies in Increment mode. (default: 0)',
    },
    {
      displayName: 'Increment',
      name: 'increment',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'The value to increment the enumeration by. Only applies in Increment mode. (default: 1)',
    },
    {
      displayName: 'Constant',
      name: 'constant',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Fill a new column with the given value. Changes the default column name to "constant" unless overridden by --new-column. To specify a null value, pass the literal "<NULL>".',
    },
    {
      displayName: 'Copy',
      name: 'copy',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Name of a column to copy. Changes the default column name to "{column}_copy" unless overridden by --new-column.',
    },
    {
      displayName: 'Uuid4',
      name: 'uuid4',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'When set, the column will be populated with uuids (v4) instead of the incremental identifier. Changes the default column name to "uuid4" unless overridden by --new-column.',
    },
    {
      displayName: 'Uuid7',
      name: 'uuid7',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'When set, the column will be populated with uuids (v7) instead of the incremental identifier. uuid v7 is a time-based uuid and is monotonically increasing. See https://buildkite.com/blog/goodbye-integers-hello-uuids Changes the default column name to "uuid7" unless overridden by --new-column.',
    },
    {
      displayName: 'Hash',
      name: 'hash',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'Create a new column filled with the hash of the given column/s. Use "1-" to hash all columns. Changes the default column name to "hash" unless overridden by --new-column. Will remove an existing "hash" column if it exists.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'When set, the first row will not be interpreted as headers.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['enum'],
        },
      },
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
];
