import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv explode' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ExplodeDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['explode'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['explode'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Rename',
      name: 'rename',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['explode'],
        },
      },
      description: 'New name for the exploded column.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['explode'],
        },
      },
      description: 'When set, the first row will not be interpreted',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['explode'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
];
