import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv extdedup' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ExtdedupDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Select',
      name: 'select',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'Select a subset of columns to dedup. Note that the outputs will remain at the full width of the CSV. If --select is NOT set, extdedup will work in LINE MODE, deduping the input as a text file on a line-by-line basis.',
    },
    {
      displayName: 'No Output',
      name: 'noOutput',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'Do not write deduplicated output to <output>. Use this if you only want to know the duplicate count. Applies to both CSV MODE and LINE MODE.',
    },
    {
      displayName: 'Dupes Output',
      name: 'dupesOutput',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'Write duplicates to <file>. In CSV MODE, <file> is a valid CSV with the same columns as the input plus a leading "dupe_rowno" column (1-based data row number). In LINE MODE, <file> is NOT a valid CSV — each duplicate line is prefixed by its 0-based file line index and a tab character.',
    },
    {
      displayName: 'Human Readable',
      name: 'humanReadable',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'Comma separate duplicate count.',
    },
    {
      displayName: 'Memory Limit',
      name: 'memoryLimit',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'How much memory to use before deduping switches to a temporary file on disk (see --temp-dir). If less than 50, this is a percentage of total memory. If more than 50, this is the memory in MB to allocate, capped at 90 percent of total memory. Defaults to 100 MB. Raising this mostly just uses more memory, as deduping on disk needs far less memory per row.',
    },
    {
      displayName: 'Temp Dir',
      name: 'tempDir',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'Directory to store temporary hash table file. If not specified, defaults to operating system temp directory.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'When set, the first row will not be interpreted as headers. That is, it will be deduped with the rest of the rows. Otherwise, the first row will always appear as the header row in the output.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Quiet',
      name: 'quiet',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['extdedup'],
        },
      },
      description: 'Do not print duplicate count to stderr.',
    },
];
