import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv extsort' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ExtsortDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Select',
      name: 'select',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'Select a subset of columns to sort (CSV MODE). Note that the outputs will remain at the full width of the CSV. If --select is NOT set, extsort will work in LINE MODE, sorting the input as a text file on a line-by-line basis.',
    },
    {
      displayName: 'Reverse',
      name: 'reverse',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'Reverse order',
    },
    {
      displayName: 'Memory Limit',
      name: 'memoryLimit',
      type: 'string',
      default: '20',
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'The maximum amount of memory to buffer the external merge sort. If less than 50, this is a percentage of total memory. If more than 50, this is the memory in MB to allocate, capped at 90 percent of total memory. [default: 20]',
    },
    {
      displayName: 'Tmp Dir',
      name: 'tmpDir',
      type: 'string',
      default: './',
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'The directory to use for externally sorting file segments. [default: ./]',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'The number of jobs to run in parallel. When not set, the number of jobs is set to the number of CPUs detected.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['extsort'],
        },
      },
      description: 'When set, the first row will not be interpreted as headers and will be sorted with the rest of the rows. Otherwise, the first row will always appear as the header row in the output.',
    },
];
