import type { INodeProperties } from 'n8n-workflow';

export const FetchDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['fetch'],
      },
    },
  },

  {
    displayName: 'Output File Path',
    name: 'outputPath',
    type: 'string',
    default: '',
    description: 'Optional path to write output file directly to disk (if omitted, results are returned in node output)',
    displayOptions: {
      show: {
        operation: ['fetch'],
      },
    },
  },
  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv fetch (Docs: https://github.com/dathere/qsv/blob/master/docs/help/fetch.md)',
    displayOptions: {
      show: {
        operation: ['fetch'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['fetch'],
      },
    },
    options: [
    {
      displayName: 'Cache Error',
      name: 'cacheError',
      type: 'boolean',
      default: false,
      description: 'Cache error responses even if a request fails. If an identical URL is requested, the cached error is returned. Otherwise, the fetch is attempted again for --max-retries.',
    },
    {
      displayName: 'Cookies',
      name: 'cookies',
      type: 'boolean',
      default: false,
      description: 'Allow cookies.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Disk Cache',
      name: 'diskCache',
      type: 'boolean',
      default: false,
      description: 'Use a persistent disk cache for responses. The cache is stored in the directory specified by --disk-cache-dir. If the directory does not exist, it will be created. If the directory exists, it will be used as is. It has a default Time To Live (TTL)/lifespan of 28 days and cache hits do not refresh the TTL of cached values. Adjust the QSV_DISKCACHE_TTL_SECS & QSV_DISKCACHE_TTL_REFRESH env vars to change DiskCache settings. A QSV_DISKCACHE_TTL_SECS of 0 disables time-based expiration (entries are cached indefinitely).',
    },
    {
      displayName: 'Disk Cache Dir',
      name: 'diskCacheDir',
      type: 'string',
      default: '',
      description: 'The directory <dir> to store the disk cache. Note that if the directory does not exist, it will be created. If the directory exists, it will be used as is, and will not be flushed. This option allows you to maintain several disk caches for different fetch jobs (e.g. one for geocoding, another for weather, etc.) [default: ~/.qsv-cache/fetch]',
    },
    {
      displayName: 'Flush Cache',
      name: 'flushCache',
      type: 'boolean',
      default: false,
      description: 'Flush all the keys in the current cache on startup. This only applies to Disk and Redis caches.',
    },
    {
      displayName: 'Http Header',
      name: 'httpHeader',
      type: 'string',
      default: '',
      description: 'Append custom header(s) to the HTTP header. Pass multiple key-value pairs by adding this option multiple times, once for each pair. The key and value should be separated by a colon.',
    },
    {
      displayName: 'Jaq',
      name: 'jaq',
      type: 'string',
      default: '',
      description: 'Apply jaq selector to API returned JSON value. Mutually exclusive with --jaqfile,',
    },
    {
      displayName: 'Jaqfile',
      name: 'jaqfile',
      type: 'string',
      default: '',
      description: 'Load jaq selector from file instead. Mutually exclusive with --jaq.',
    },
    {
      displayName: 'Max Errors',
      name: 'maxErrors',
      type: 'string',
      default: '',
      description: 'Maximum number of errors before aborting. Set to zero (0) to continue despite errors. [default: 10 ]',
    },
    {
      displayName: 'Max Retries',
      name: 'maxRetries',
      type: 'string',
      default: '',
      description: 'Maximum number of retries per record before an error is raised. [default: 5]',
    },
    {
      displayName: 'Mem Cache Size',
      name: 'memCacheSize',
      type: 'string',
      default: '',
      description: 'Maximum number of entries in the in-memory LRU cache. [default: 2000000]',
    },
    {
      displayName: 'New Column',
      name: 'newColumn',
      type: 'string',
      default: '',
      description: 'Put the fetched values in a new column. Specifying this option results in a CSV. Otherwise, the output is in JSONL format.',
    },
    {
      displayName: 'No Cache',
      name: 'noCache',
      type: 'boolean',
      default: false,
      description: 'Do not cache responses.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      description: 'When set, the first row will not be interpreted as headers. Namely, it will be sorted with the rest of the rows. Otherwise, the first row will always appear as the header row in the output.',
    },
    {
      displayName: 'Pretty',
      name: 'pretty',
      type: 'boolean',
      default: false,
      description: 'Prettify JSON responses. Otherwise, they\'re minified. If the response is not in JSON format, it\'s passed through. Note that --pretty requires the --new-column option.',
    },
    {
      displayName: 'Progressbar',
      name: 'progressbar',
      type: 'boolean',
      default: false,
      description: 'Show progress bars. Will also show the cache hit rate upon completion. Not valid for stdin.',
    },
    {
      displayName: 'Rate Limit',
      name: 'rateLimit',
      type: 'string',
      default: '',
      description: 'Rate Limit in Queries Per Second (max: 1000). Note that fetch dynamically throttles as well based on rate-limit and retry-after response headers. Set to 0 to go as fast as possible, automatically throttling as required. CAUTION: Only use zero for APIs that use RateLimit and/or Retry-After headers, otherwise your fetch job may look like a Denial Of Service attack. Even though zero is the default, this is mitigated by --max-errors having a default of 10. [default: 0 ]',
    },
    {
      displayName: 'Redis Cache',
      name: 'redisCache',
      type: 'boolean',
      default: false,
      description: 'Use Redis to cache responses. It connects to "redis://127.0.0.1:6379/1" with a connection pool size of 20, with a TTL of 28 days, and a cache hit NOT renewing an entry\'s TTL. Adjust the QSV_REDIS_CONNSTR, QSV_REDIS_MAX_POOL_SIZE, QSV_REDIS_TTL_SECS & QSV_REDIS_TTL_REFRESH env vars respectively to change Redis settings. A QSV_REDIS_TTL_SECS of 0 disables expiration (entries cached indefinitely). This option is ignored if the --disk-cache option is enabled.',
    },
    {
      displayName: 'Report',
      name: 'report',
      type: 'string',
      default: '',
      description: 'Creates a report of the fetch job. The report has the same name as the input file with the ".fetch-report" suffix. There are two kinds of report - d for "detailed" & s for "short". The detailed report has the same columns as the input CSV with six additional columns - qsv_fetch_url, qsv_fetch_status, qsv_fetch_cache_hit, qsv_fetch_retries, qsv_fetch_elapsed_ms & qsv_fetch_response. The short report only has the six columns without the "qsv_fetch_" prefix. [default: none]',
    },
    {
      displayName: 'Store Error',
      name: 'storeError',
      type: 'boolean',
      default: false,
      description: 'On error, store error code/message instead of blank value.',
    },
    {
      displayName: 'Timeout',
      name: 'timeout',
      type: 'string',
      default: '',
      description: 'Timeout for each URL request. [default: 30 ]',
    },
    {
      displayName: 'Url Template',
      name: 'urlTemplate',
      type: 'string',
      default: '',
      description: 'URL template to use. Use column names enclosed with curly braces to insert the CSV data for a record. Mutually exclusive with url-column.',
    },
    {
      displayName: 'User Agent',
      name: 'userAgent',
      type: 'string',
      default: '',
      description: 'Specify custom user agent. It supports the following variables - $QSV_VERSION, $QSV_TARGET, $QSV_BIN_NAME, $QSV_KIND and $QSV_COMMAND. Try to follow the syntax here - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent',
    },
    ],
  },
];
