import type { INodeProperties } from 'n8n-workflow';

export const FetchpostDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['fetchpost'],
      },
    },
  },
  {
    displayName: 'URL Column',
    name: 'urlColumn',
    type: 'string',
    required: true,
    default: '',
    description: 'Name of the column with the URL. Otherwise, if the argument starts with `http`, the URL to use.',
    displayOptions: {
      show: {
        operation: ['fetchpost'],
      },
    },
  },
  {
    displayName: 'Column List',
    name: 'columnList',
    type: 'string',
    required: true,
    default: '',
    description: 'Comma-delimited list of columns to insert into the HTTP Post body. Uses `qsv select` syntax - i.e. Columns can be referenced by index or by name if there is a header row (duplicate column names can be disambiguated with more indexing). Column ranges can also be specified. Finally, columns can be selected using regular expressions. See \'qsv select --help\' for examples.',
    displayOptions: {
      show: {
        operation: ['fetchpost'],
      },
    },
  },
  {
    displayName: 'Output File Path',
    name: 'outputPath',
    type: 'string',
    default: '',
    description: 'Optional path to write output file directly to disk (if omitted, results are returned in node output)',
    displayOptions: {
      show: {
        operation: ['fetchpost'],
      },
    },
  },
  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv fetchpost [⚡ Runs faster when CSV index (.qsv.idx) is present.] (Docs: https://github.com/dathere/qsv/blob/master/docs/help/fetchpost.md)',
    displayOptions: {
      show: {
        operation: ['fetchpost'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['fetchpost'],
      },
    },
    options: [
    {
      displayName: 'Cache Error',
      name: 'cacheError',
      type: 'boolean',
      default: false,
      description: 'Cache error responses even if a request fails. If an identical URL is requested, the cached error is returned. Otherwise, the fetch is attempted again for --max-retries.',
    },
    {
      displayName: 'Compress',
      name: 'compress',
      type: 'boolean',
      default: false,
      description: 'Compress the HTTP request body using gzip. Note that most servers do not support compressed request bodies unless they are specifically configured to do so. This should only be enabled for trusted scenarios where "zip bombs" are not a concern. see https://github.com/postmanlabs/httpbin/issues/577#issuecomment-875814469 for more info.',
    },
    {
      displayName: 'Content Type',
      name: 'contentType',
      type: 'string',
      default: '',
      description: 'Overrides automatic content types for `<column-list>` (`application/x-www-form-urlencoded`) and `--payload-tpl` (`application/json`). Typical alternative values are `multipart/form-data` and `text/plain`. It is the responsibility of the user to format the payload accordingly when using --payload-tpl.',
    },
    {
      displayName: 'Cookies',
      name: 'cookies',
      type: 'boolean',
      default: false,
      description: 'Allow cookies.',
    },
    {
      displayName: 'Default Encoding',
      name: 'defaultEncoding',
      type: 'string',
      default: 'utf-8',
      description: 'Fallback character encoding used to decode a response body when the server does NOT send a charset parameter in its Content-Type header. Accepts WHATWG encoding labels, e.g. utf-8, windows-1252, iso-8859-1, shift_jis, euc-jp, koi8-r. When the server DOES send a charset, the server always wins and this option is ignored.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Disk Cache',
      name: 'diskCache',
      type: 'boolean',
      default: false,
      description: 'Use a persistent disk cache for responses. The cache is stored in the directory specified by --disk-cache-dir. If the directory does not exist, it will be created. If the directory exists, it will be used as is. It has a default Time To Live (TTL)/lifespan of 28 days and cache hits do not refresh the TTL of cached values. Adjust the QSV_DISKCACHE_TTL_SECS & QSV_DISKCACHE_TTL_REFRESH env vars to change DiskCache settings. A QSV_DISKCACHE_TTL_SECS of 0 disables time-based expiration (entries are cached indefinitely).',
    },
    {
      displayName: 'Disk Cache Dir',
      name: 'diskCacheDir',
      type: 'string',
      default: '~/.qsv-cache/fetchpost',
      description: 'The directory <dir> to store the disk cache. Note that if the directory does not exist, it will be created. If the directory exists, it will be used as is, and will not be flushed. This option allows you to maintain several disk caches for different fetchpost jobs (e.g. one for geocoding, another for weather, etc.)',
    },
    {
      displayName: 'Flush Cache',
      name: 'flushCache',
      type: 'boolean',
      default: false,
      description: 'Flush all the keys in the current cache on startup. This only applies to Disk and Redis caches.',
    },
    {
      displayName: 'Globals Json',
      name: 'globalsJson',
      type: 'string',
      default: '',
      description: 'A JSON file containing global variables. When posting as an HTML Form, this file is added to the Form data. When constructing a payload using a MiniJinja template, the JSON properties can be accessed in templates using the "qsv_g" namespace (e.g. {{qsv_g.api_key}}, {{qsv_g.base_url}}).',
    },
    {
      displayName: 'Http Header',
      name: 'httpHeader',
      type: 'string',
      default: '',
      description: 'Append custom header(s) to the HTTP header. Pass multiple key-value pairs by adding this option multiple times, once for each pair. The key and value should be separated by a colon.',
    },
    {
      displayName: 'Jaq',
      name: 'jaq',
      type: 'string',
      default: '',
      description: 'Apply jaq selector to API returned JSON response. Mutually exclusive with --jaqfile.',
    },
    {
      displayName: 'Jaqfile',
      name: 'jaqfile',
      type: 'string',
      default: '',
      description: 'Load jaq selector from file instead. Mutually exclusive with --jaq.',
    },
    {
      displayName: 'Max Errors',
      name: 'maxErrors',
      type: 'number',
      default: 10,
      description: 'Maximum number of errors before aborting. Set to zero (0) to continue despite errors.',
    },
    {
      displayName: 'Max Retries',
      name: 'maxRetries',
      type: 'number',
      default: 5,
      description: 'Maximum number of retries per record before an error is raised.',
    },
    {
      displayName: 'Mem Cache Size',
      name: 'memCacheSize',
      type: 'number',
      default: 2000000,
      description: 'Maximum number of entries in the in-memory LRU cache.',
    },
    {
      displayName: 'New Column',
      name: 'newColumn',
      type: 'string',
      default: '',
      description: 'Put the fetched values in a new column. Specifying this option results in a CSV. Otherwise, the output is in JSONL format.',
    },
    {
      displayName: 'No Cache',
      name: 'noCache',
      type: 'boolean',
      default: false,
      description: 'Do not cache responses.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      description: 'When set, the first row will not be interpreted as headers. Namely, it will be sorted with the rest of the rows. Otherwise, the first row will always appear as the header row in the output.',
    },
    {
      displayName: 'Payload Tpl',
      name: 'payloadTpl',
      type: 'string',
      default: '',
      description: 'Instead of <column-list>, use a MiniJinja template file to render a JSON payload in the HTTP Post body. You can also use --payload-tpl to render a non-JSON payload, but --content-type will have to be set manually. If a rendered JSON is invalid, `fetchpost` will abort and return an error.',
    },
    {
      displayName: 'Pretty',
      name: 'pretty',
      type: 'boolean',
      default: false,
      description: 'Prettify JSON responses. Otherwise, they\'re minified. If the response is not in JSON format, it\'s passed through unchanged. Note that --pretty requires the --new-column option.',
    },
    {
      displayName: 'Rate Limit',
      name: 'rateLimit',
      type: 'number',
      default: 0,
      description: 'Rate Limit in Queries Per Second (max: 1000). Note that fetch dynamically throttles as well based on rate-limit and retry-after response headers. Set to 0 to go as fast as possible, automatically throttling as required. CAUTION: Only use zero for APIs that use RateLimit and/or Retry-After headers, otherwise your fetchpost job may look like a Denial Of Service attack. Even though zero is the default, this is mitigated by --max-errors having a default of 10.',
    },
    {
      displayName: 'Report',
      name: 'report',
      type: 'string',
      default: 'none',
      description: 'Creates a report of the fetchpost job. The report has the same name as the input file with the ".fetchpost-report" suffix. There are two kinds of report - d for "detailed" & s for "short". The detailed report has the same columns as the input CSV with seven additional columns - qsv_fetchp_url, qsv_fetchp_form, qsv_fetchp_status, qsv_fetchp_cache_hit, qsv_fetchp_retries, qsv_fetchp_elapsed_ms & qsv_fetchp_response. The short report only has the seven columns without the "qsv_fetchp_" prefix.',
    },
    {
      displayName: 'Store Error',
      name: 'storeError',
      type: 'boolean',
      default: false,
      description: 'On error, store error code/message instead of blank value.',
    },
    {
      displayName: 'Timeout',
      name: 'timeout',
      type: 'number',
      default: 30,
      description: 'Timeout for each URL request.',
    },
    ],
  },
];
