import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv fixedwidth' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const FixedwidthDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['fixedwidth'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fixedwidth'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Positions',
      name: 'positions',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fixedwidth'],
        },
      },
      description: 'Comma-separated, 1-based starting byte position of each column (e.g. "1,10,15"). Overrides any "#..." header comment in the input.',
    },
    {
      displayName: 'Widths',
      name: 'widths',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fixedwidth'],
        },
      },
      description: 'Comma-separated width, in bytes, of each column (e.g. "9,5,20"). An alternative to --positions; the two are mutually exclusive.',
    },
];
