import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv fixlengths' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const FixlengthsDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Length',
      name: 'length',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'Forcefully set the length of each record. If a record is not the size given, then it is truncated or expanded as appropriate.',
    },
    {
      displayName: 'Remove Empty',
      name: 'removeEmpty',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'Remove empty columns.',
    },
    {
      displayName: 'Insert',
      name: 'insert',
      type: 'string',
      default: '0',
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'If empty fields need to be inserted, insert them at <pos>. If <pos> is zero, then it is inserted at the end of each record. If <pos> is negative, it is inserted from the END of each record going backwards. If <pos> is positive, it is inserted from the BEGINNING of each record going forward. [default: 0]',
    },
    {
      displayName: 'Quote',
      name: 'quote',
      type: 'string',
      default: '"',
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'The quote character to use. [default: "]',
    },
    {
      displayName: 'Escape',
      name: 'escape',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'The escape character to use. When not specified, quotes are escaped by doubling them.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Quiet',
      name: 'quiet',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['fixlengths'],
        },
      },
      description: 'Don\'t print removed column information.',
    },
];
