import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv fmt' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const FmtDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Out Delimiter',
      name: 'outDelimiter',
      type: 'string',
      default: ',',
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'The field delimiter for writing CSV data. Must be a single character. "T" or "\\t" can be used as shortcuts for tab. [default: ,]',
    },
    {
      displayName: 'Crlf',
      name: 'crlf',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'Use \'\\r\\n\' line endings in the output.',
    },
    {
      displayName: 'Ascii',
      name: 'ascii',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'Use ASCII field/record separators: Unit Separator (U+001F) for fields and Record Separator (U+001E) for records. Substitute (U+001A) is used as the quote character.',
    },
    {
      displayName: 'Quote',
      name: 'quote',
      type: 'string',
      default: '"',
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'The quote character to use. Must be a single character. [default: "]',
    },
    {
      displayName: 'Quote Always',
      name: 'quoteAlways',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'Put quotes around every value.',
    },
    {
      displayName: 'Quote Never',
      name: 'quoteNever',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'Never put quotes around any value.',
    },
    {
      displayName: 'Escape',
      name: 'escape',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'The escape character to use. When not specified, quotes are escaped by doubling them.',
    },
    {
      displayName: 'No Final Newline',
      name: 'noFinalNewline',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'Do not write a newline at the end of the output. This makes it easier to paste the output into Excel.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['fmt'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
];
