import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv foreach' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ForeachDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["foreach"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["foreach"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Unify",
    name: "unify",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["foreach"],
      },
    },
    description:
      "If the output of the executed command is a CSV, unify the result by skipping headers on each subsequent command. Does not work when --dry-run is true. The first child's CSV header row becomes canonical; later children are expected to produce the same schema.",
  },
  {
    displayName: "New Column",
    name: "newColumn",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["foreach"],
      },
    },
    description:
      "If unifying, add a new column with given name and copying the value of the current input file line.",
  },
  {
    displayName: "Dry Run",
    name: "dryRun",
    type: "string",
    default: "true",
    displayOptions: {
      show: {
        operation: ["foreach"],
      },
    },
    description:
      "If set to true (the default for safety reasons), the commands are sent to stdout instead of executing them. If set to a file, the commands will be written to the specified text file instead of executing them. The file is only created after all flag validation succeeds, so a conflicting flag combination will not truncate an existing file. Only if set to false will the commands be actually executed. [default: true]",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["foreach"],
      },
    },
    description: "When set, the file will be considered to have no",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["foreach"],
      },
    },
    description: "The field delimiter for reading CSV data.",
  },
  {
    displayName: "Progressbar",
    name: "progressbar",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["foreach"],
      },
    },
    description: "Show progress bars. Not valid for stdin.",
  },
];
