import type { INodeProperties } from 'n8n-workflow';

export const GeocodeDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['geocode'],
      },
    },
  },
  {
    displayName: 'Subcommand',
    name: 'subcommand',
    type: 'options',
    required: true,
    default: 'cache-clear',
    options: [
        { name: 'cache-clear', value: 'cache-clear' },
        { name: 'cache-info', value: 'cache-info' },
        { name: 'cache-prune', value: 'cache-prune' },
        { name: 'countryinfo', value: 'countryinfo' },
        { name: 'countryinfonow', value: 'countryinfonow' },
        { name: 'iplookup', value: 'iplookup' },
        { name: 'iplookupnow', value: 'iplookupnow' },
        { name: 'opencage', value: 'opencage' },
        { name: 'opencagenow', value: 'opencagenow' },
        { name: 'reverse', value: 'reverse' },
        { name: 'reversenow', value: 'reversenow' },
        { name: 'suggest', value: 'suggest' },
        { name: 'suggestnow', value: 'suggestnow' },
    ],
    description: 'Subcommand to execute. Valid values: cache-clear, cache-info, cache-prune, countryinfo, countryinfonow, iplookup, iplookupnow, opencage, opencagenow, reverse, reversenow, suggest, suggestnow',
    displayOptions: {
      show: {
        operation: ['geocode'],
      },
    },
  },
  {
    displayName: 'Column',
    name: 'column',
    type: 'string',
    required: false,
    default: '',
    description: 'The column to geocode. Used by suggest, reverse & countryinfo subcommands. For suggest, it must be a column with a City string pattern. For reverse, it must be a column using WGS 84 coordinates in "lat, long" or "(lat, long)" format. For countryinfo, it must be a column with a ISO 3166-1 alpha-2 country code. For iplookup, it must be a column with an IP address or a URL. For opencage, it may be a free-form address OR a WGS 84 coordinate. Note that you can use column selector syntax to select the column, but only the first column will be used. See `select --help` for more information.',
    displayOptions: {
      show: {
        operation: ['geocode'],
      },
    },
  },
  {
    displayName: 'Location',
    name: 'location',
    type: 'string',
    required: false,
    default: '',
    description: 'The location to geocode for suggestnow, reversenow, countryinfonow and iplookupnow subcommands. For suggestnow, its a City string pattern. For reversenow, it must be a WGS 84 coordinate. For countryinfonow, it must be a ISO 3166-1 alpha-2 code. For iplookupnow, it must be an IP address or a URL. For opencagenow, it must be an address OR a WGS 84 coordinate.',
    displayOptions: {
      show: {
        operation: ['geocode'],
      },
    },
  },
  {
    displayName: 'Index File Path',
    name: 'indexFile',
    type: 'string',
    required: false,
    default: '',
    description: 'The alternate geonames index file to use. It must be a .rkyv file. For convenience, if this is set to a published population floor (15000 or 1000), it will download that prebuilt English-only Geonames index rkyv file from the qsv GitHub repo for the current qsv version and use it. Only used by the index-load subcommand.',
    displayOptions: {
      show: {
        operation: ['geocode'],
      },
    },
  },
  {
    displayName: 'Output File Path',
    name: 'outputPath',
    type: 'string',
    default: '',
    description: 'Optional path to write output file directly to disk (if omitted, results are returned in node output)',
    displayOptions: {
      show: {
        operation: ['geocode'],
      },
    },
  },
  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv geocode [⚡ Runs faster when CSV index (.qsv.idx) is present.] (Docs: https://github.com/dathere/qsv/blob/master/docs/help/geocode.md)',
    displayOptions: {
      show: {
        operation: ['geocode'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['geocode'],
      },
    },
    options: [
    {
      displayName: 'Admin1',
      name: 'admin1',
      type: 'string',
      default: '',
      description: 'The comma-delimited, case-insensitive list of admin1s to filter for. Only a place inside one of them is returned. A value with no match inside them is left unchanged (or set to the invalid-result value), and the number of such values is reported on stderr.',
    },
    {
      displayName: 'Batch',
      name: 'batch',
      type: 'number',
      default: 50000,
      description: 'The number of rows per batch to load into memory, before running in parallel. Set to 0 to load all rows in one batch.',
    },
    {
      displayName: 'Cache Dir',
      name: 'cacheDir',
      type: 'string',
      default: '~/.qsv-cache',
      description: 'The directory to use for caching the Geonames cities index and the persistent on-disk OpenCage result cache. If the directory does not exist, qsv will attempt to create it. If the QSV_CACHE_DIR envvar is set, it will be used instead.',
    },
    {
      displayName: 'Cache Ttl',
      name: 'cacheTtl',
      type: 'number',
      default: 1209600,
      description: 'Time-to-live for the persistent on-disk OpenCage result cache. A value of 0 disables time-based expiration (entries are cached indefinitely). Use --no-cache to disable caching entirely.',
    },
    {
      displayName: 'Cities Url',
      name: 'citiesUrl',
      type: 'string',
      default: 'https://download.geonames.org/export/dump/cities15000.zip',
      description: 'The URL to download the Geonames cities file from. There are several available at https://download.geonames.org/export/dump/. cities500.zip   - cities with populations > 500; ~200k cities, 56mb cities1000.zip  - population > 1000; ~140k cities, 44mb cities5000.zip  - population > 5000; ~53k cities, 21mb cities15000.zip - population > 15000; ~26k cities, 13mb Note that the more cities are included, the larger the local index file will be, lookup times will be slower, and the search results will be different. For convenience, if this is set to 500, 1000, 5000 or 15000, it will be converted to a geonames cities URL.',
    },
    {
      displayName: 'Country',
      name: 'country',
      type: 'string',
      default: '',
      description: 'The comma-delimited, case-insensitive list of countries to filter for. Country is specified as a ISO 3166-1 alpha-2 (two-letter) country code. https://en.wikipedia.org/wiki/ISO_3166-2',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Force',
      name: 'force',
      type: 'boolean',
      default: false,
      description: 'Force update the Geonames cities index. If not set, qsv will check if there are updates available at Geonames.org before updating the index.',
    },
    {
      displayName: 'Formatstr',
      name: 'formatstr',
      type: 'string',
      default: '%+',
      description: 'The place format to use. It has three options: 1. Use one of the predefined formats. 2. Use dynamic formatting to create a custom format. 3. Use the special format "%dyncols:" to dynamically add multiple columns to the output CSV using fields from a geocode result.',
    },
    {
      displayName: 'Invalid Result',
      name: 'invalidResult',
      type: 'string',
      default: '',
      description: 'The string to return when the geocode result is empty/invalid. If not set, the original value is used.',
    },
    {
      displayName: 'K_weight',
      name: 'k_weight',
      type: 'number',
      default: 0,
      description: 'Use population-weighted distance for reverse subcommand. (i.e. nearest.distance - k * city.population) Larger values will favor more populated cities. If not set (default), the population is not used and the nearest city is returned.',
    },
    {
      displayName: 'Language',
      name: 'language',
      type: 'string',
      default: 'en',
      description: 'The language to use when geocoding. The language is specified as a ISO 639-1 code. Note that the Geonames index must have been built with the specified language using the `index-update` subcommand with the --languages option. If the language is not available, the first language in the index is used.',
    },
    {
      displayName: 'Languages',
      name: 'languages',
      type: 'string',
      default: 'en',
      description: 'The comma-delimited, case-insensitive list of languages to use when building the Geonames cities index. The languages are specified as a comma-separated list of ISO 639-2 codes. See https://download.geonames.org/export/dump/iso-languagecodes.txt to look up codes and https://download.geonames.org/export/dump/alternatenames/ for the supported language files. 253 languages are currently supported.',
    },
    {
      displayName: 'Min Score',
      name: 'minScore',
      type: 'number',
      default: 0.8,
      description: 'The minimum Jaro-Winkler distance score.',
    },
    {
      displayName: 'New Column',
      name: 'newColumn',
      type: 'string',
      default: '',
      description: 'Put the transformed values in a new column instead. Not valid when using the \'%dyncols:\' --formatstr option.',
    },
    {
      displayName: 'No Annotations',
      name: 'noAnnotations',
      type: 'boolean',
      default: false,
      description: 'Omit OpenCage annotations (timezone, currency, etc.) from the result and from %json output.',
    },
    {
      displayName: 'No Cache',
      name: 'noCache',
      type: 'boolean',
      default: false,
      description: 'Disable the persistent on-disk OpenCage cache. Duplicate queries within a run are still de-duplicated.',
    },
    {
      displayName: 'Older Than',
      name: 'olderThan',
      type: 'string',
      default: '',
      description: 'Delete OpenCage cache entries older than this value. Accepts an absolute date/datetime (e.g. 2025-01-31) or a relative age with a unit suffix (s/m/h/d/w = seconds, minutes, hours, days or weeks; e.g. 30d, 2w, 48h). Required by the cache-prune subcommand.',
    },
    {
      displayName: 'Rate Limit',
      name: 'rateLimit',
      type: 'number',
      default: 1,
      description: 'Maximum number of OpenCage API requests per second. The free tier allows 1 request/second (2,500/day).',
    },
    {
      displayName: 'Rename',
      name: 'rename',
      type: 'string',
      default: '',
      description: 'New name for the transformed column.',
    },
    {
      displayName: 'Reverse',
      name: 'reverse',
      type: 'boolean',
      default: false,
      description: 'Force reverse geocoding for opencage/opencagenow (treat the query as a "lat, long" WGS-84 coordinate). If not set, forward and reverse mode is auto-detected per row.',
    },
    {
      displayName: 'Timeout',
      name: 'timeout',
      type: 'number',
      default: 120,
      description: 'Timeout for downloading Geonames cities index. Also applies to each Geonames source file downloaded when rebuilding the index with index-update - raise it on slow connections.',
    },
    ],
  },
];
