import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv get' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const GetDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Name",
    name: "name",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "Logical cache name (the `dc:` handle) for the fetched",
  },
  {
    displayName: "Ttl",
    name: "ttl",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "Per-entry time-to-live in seconds. -1 = never expire.",
  },
  {
    displayName: "Refresh",
    name: "refresh",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description:
      "Revalidation policy for `dc:` use: on-stale, always or never.",
  },
  {
    displayName: "Compress",
    name: "compress",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "Transparent blob compression: zstd or none.",
  },
  {
    displayName: "Force",
    name: "force",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "Re-fetch even if a fresh cached copy exists.",
  },
  {
    displayName: "Sample",
    name: "sample",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "PREVIEW: stream the first N data records of <source> to",
  },
  {
    displayName: "Offset",
    name: "offset",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "PREVIEW: skip ~<mb> megabytes (via an HTTP Range request)",
  },
  {
    displayName: "Random",
    name: "random",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "PREVIEW: random (reservoir) sampling. Streams the full",
  },
  {
    displayName: "Cloud Opt",
    name: "cloudOpt",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "Extra cloud object-store config as a `key=value` pair",
  },
  {
    displayName: "Ckan Api",
    name: "ckanApi",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "CKAN Action API base URL. Overrides the QSV_CKAN_API",
  },
  {
    displayName: "Ckan Token",
    name: "ckanToken",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "CKAN API token. Overrides the QSV_CKAN_TOKEN env var.",
  },
  {
    displayName: "Timeout",
    name: "timeout",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description:
      "HTTP timeout in seconds. For cache downloads this is an INACTIVITY",
  },
  {
    displayName: "Older Than",
    name: "olderThan",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "For cache-prune: remove entries older than this age.",
  },
  {
    displayName: "Json",
    name: "json",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "For cache-list/cache-info: output JSON instead of a table.",
  },
  {
    displayName: "Verify",
    name: "verify",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "For cache-list: recompute each cached blob's BLAKE3 and",
  },
  {
    displayName: "Cache Dir",
    name: "cacheDir",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "The qsv cache directory. Overrides the QSV_CACHE_DIR",
  },
  {
    displayName: "Quiet",
    name: "quiet",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["get"],
      },
    },
    description: "Do not print progress/summary messages to stderr.",
  },
];
