import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv headers' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const HeadersDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['headers'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['headers'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Just Names',
      name: 'justNames',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['headers'],
        },
      },
      description: 'Only show the header names (hide column index).',
    },
    {
      displayName: 'Just Count',
      name: 'justCount',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['headers'],
        },
      },
      description: 'Only show the number of headers.',
    },
    {
      displayName: 'Union',
      name: 'union',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['headers'],
        },
      },
      description: 'Shows the union of headers across all inputs',
    },
    {
      displayName: 'Trim',
      name: 'trim',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['headers'],
        },
      },
      description: 'Trim leading/trailing space, tab, and quote',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['headers'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
];
