import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv implode' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ImplodeDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Keys",
    name: "keys",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description:
      'Key column(s) to group by. Supports the usual selector syntax (e.g. "name", "1", "1-3", "a,c").',
  },
  {
    displayName: "Value",
    name: "value",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description:
      "The column whose values will be joined per group. Must resolve to exactly one column.",
  },
  {
    displayName: "Rename",
    name: "rename",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description: "New name for the imploded value column.",
  },
  {
    displayName: "Sorted",
    name: "sorted",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description:
      "Assume input is pre-sorted by the key column(s). Streams groups as they are seen; memory is bounded by the size of the largest group.",
  },
  {
    displayName: "Skip Empty",
    name: "skipEmpty",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description:
      "Skip empty values when joining. By default, empty values are included as empty tokens so that round-tripping with `explode` is lossless.",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description: "When set, the first row will not be interpreted as headers.",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["implode"],
      },
    },
    description:
      "The field delimiter for reading CSV data. Must be a single character. (default: ,)",
  },
];
