import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv index' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const IndexDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["index"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output",
    name: "output",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["index"],
      },
    },
    description: "Write index to <file> instead of <input>.idx.",
  },
];
