import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv input' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const InputDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Quote",
    name: "quote",
    type: "string",
    default: '"',
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: 'The quote character to use. [default: "]',
  },
  {
    displayName: "Escape",
    name: "escape",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "The escape character to use. When not specified, quotes are escaped by doubling them.",
  },
  {
    displayName: "No Quoting",
    name: "noQuoting",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "Disable quoting completely when reading CSV data.",
  },
  {
    displayName: "Quote Style",
    name: "quoteStyle",
    type: "string",
    default: "necessary",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "The quoting style to use when writing CSV data. Possible values: all, necessary, nonnumeric and never. All: Quotes all fields. Necessary: Quotes fields only when necessary - when fields contain a quote, delimiter or record terminator. Quotes are also necessary when writing an empty record (which is indistinguishable from a record with one empty field). NonNumeric: Quotes all fields that are non-numeric. Never: Never write quotes. Even if it produces invalid CSV. [default: necessary]",
  },
  {
    displayName: "Skip Lines",
    name: "skipLines",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The number of preamble CSV records to skip.",
  },
  {
    displayName: "Auto Skip",
    name: "autoSkip",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "Sniffs a CSV for preamble records and automatically skips them. Takes precedence over --skip-lines option. Does not work with <stdin>.",
  },
  {
    displayName: "Skip Lastlines",
    name: "skipLastlines",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The number of epilogue CSV records to skip.",
  },
  {
    displayName: "Trim Headers",
    name: "trimHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "Trim leading & trailing whitespace & quotes from header values.",
  },
  {
    displayName: "Trim Fields",
    name: "trimFields",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "Trim leading & trailing whitespace from field values.",
  },
  {
    displayName: "Comment",
    name: "comment",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "The comment character to use (single-byte; only the first byte of the UTF-8 encoding is matched). When set, lines starting with this byte will be skipped.",
  },
  {
    displayName: "Encoding Errors",
    name: "encodingErrors",
    type: "string",
    default: "replace",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      'How to handle UTF-8 encoding errors. Possible values: replace, skip, strict. replace: Replace invalid UTF-8 sequences with �. skip: Fields with encoding errors are "<SKIPPED>". strict: Fail on any encoding errors. [default: replace]',
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "The field delimiter for reading CSV data. Must be a single character. (default: ,)",
  },
];
