import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv input' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const InputDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Quote",
    name: "quote",
    type: "string",
    default: '"',
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: 'The quote character to use. [default: "]',
  },
  {
    displayName: "Escape",
    name: "escape",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The escape character to use. When not specified,",
  },
  {
    displayName: "No Quoting",
    name: "noQuoting",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "Disable quoting completely when reading CSV data.",
  },
  {
    displayName: "Quote Style",
    name: "quoteStyle",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The quoting style to use when writing CSV data.",
  },
  {
    displayName: "Skip Lines",
    name: "skipLines",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The number of preamble CSV records to skip.",
  },
  {
    displayName: "Auto Skip",
    name: "autoSkip",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "Sniffs a CSV for preamble records and automatically",
  },
  {
    displayName: "Skip Lastlines",
    name: "skipLastlines",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The number of epilogue CSV records to skip.",
  },
  {
    displayName: "Trim Headers",
    name: "trimHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description:
      "Trim leading & trailing whitespace & quotes from header values.",
  },
  {
    displayName: "Trim Fields",
    name: "trimFields",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "Trim leading & trailing whitespace from field values.",
  },
  {
    displayName: "Comment",
    name: "comment",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The comment character to use (single-byte; only the",
  },
  {
    displayName: "Encoding Errors",
    name: "encodingErrors",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "How to handle UTF-8 encoding errors.",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["input"],
      },
    },
    description: "The field delimiter for reading CSV data.",
  },
];
