import type { INodeProperties } from "n8n-workflow";

export const JoinpDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    required: true,
    default: "",
    description: "Path to input CSV file on disk or host filesystem",
    displayOptions: {
      show: {
        operation: ["joinp"],
      },
    },
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    description:
      "Optional path to write output file directly to disk (if omitted, results are returned in node output)",
    displayOptions: {
      show: {
        operation: ["joinp"],
      },
    },
  },
  {
    displayName: "Additional Flags",
    name: "additionalArgs",
    type: "string",
    default: "",
    description: "Additional raw command line arguments to pass to qsv joinp",
    displayOptions: {
      show: {
        operation: ["joinp"],
      },
    },
  },
  {
    displayName: "Options",
    name: "options",
    type: "collection",
    placeholder: "Add Option",
    default: {},
    displayOptions: {
      show: {
        operation: ["joinp"],
      },
    },
    options: [
      {
        displayName: "Left",
        name: "left",
        type: "boolean",
        default: false,
        description: "Do a 'left outer' join. This returns all rows in",
      },
      {
        displayName: "Left Anti",
        name: "leftAnti",
        type: "boolean",
        default: false,
        description: "This returns only the rows in the first CSV data set",
      },
      {
        displayName: "Left Semi",
        name: "leftSemi",
        type: "boolean",
        default: false,
        description: "This returns only the rows in the first CSV data set",
      },
      {
        displayName: "Right",
        name: "right",
        type: "boolean",
        default: false,
        description: "Do a 'right outer' join. This returns all rows in",
      },
      {
        displayName: "Right Anti",
        name: "rightAnti",
        type: "boolean",
        default: false,
        description: "This returns only the rows in the second CSV data set",
      },
      {
        displayName: "Right Semi",
        name: "rightSemi",
        type: "boolean",
        default: false,
        description: "This returns only the rows in the second CSV data set",
      },
      {
        displayName: "Full",
        name: "full",
        type: "boolean",
        default: false,
        description: "Do a 'full outer' join. This returns all rows in",
      },
      {
        displayName: "Cross",
        name: "cross",
        type: "boolean",
        default: false,
        description: "USE WITH CAUTION.",
      },
      {
        displayName: "Non Equi",
        name: "nonEqui",
        type: "string",
        default: "",
        description: "Do a non-equi join. The given expression is evaluated",
      },
      {
        displayName: "Coalesce",
        name: "coalesce",
        type: "boolean",
        default: false,
        description: "Force the join to coalesce columns with the same name.",
      },
      {
        displayName: "Filter Left",
        name: "filterLeft",
        type: "string",
        default: "",
        description: "Filter the left CSV data set by the given Polars SQL",
      },
      {
        displayName: "Filter Right",
        name: "filterRight",
        type: "string",
        default: "",
        description: "Filter the right CSV data set by the given Polars SQL",
      },
      {
        displayName: "Validate",
        name: "validate",
        type: "string",
        default: "",
        description: "Validate the join keys BEFORE performing the join.",
      },
      {
        displayName: "Maintain Order",
        name: "maintainOrder",
        type: "string",
        default: "",
        description: "Which row order to preserve, if any. Valid values are:",
      },
      {
        displayName: "Nulls",
        name: "nulls",
        type: "boolean",
        default: false,
        description: "When set, joins will work on empty fields.",
      },
      {
        displayName: "Streaming",
        name: "streaming",
        type: "boolean",
        default: false,
        description: "When set, the join will be done in a streaming fashion.",
      },
      {
        displayName: "Try Parsedates",
        name: "tryParsedates",
        type: "boolean",
        default: false,
        description: "When set, will attempt to parse the columns as dates.",
      },
      {
        displayName: "Infer Len",
        name: "inferLen",
        type: "string",
        default: "",
        description:
          "The number of rows to scan when inferring the schema of the CSV.",
      },
      {
        displayName: "Cache Schema",
        name: "cacheSchema",
        type: "string",
        default: "",
        description: "Create and cache Polars schema JSON files.",
      },
      {
        displayName: "Low Memory",
        name: "lowMemory",
        type: "boolean",
        default: false,
        description:
          "Use low memory mode when parsing CSVs. This will use less memory",
      },
      {
        displayName: "No Optimizations",
        name: "noOptimizations",
        type: "boolean",
        default: false,
        description:
          "Disable non-default join optimizations. This will make joins slower.",
      },
      {
        displayName: "Ignore Errors",
        name: "ignoreErrors",
        type: "boolean",
        default: false,
        description:
          "Ignore errors when parsing CSVs. If set, rows with errors",
      },
      {
        displayName: "Decimal Comma",
        name: "decimalComma",
        type: "boolean",
        default: false,
        description:
          "Use comma as the decimal separator when parsing & writing CSVs.",
      },
      {
        displayName: "Asof",
        name: "asof",
        type: "boolean",
        default: false,
        description: "Do an 'asof' join. This is similar to a left inner",
      },
      {
        displayName: "No Sort",
        name: "noSort",
        type: "boolean",
        default: false,
        description:
          "Do not sort the CSV data sets on the join columns by default.",
      },
      {
        displayName: "Left_by",
        name: "left_by",
        type: "string",
        default: "",
        description:
          "Do an 'asof_by' join - a special implementation of the asof",
      },
      {
        displayName: "Right_by",
        name: "right_by",
        type: "string",
        default: "",
        description: "Do an 'asof_by' join. This specifies the column/s for",
      },
      {
        displayName: "Strategy",
        name: "strategy",
        type: "string",
        default: "",
        description: "The strategy to use for the asof join:",
      },
      {
        displayName: "Tolerance",
        name: "tolerance",
        type: "string",
        default: "",
        description: "The tolerance for the nearest asof join. This is only",
      },
      {
        displayName: "Allow Exact Matches",
        name: "allowExactMatches",
        type: "boolean",
        default: false,
        description: "When set, the asof join will allow exact matches.",
      },
      {
        displayName: "Sql Filter",
        name: "sqlFilter",
        type: "string",
        default: "",
        description: "The SQL expression to apply against the join result.",
      },
      {
        displayName: "Datetime Format",
        name: "datetimeFormat",
        type: "string",
        default: "",
        description: "The datetime format to use writing datetimes.",
      },
      {
        displayName: "Date Format",
        name: "dateFormat",
        type: "string",
        default: "",
        description: "The date format to use writing dates.",
      },
      {
        displayName: "Time Format",
        name: "timeFormat",
        type: "string",
        default: "",
        description: "The time format to use writing times.",
      },
      {
        displayName: "Float Precision",
        name: "floatPrecision",
        type: "string",
        default: "",
        description:
          "The number of digits of precision to use when writing floats.",
      },
      {
        displayName: "Null Value",
        name: "nullValue",
        type: "string",
        default: "",
        description: "The string to use when writing null values.",
      },
      {
        displayName: "Ignore Case",
        name: "ignoreCase",
        type: "boolean",
        default: false,
        description: "When set, joins are done case insensitively.",
      },
      {
        displayName: "Ignore Leading Zeros",
        name: "ignoreLeadingZeros",
        type: "boolean",
        default: false,
        description: "When set, joins are done ignoring leading zeros.",
      },
      {
        displayName: "Norm Unicode",
        name: "normUnicode",
        type: "string",
        default: "",
        description: "When set, join keys are Unicode normalized.",
      },
      {
        displayName: "Delimiter",
        name: "delimiter",
        type: "string",
        default: "",
        description: "The field delimiter for reading/writing CSV data.",
      },
      {
        displayName: "Quiet",
        name: "quiet",
        type: "boolean",
        default: false,
        description: "Do not return join shape to stderr.",
      },
    ],
  },
];
