import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv join' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const JoinDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Left',
      name: 'left',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'Do a \'left outer\' join. This returns all rows in first CSV data set, including rows with no corresponding row in the second data set. When no corresponding row exists, it is padded out with empty fields.',
    },
    {
      displayName: 'Left Anti',
      name: 'leftAnti',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'Do a \'left anti\' join. This returns all rows in first CSV data set that has no match with the second data set.',
    },
    {
      displayName: 'Left Semi',
      name: 'leftSemi',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'Do a \'left semi\' join. This returns all rows in first CSV data set that has a match with the second data set.',
    },
    {
      displayName: 'Right',
      name: 'right',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'Do a \'right outer\' join. This returns all rows in second CSV data set, including rows with no corresponding row in the first data set. When no corresponding row exists, it is padded out with empty fields. (This is the reverse of \'outer left\'.)',
    },
    {
      displayName: 'Right Anti',
      name: 'rightAnti',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'This returns only the rows in the second CSV data set that do not have a corresponding row in the first data set. The output schema is the same as the second dataset.',
    },
    {
      displayName: 'Right Semi',
      name: 'rightSemi',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'This returns only the rows in the second CSV data set that have a corresponding row in the first data set. The output schema is the same as the second data set.',
    },
    {
      displayName: 'Full',
      name: 'full',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'Do a \'full outer\' join. This returns all rows in both data sets with matching records joined. If there is no match, the missing side will be padded out with empty fields. (This is the combination of \'outer left\' and \'outer right\'.)',
    },
    {
      displayName: 'Cross',
      name: 'cross',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'USE WITH CAUTION. This returns the cartesian product of the CSV data sets given. The number of rows return is equal to N * M, where N and M correspond to the number of rows in the given data sets, respectively.',
    },
    {
      displayName: 'Nulls',
      name: 'nulls',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'When set, joins will work on empty fields. Otherwise, empty fields are completely ignored. (In fact, any row that has an empty field in the key specified is ignored.)',
    },
    {
      displayName: 'Keys Output',
      name: 'keysOutput',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'Write successfully joined keys to <file>. This means that the keys are written to the output file when a match is found, with the exception of anti joins, where keys are written when NO match is found. Cross joins do not write keys.',
    },
    {
      displayName: 'Ignore Case',
      name: 'ignoreCase',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'When set, joins are done case insensitively.',
    },
    {
      displayName: 'Ignore Leading Zeros',
      name: 'ignoreLeadingZeros',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'When set, leading zeros are ignored in join keys.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'When set, the first row will not be interpreted as headers. (i.e., They are not searched, analyzed, sliced, etc.)',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['join'],
        },
      },
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
];
