import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv json' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const JsonDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["json"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["json"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Jaq",
    name: "jaq",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["json"],
      },
    },
    description:
      "Filter JSON data using jaq syntax (https://github.com/01mf02/jaq),",
  },
  {
    displayName: "Select",
    name: "select",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["json"],
      },
    },
    description: "Select, reorder or drop columns for output.",
  },
];
