import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv jsonl' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const JsonlDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["jsonl"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["jsonl"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Ignore Errors",
    name: "ignoreErrors",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["jsonl"],
      },
    },
    description: "Skip malformed input lines.",
  },
  {
    displayName: "Jobs",
    name: "jobs",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["jsonl"],
      },
    },
    description: "The number of jobs to run in parallel.",
  },
  {
    displayName: "Batch",
    name: "batch",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["jsonl"],
      },
    },
    description: "The number of rows per batch to load into memory,",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["jsonl"],
      },
    },
    description: "The delimiter to use when writing CSV data.",
  },
];
