import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv moarstats' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const MoarstatsDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Advanced",
    name: "advanced",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Compute Kurtosis, Shannon Entropy, Bimodality Coefficient,",
  },
  {
    displayName: "Epsilon",
    name: "epsilon",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "The Atkinson Index Inequality Aversion parameter.",
  },
  {
    displayName: "Stats Options",
    name: "statsOptions",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Options to pass to the stats command if baseline stats need",
  },
  {
    displayName: "Round",
    name: "round",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Round statistics to <n> decimal places. Rounding follows",
  },
  {
    displayName: "Use Percentiles",
    name: "usePercentiles",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Use percentiles instead of Q1/Q3 for winsorization/trimming.",
  },
  {
    displayName: "Pct Thresholds",
    name: "pctThresholds",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: 'Comma-separated percentile pair (e.g., "10,90") to use',
  },
  {
    displayName: "Xsd Gdate Scan",
    name: "xsdGdateScan",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Gregorian XSD date type detection mode.",
  },
  {
    displayName: "Bivariate",
    name: "bivariate",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Enable bivariate statistics computation.",
  },
  {
    displayName: "Bivariate Stats",
    name: "bivariateStats",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "<stats>",
  },
  {
    displayName: "Cardinality Threshold",
    name: "cardinalityThreshold",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "<n>",
  },
  {
    displayName: "Bivariate Batch",
    name: "bivariateBatch",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Process at most <n> field pairs per pass over the input,",
  },
  {
    displayName: "Join Inputs",
    name: "joinInputs",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "<files>",
  },
  {
    displayName: "Join Keys",
    name: "joinKeys",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "<keys>",
  },
  {
    displayName: "Join Type",
    name: "joinType",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "<type>",
  },
  {
    displayName: "Progressbar",
    name: "progressbar",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Show progress bars when computing bivariate statistics.",
  },
  {
    displayName: "Force",
    name: "force",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "Force recomputing stats even if valid precomputed stats",
  },
  {
    displayName: "Jobs",
    name: "jobs",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["moarstats"],
      },
    },
    description: "The number of jobs to run in parallel.",
  },
];
