import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv partition' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const PartitionDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['partition'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['partition'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Filename',
      name: 'filename',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['partition'],
        },
      },
      description: 'A filename template to use when constructing the',
    },
    {
      displayName: 'Prefix Length',
      name: 'prefixLength',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['partition'],
        },
      },
      description: 'Truncate the partition column after the',
    },
    {
      displayName: 'Drop',
      name: 'drop',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['partition'],
        },
      },
      description: 'Drop the partition column from results.',
    },
    {
      displayName: 'Limit',
      name: 'limit',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['partition'],
        },
      },
      description: 'Limit the number of simultaneously open files.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['partition'],
        },
      },
      description: 'When set, the first row will NOT be interpreted',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['partition'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
];
