import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv pragmastat' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const PragmastatDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Twosample",
    name: "twosample",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Compute two-sample estimators for all column pairs.",
  },
  {
    displayName: "Compare1",
    name: "compare1",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "One-sample confirmatory analysis. Test center/spread against",
  },
  {
    displayName: "Compare2",
    name: "compare2",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Two-sample confirmatory analysis. Test shift/ratio/disparity",
  },
  {
    displayName: "Select",
    name: "select",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Select columns for analysis. Uses qsv's column selection",
  },
  {
    displayName: "Misrate",
    name: "misrate",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Probability that bounds fail to contain the true parameter.",
  },
  {
    displayName: "Standalone",
    name: "standalone",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Output one-sample results as standalone CSV instead of",
  },
  {
    displayName: "Stats Options",
    name: "statsOptions",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Options to pass to the stats command if baseline stats need",
  },
  {
    displayName: "Round",
    name: "round",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Round statistics to <n> decimal places. Rounding follows",
  },
  {
    displayName: "Force",
    name: "force",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Force recomputing ps_* columns even if they already exist",
  },
  {
    displayName: "Subsample",
    name: "subsample",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Randomly subsample N values per column before computing.",
  },
  {
    displayName: "Seed",
    name: "seed",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Seed for reproducible subsampling.",
  },
  {
    displayName: "No Bounds",
    name: "noBounds",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Skip confidence bounds computation (~2x faster).",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "The field delimiter for reading/writing CSV data.",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "When set, the first row will not be treated as headers.",
  },
  {
    displayName: "Jobs",
    name: "jobs",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "The number of jobs to run in parallel.",
  },
  {
    displayName: "Memcheck",
    name: "memcheck",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["pragmastat"],
      },
    },
    description: "Check if there is enough memory to load the entire",
  },
];
