import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv prompt' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const PromptDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Msg',
      name: 'msg',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'The prompt message to display in the file dialog title.',
    },
    {
      displayName: 'Filters',
      name: 'filters',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'The filter to use for the INPUT file dialog. Set to "None" to',
    },
    {
      displayName: 'Workdir',
      name: 'workdir',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'The directory to start the file dialog in.',
    },
    {
      displayName: 'Fd Output',
      name: 'fdOutput',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'Write output to a file by using a save file dialog.',
    },
    {
      displayName: 'Save Fname',
      name: 'saveFname',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'The filename to save the output as when using --fd-output.',
    },
    {
      displayName: 'Base Delay Ms',
      name: 'baseDelayMs',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'The base delay in milliseconds to use when opening INPUT dialog.',
    },
    {
      displayName: 'Quiet',
      name: 'quiet',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['prompt'],
        },
      },
      description: 'Do not print --fd-output message to stderr.',
    },
];
