import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv prompt' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const PromptDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Msg",
    name: "msg",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description:
      'The prompt message to display in the file dialog title. When not using --fd-output, the default is "Select a File". When using --fd-output, the default is "Save File As".',
  },
  {
    displayName: "Filters",
    name: "filters",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description:
      'The filter to use for the INPUT file dialog. Set to "None" to disable filters. Filters are comma-delimited file extensions. Defaults to csv,tsv,tab,ssv,xls,xlsx,xlsm,xlsb,ods. If the polars feature is enabled, it adds avro,arrow,ipc,parquet, json,jsonl,ndjson & gz,zst,zlib compressed files to the filter.',
  },
  {
    displayName: "Workdir",
    name: "workdir",
    type: "string",
    default: ".",
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description: "The directory to start the file dialog in. [default: .]",
  },
  {
    displayName: "Fd Output",
    name: "fdOutput",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description:
      "Write output to a file by using a save file dialog. Used when piping into qsv prompt. Mutually exclusive with --output.",
  },
  {
    displayName: "Save Fname",
    name: "saveFname",
    type: "string",
    default: "output.csv",
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description:
      "The filename to save the output as when using --fd-output. [default: output.csv]",
  },
  {
    displayName: "Base Delay Ms",
    name: "baseDelayMs",
    type: "string",
    default: "200",
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description:
      "The base delay in milliseconds to use when opening INPUT dialog. This is to ensure that the INPUT dialog is shown before/over the OUTPUT dialog when using the prompt command is used in both INPUT and OUTPUT modes in a single pipeline. [default: 200]",
  },
  {
    displayName: "Quiet",
    name: "quiet",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["prompt"],
      },
    },
    description: "Do not print --fd-output message to stderr.",
  },
];
