import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv pseudo' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const PseudoDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["pseudo"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pseudo"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Start",
    name: "start",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pseudo"],
      },
    },
    description: "The starting number for the incremental identifier.",
  },
  {
    displayName: "Increment",
    name: "increment",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pseudo"],
      },
    },
    description: "The increment for the incremental identifier.",
  },
  {
    displayName: "Formatstr",
    name: "formatstr",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pseudo"],
      },
    },
    description: "The format string for the incremental identifier.",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["pseudo"],
      },
    },
    description: "When set, the first row will not be interpreted",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["pseudo"],
      },
    },
    description: "The field delimiter for reading CSV data.",
  },
];
