import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv reverse' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ReverseDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['reverse'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['reverse'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['reverse'],
        },
      },
      description: 'When set, the first row will not be interpreted',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['reverse'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
    {
      displayName: 'Memcheck',
      name: 'memcheck',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['reverse'],
        },
      },
      description: 'Check if there is enough memory to load the entire',
    },
];
