import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv safenames' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const SafenamesDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["safenames"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["safenames"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Mode",
    name: "mode",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["safenames"],
      },
    },
    description:
      'Rename header names to "safe" names — guaranteed "database-ready" names. Mode is selected by the FIRST character: c/C conditional, a/A always, s safer, S Safer (unicode), v verify, V Verbose, j JSON, J pretty JSON (case matters for s vs S, v vs V and j vs J; --mode verbose maps to \'v\', NOT V).',
  },
  {
    displayName: "Reserved",
    name: "reserved",
    type: "string",
    default: "_id",
    displayOptions: {
      show: {
        operation: ["safenames"],
      },
    },
    description:
      'Comma-delimited list of additional case-insensitive reserved names that should be considered "unsafe." If a header name is found in the reserved list, it will be prefixed with "reserved_". [default: _id]',
  },
  {
    displayName: "Prefix",
    name: "prefix",
    type: "string",
    default: "unsafe_",
    displayOptions: {
      show: {
        operation: ["safenames"],
      },
    },
    description:
      'Certain systems do not allow header names to start with "_" (e.g. CKAN Datastore). This option allows the specification of the unsafe prefix to use when a header starts with "_". [default: unsafe_]',
  },
  {
    displayName: "Collapse",
    name: "collapse",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["safenames"],
      },
    },
    description:
      "Collapse consecutive runs of non-alphanumeric characters into a single _. Composes with ALL modes (including verify & JSON modes). Implied by --mode s and --mode S.",
  },
  {
    displayName: "Unicode",
    name: "unicode",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["safenames"],
      },
    },
    description:
      "Preserve unicode letters & numbers instead of stripping to ASCII. Composes with ALL modes (including verify & JSON modes). Implied by --mode S.",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["safenames"],
      },
    },
    description:
      "The field delimiter for reading CSV data. Must be a single character. (default: ,)",
  },
];
