import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv select' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const SelectDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['select'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['select'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Random',
      name: 'random',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['select'],
        },
      },
      description: 'Randomly shuffle the columns in the selection.',
    },
    {
      displayName: 'Seed',
      name: 'seed',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['select'],
        },
      },
      description: 'Seed for the random number generator.',
    },
    {
      displayName: 'Sort',
      name: 'sort',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['select'],
        },
      },
      description: 'Sort the selected columns lexicographically,',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['select'],
        },
      },
      description: 'When set, the first row will not be interpreted',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['select'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
];
