import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv slice' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const SliceDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Start',
      name: 'start',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'The index of the record to slice from. If negative, starts from the last record.',
    },
    {
      displayName: 'End',
      name: 'end',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'The index of the record to slice to.',
    },
    {
      displayName: 'Len',
      name: 'len',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'The length of the slice (can be used instead of --end).',
    },
    {
      displayName: 'Index',
      name: 'index',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'Slice a single record (shortcut for -s N -l 1). If negative, starts from the last record.',
    },
    {
      displayName: 'Json',
      name: 'json',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'Output the result as JSON. Fields are written as key-value pairs. The key is the column name. The value is the field value. The output is a JSON array. If --no-headers is set, then the keys are the column indices (zero-based).',
    },
    {
      displayName: 'Invert',
      name: 'invert',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'slice all records EXCEPT those in the specified range.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'When set, the first row will not be interpreted as headers. Otherwise, the first row will always appear in the output as the header row.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['slice'],
        },
      },
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
];
