import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv snappy' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const SnappyDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['snappy'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['snappy'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'User Agent',
      name: 'userAgent',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['snappy'],
        },
      },
      description: 'Specify custom user agent to use when the input is a URL.',
    },
    {
      displayName: 'Timeout',
      name: 'timeout',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['snappy'],
        },
      },
      description: 'Timeout for downloading URLs in seconds.',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['snappy'],
        },
      },
      description: 'The number of jobs to run in parallel when compressing.',
    },
    {
      displayName: 'Quiet',
      name: 'quiet',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['snappy'],
        },
      },
      description: 'Suppress status messages to stderr.',
    },
    {
      displayName: 'Progressbar',
      name: 'progressbar',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['snappy'],
        },
      },
      description: 'Show download progress bars. Only valid for URL input.',
    },
];
