import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv sniff' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const SniffDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Sample",
    name: "sample",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "First n rows to sample to sniff out the metadata.",
  },
  {
    displayName: "Prefer Dmy",
    name: "preferDmy",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description:
      "Prefer to parse dates in dmy format. Otherwise, use mdy format.",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "The delimiter for reading CSV data.",
  },
  {
    displayName: "Quote",
    name: "quote",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "The quote character for reading CSV data.",
  },
  {
    displayName: "Json",
    name: "json",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "Return results in JSON format.",
  },
  {
    displayName: "Pretty Json",
    name: "prettyJson",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "Return results in pretty JSON format.",
  },
  {
    displayName: "Save Urlsample",
    name: "saveUrlsample",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "Save the URL sample to a file.",
  },
  {
    displayName: "Timeout",
    name: "timeout",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description:
      "Timeout when sniffing URLs in seconds. If 0, no timeout is used.",
  },
  {
    displayName: "User Agent",
    name: "userAgent",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description:
      "Specify custom user agent to use when sniffing a CSV on a URL.",
  },
  {
    displayName: "Stats Types",
    name: "statsTypes",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "Use the same data type names as `stats`.",
  },
  {
    displayName: "No Infer",
    name: "noInfer",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description:
      "Do not infer the schema. Only return the file's mime type, size and",
  },
  {
    displayName: "Just Mime",
    name: "justMime",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description:
      "Only return the file's mime type. Use this to use sniff as a general",
  },
  {
    displayName: "Quick",
    name: "quick",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description:
      "When sniffing a non-CSV remote file, only download the first chunk of the file",
  },
  {
    displayName: "Harvest Mode",
    name: "harvestMode",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description:
      "This is a convenience flag when using sniff in CKAN harvesters.",
  },
  {
    displayName: "Progressbar",
    name: "progressbar",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["sniff"],
      },
    },
    description: "Show progress bars. Only valid for URL input.",
  },
];
