import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv split' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const SplitDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Size",
    name: "size",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "The number of records to write into each chunk.",
  },
  {
    displayName: "Chunks",
    name: "chunks",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "The number of chunks to split the data into.",
  },
  {
    displayName: "Kb Size",
    name: "kbSize",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "The size of each chunk in kilobytes. The number of rows",
  },
  {
    displayName: "Jobs",
    name: "jobs",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "The number of splitting jobs to run in parallel.",
  },
  {
    displayName: "Filename",
    name: "filename",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "A filename template to use when constructing",
  },
  {
    displayName: "Pad",
    name: "pad",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "The zero padding width that is used in the",
  },
  {
    displayName: "Filter",
    name: "filter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "Run the specified command on each chunk after it is written.",
  },
  {
    displayName: "Filter Cleanup",
    name: "filterCleanup",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description:
      "Cleanup the original output filename AFTER the filter command",
  },
  {
    displayName: "Filter Ignore Errors",
    name: "filterIgnoreErrors",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "Ignore errors when running the filter command.",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "When set, the first row will NOT be interpreted",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "The field delimiter for reading CSV data.",
  },
  {
    displayName: "Quiet",
    name: "quiet",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["split"],
      },
    },
    description: "Do not display an output summary to stderr.",
  },
];
