import type { INodeProperties } from 'n8n-workflow';

export const SqlpDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['sqlp'],
      },
    },
  },
  {
    displayName: 'SQL Query',
    name: 'sql',
    type: 'string',
    required: true,
    default: '',
    description: 'The SQL query/ies to run. Each input file will be available as a table named after the file name (without the extension), or as "_t_N" where N is the 1-based index. If the query ends with ".sql", it will be read as a SQL script file, with each SQL query separated by a semicolon. It will execute the queries in order, and the result of the LAST query will be returned as the result. SQL scripts support single-line comments starting with \'--\'.',
    displayOptions: {
      show: {
        operation: ['sqlp'],
      },
    },
  },
  {
    displayName: 'Output File Path',
    name: 'outputPath',
    type: 'string',
    default: '',
    description: 'Optional path to write output file directly to disk (if omitted, results are returned in node output)',
    displayOptions: {
      show: {
        operation: ['sqlp'],
      },
    },
  },
  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv sqlp [⚡ Runs faster when CSV index (.qsv.idx) is present.] (Docs: https://github.com/dathere/qsv/blob/master/docs/help/sqlp.md)',
    displayOptions: {
      show: {
        operation: ['sqlp'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['sqlp'],
      },
    },
    options: [
    {
      displayName: 'Cache Schema',
      name: 'cacheSchema',
      type: 'boolean',
      default: false,
      description: 'Create and cache Polars schema JSON files. If the schema file/s exists, it will load the schema instead of inferring it (ignoring --infer-len) and attempt to use it for each corresponding Polars "table" with the same file stem. If specified and the schema file/s do not exist, it will check if a stats cache is available. If so, it will use it to derive a Polars schema and save it. If there\'s no stats cache, it will infer the schema using --infer-len and save the inferred schemas. Date columns in formats Polars can\'t parse are saved as String, as are day-first dates unless QSV_PREFER_DMY is set. Each schema file will have the same file stem as the corresponding input file, with the extension ".pschema.json" (data.csv\'s Polars schema file will be data.pschema.json) NOTE: You can edit the generated schema files to change the Polars schema and cast columns to the desired data type. Float columns are saved as Float64. For example, to save memory you can narrow a Float64 column to Float32 by changing its "Float64" type to "Float32" in the schema file, at the cost of precision (Float32 holds only about 7 significant digits). You can also cast a Float to a Decimal with a desired precision and scale. (e.g. instead of "Float64", use {"Decimal": [10, 3]}) The valid types are: `Boolean`, `UInt8`, `UInt16`, `UInt32`, `UInt64`, `Int8`, `Int16`, `Int32`, `Int64`, `Float32`, `Float64`, `String`, `Date`, `Datetime`, `Duration`, `Time`, `Null`, `Categorical`, `Decimal` and `Enum`.',
    },
    {
      displayName: 'Compress Level',
      name: 'compressLevel',
      type: 'number',
      default: 0,
      description: 'The compression level to use when using zstd or gzip compression. When using zstd, valid values are -7 to 22, with -7 being the lowest compression level and 22 being the highest compression level. When using gzip, valid values are 1-9, with 1 being the lowest compression level and 9 being the highest compression level. Higher compression levels are slower. The zstd default is 3, and the gzip default is 6.',
    },
    {
      displayName: 'Compression',
      name: 'compression',
      type: 'string',
      default: 'zstd',
      description: 'The compression codec to use when writing arrow, avro or parquet files. The `zstd` default below applies to Arrow and Parquet. Avro does not support zstd, so when `--compression` is omitted Avro silently falls back to uncompressed unless you pass an Avro-supported codec. For Arrow, valid values are: `zstd`, `lz4`, `uncompressed`. For Avro, valid values are: `deflate`, `snappy`, `uncompressed`. For Parquet, valid values are: `zstd`, `lz4raw`, `gzip`, `snappy`, `uncompressed`.',
    },
    {
      displayName: 'Date Format',
      name: 'dateFormat',
      type: 'string',
      default: '',
      description: 'The date format to use writing dates.',
    },
    {
      displayName: 'Datetime Format',
      name: 'datetimeFormat',
      type: 'string',
      default: '',
      description: 'The datetime format to use writing datetimes. See https://docs.rs/chrono/latest/chrono/format/strftime/index.html for the list of valid format specifiers.',
    },
    {
      displayName: 'Decimal Comma',
      name: 'decimalComma',
      type: 'boolean',
      default: false,
      description: 'Use comma as the decimal separator when parsing & writing CSVs. Otherwise, use period as the decimal separator. Note that you\'ll need to set --delimiter to an alternate delimiter other than the default comma if you are using this option.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: ',',
      description: 'The field delimiter for reading and writing CSV data. Must be a single character.',
    },
    {
      displayName: 'Float Precision',
      name: 'floatPrecision',
      type: 'number',
      default: 0,
      description: 'The number of digits of precision to use when writing floats.',
    },
    {
      displayName: 'Format',
      name: 'format',
      type: 'string',
      default: 'csv',
      description: 'The output format to use. Valid values are: csv, json, jsonl, parquet, arrow, avro',
    },
    {
      displayName: 'Ignore Errors',
      name: 'ignoreErrors',
      type: 'boolean',
      default: false,
      description: 'Ignore errors when parsing CSVs. If set, rows with errors will be skipped. If not set, the query will fail. Only use this when debugging queries, as Polars does batched parsing and will skip the entire batch where the error occurred. To get more detailed error messages, set the environment variable POLARS_BACKTRACE_IN_ERR=1 before running the query.',
    },
    {
      displayName: 'Infer Len',
      name: 'inferLen',
      type: 'number',
      default: 10000,
      description: 'The number of rows to scan when inferring the schema of the CSV. Set to 0 to do a full table scan (warning: can be slow).',
    },
    {
      displayName: 'Low Memory',
      name: 'lowMemory',
      type: 'boolean',
      default: false,
      description: 'Use low memory mode when parsing CSVs. This will use less memory but will be slower. Only use this when you get out of memory errors.',
    },
    {
      displayName: 'No Optimizations',
      name: 'noOptimizations',
      type: 'boolean',
      default: false,
      description: 'Disable non-default query optimizations. This will make queries slower. Use this when you get query errors or to force CSV parsing when there is only one input file, no CSV parsing options are used and its not a SQL script.',
    },
    {
      displayName: 'Rnull Values',
      name: 'rnullValues',
      type: 'string',
      default: '<empty string>',
      description: 'The comma-delimited list of case-sensitive strings to consider as null values when READING CSV files (e.g. NULL, NONE, <empty string>). Use "<empty string>" to consider an empty string a null value.',
    },
    {
      displayName: 'Statistics',
      name: 'statistics',
      type: 'boolean',
      default: false,
      description: 'Compute column statistics when writing parquet files.',
    },
    {
      displayName: 'Streaming',
      name: 'streaming',
      type: 'boolean',
      default: false,
      description: 'Use streaming mode when parsing CSVs. This will use less memory but will be slower. Only use this when you get out of memory errors.',
    },
    {
      displayName: 'Time Format',
      name: 'timeFormat',
      type: 'string',
      default: '',
      description: 'The time format to use writing times.',
    },
    {
      displayName: 'Truncate Ragged Lines',
      name: 'truncateRaggedLines',
      type: 'boolean',
      default: false,
      description: 'Truncate ragged lines when parsing CSVs. If set, rows with more columns than the header will be truncated. If not set, the query will fail. Use this only when you get an error about ragged lines.',
    },
    {
      displayName: 'Try Parsedates',
      name: 'tryParsedates',
      type: 'boolean',
      default: false,
      description: 'Automatically try to parse dates/datetimes and time. If parsing fails, columns remain as strings. Note that if dates are not well-formatted in your CSV, that you may want to try to set `--ignore-errors` to relax the CSV parsing of dates.',
    },
    {
      displayName: 'Wnull Value',
      name: 'wnullValue',
      type: 'string',
      default: '<empty string>',
      description: 'The string to use when WRITING null values.',
    },
    ],
  },
];
