import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv sqlp' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const SqlpDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Format',
      name: 'format',
      type: 'string',
      default: 'csv',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The output format to use. Valid values are: csv, json, jsonl, parquet, arrow, avro [default: csv]',
    },
    {
      displayName: 'Try Parsedates',
      name: 'tryParsedates',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Automatically try to parse dates/datetimes and time. If parsing fails, columns remain as strings. Note that if dates are not well-formatted in your CSV, that you may want to try to set `--ignore-errors` to relax the CSV parsing of dates.',
    },
    {
      displayName: 'Infer Len',
      name: 'inferLen',
      type: 'string',
      default: '10000',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The number of rows to scan when inferring the schema of the CSV. Set to 0 to do a full table scan (warning: can be slow). [default: 10000]',
    },
    {
      displayName: 'Cache Schema',
      name: 'cacheSchema',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Create and cache Polars schema JSON files. If the schema file/s exists, it will load the schema instead of inferring it (ignoring --infer-len) and attempt to use it for each corresponding Polars "table" with the same file stem. If specified and the schema file/s do not exist, it will check if a stats cache is available. If so, it will use it to derive a Polars schema and save it. If there\'s no stats cache, it will infer the schema using --infer-len and save the inferred schemas. Each schema file will have the same file stem as the corresponding input file, with the extension ".pschema.json" (data.csv\'s Polars schema file will be data.pschema.json) NOTE: You can edit the generated schema files to change the Polars schema and cast columns to the desired data type. For example, you can force a Float32 column to be a Float64 column by changing the "Float32" type to "Float64" in the schema file. You can also cast a Float to a Decimal with a desired precision and scale. (e.g. instead of "Float32", use "{Decimal" : [10, 3]}") The valid types are: `Boolean`, `UInt8`, `UInt16`, `UInt32`, `UInt64`, `Int8`, `Int16`, `Int32`, `Int64`, `Float32`, `Float64`, `String`, `Date`, `Datetime`, `Duration`, `Time`, `Null`, `Categorical`, `Decimal` and `Enum`.',
    },
    {
      displayName: 'Streaming',
      name: 'streaming',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Use streaming mode when parsing CSVs. This will use less memory but will be slower. Only use this when you get out of memory errors.',
    },
    {
      displayName: 'Low Memory',
      name: 'lowMemory',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Use low memory mode when parsing CSVs. This will use less memory but will be slower. Only use this when you get out of memory errors.',
    },
    {
      displayName: 'No Optimizations',
      name: 'noOptimizations',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Disable non-default query optimizations. This will make queries slower. Use this when you get query errors or to force CSV parsing when there is only one input file, no CSV parsing options are used and its not a SQL script.',
    },
    {
      displayName: 'Truncate Ragged Lines',
      name: 'truncateRaggedLines',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Truncate ragged lines when parsing CSVs. If set, rows with more columns than the header will be truncated. If not set, the query will fail. Use this only when you get an error about ragged lines.',
    },
    {
      displayName: 'Ignore Errors',
      name: 'ignoreErrors',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Ignore errors when parsing CSVs. If set, rows with errors will be skipped. If not set, the query will fail. Only use this when debugging queries, as Polars does batched parsing and will skip the entire batch where the error occurred. To get more detailed error messages, set the environment variable POLARS_BACKTRACE_IN_ERR=1 before running the query.',
    },
    {
      displayName: 'Rnull Values',
      name: 'rnullValues',
      type: 'string',
      default: '<empty string>',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The comma-delimited list of case-sensitive strings to consider as null values when READING CSV files (e.g. NULL, NONE, <empty string>). Use "<empty string>" to consider an empty string a null value. [default: <empty string>]',
    },
    {
      displayName: 'Decimal Comma',
      name: 'decimalComma',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Use comma as the decimal separator when parsing & writing CSVs. Otherwise, use period as the decimal separator. Note that you\'ll need to set --delimiter to an alternate delimiter other than the default comma if you are using this option.',
    },
    {
      displayName: 'Datetime Format',
      name: 'datetimeFormat',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The datetime format to use writing datetimes. See https://docs.rs/chrono/latest/chrono/format/strftime/index.html for the list of valid format specifiers.',
    },
    {
      displayName: 'Date Format',
      name: 'dateFormat',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The date format to use writing dates.',
    },
    {
      displayName: 'Time Format',
      name: 'timeFormat',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The time format to use writing times.',
    },
    {
      displayName: 'Float Precision',
      name: 'floatPrecision',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The number of digits of precision to use when writing floats.',
    },
    {
      displayName: 'Wnull Value',
      name: 'wnullValue',
      type: 'string',
      default: '<empty string>',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The string to use when WRITING null values. [default: <empty string>]',
    },
    {
      displayName: 'Compression',
      name: 'compression',
      type: 'string',
      default: 'zstd',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The compression codec to use when writing arrow, avro or parquet files. The `zstd` default below applies to Arrow and Parquet. Avro does not support zstd, so when `--compression` is omitted Avro silently falls back to uncompressed unless you pass an Avro-supported codec. For Arrow, valid values are: `zstd`, `lz4`, `uncompressed`. For Avro, valid values are: `deflate`, `snappy`, `uncompressed`. For Parquet, valid values are: `zstd`, `lz4raw`, `gzip`, `snappy`, `uncompressed`. [default: zstd]',
    },
    {
      displayName: 'Compress Level',
      name: 'compressLevel',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The compression level to use when using zstd or gzip compression. When using zstd, valid values are -7 to 22, with -7 being the lowest compression level and 22 being the highest compression level. When using gzip, valid values are 1-9, with 1 being the lowest compression level and 9 being the highest compression level. Higher compression levels are slower. The zstd default is 3, and the gzip default is 6.',
    },
    {
      displayName: 'Statistics',
      name: 'statistics',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Compute column statistics when writing parquet files.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'The field delimiter for reading and writing CSV data.',
    },
    {
      displayName: 'Quiet',
      name: 'quiet',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['sqlp'],
        },
      },
      description: 'Do not return result shape to stderr.',
    },
];
