import type { INodeProperties } from 'n8n-workflow';

export const StatsDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['stats'],
      },
    },
  },

  {
    displayName: 'Output File Path',
    name: 'outputPath',
    type: 'string',
    default: '',
    description: 'Optional path to write output file directly to disk (if omitted, results are returned in node output)',
    displayOptions: {
      show: {
        operation: ['stats'],
      },
    },
  },
  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv stats (Docs: https://github.com/dathere/qsv/blob/master/docs/help/stats.md)',
    displayOptions: {
      show: {
        operation: ['stats'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['stats'],
      },
    },
    options: [
    {
      displayName: 'Boolean Patterns',
      name: 'booleanPatterns',
      type: 'string',
      default: '',
      description: 'Comma-separated list of boolean pattern pairs in the format "true_pattern:false_pattern". Each pattern can be a string of any length. The patterns are case-insensitive. If a pattern ends with a "*", it is treated as a prefix. For example, "t*:f*,y*:n*" will match "true", "truthy", "Truth" as boolean true values so long as the corresponding false pattern (e.g. False, f, etc.) is also matched & cardinality is 2. Ignored if --infer-boolean is false. [default: 1:0,t*:f*,y*:n*]',
    },
    {
      displayName: 'Cache Threshold',
      name: 'cacheThreshold',
      type: 'string',
      default: '',
      description: 'Controls the creation of stats cache files. * when greater than 1, the threshold in milliseconds before caching stats results. If a stats run takes longer than this threshold, the stats results will be cached. * 0 to suppress caching. * 1 to force caching. * a negative number to automatically create an index when the input file size is greater than abs(arg) in bytes. If the negative number ends with 5, it will delete the index file and the stats cache file after the stats run. Otherwise, the index file and the cache files are kept. [default: 5000]',
    },
    {
      displayName: 'Cardinality',
      name: 'cardinality',
      type: 'boolean',
      default: false,
      description: 'Compute the cardinality and the uniqueness ratio. This is automatically enabled if --infer-boolean is enabled. https://en.wikipedia.org/wiki/Cardinality_(SQL_statements) Uses memory proportional to the number of unique values in each column.',
    },
    {
      displayName: 'Cardinality Method',
      name: 'cardinalityMethod',
      type: 'string',
      default: '',
      description: 'Algorithm used to compute the --cardinality column. Choices: exact  - track every unique value in a frequency map (current behavior). O(cardinality) memory per column. Subject to --mode-cardinality-cap, which emits the ">=<n>" sentinel on overflow. approx - use HyperLogLog (Apache DataSketches port, lg_k=12). O(1) memory per column (~5KB), ~1.5% relative standard error. Notes: * --mode-cardinality-cap no longer affects the cardinality column under approx; the ">=<n>" sentinel is never emitted. * The cap STILL governs mode/antimode tracking (mode columns still emit "*HIGH_CARDINALITY" on overflow). * --infer-boolean forces exact (boolean inference needs cardinality == 2 exactness); a one-time warning is emitted. * Reproducible across --jobs values: the HLL union used at merge time is associative and order-invariant, so chunk completion order does not affect the final estimate. * Requires a little-endian target. Apache DataSketches does not support big-endian platforms (e.g., s390x); on those builds, this choice is rejected. [default: exact]',
    },
    {
      displayName: 'Dates Whitelist',
      name: 'datesWhitelist',
      type: 'string',
      default: '',
      description: 'The comma-separated, case-insensitive patterns to look for when shortlisting fields for date inferencing. i.e. if the field\'s name has any of these patterns, it is shortlisted for date inferencing. Special values: * "all" - inspect ALL fields for date/datetime types * "sniff" - use `qsv sniff` to auto-detect date/datetime columns Note that false positive date matches WILL most likely occur when using "all" as unix epoch timestamps are just numbers. Be sure to only use "all" if you know ALL the columns you\'re inspecting are dates, boolean or string fields. To avoid false positives, preprocess the file first with the `datefmt` command to convert unix epoch timestamp columns to RFC3339 format. When set to "sniff", we do two-stage date inferencing. First running sniff on the input file and then second, only inferring dates for the columns that sniff identifies as date/datetime candidates. This is much faster than "all", and more convenient than manually specifying patterns in the whitelist. [default: sniff]',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      description: 'The field delimiter for READING CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Everything',
      name: 'everything',
      type: 'boolean',
      default: false,
      description: 'Compute all statistics available.',
    },
    {
      displayName: 'Force',
      name: 'force',
      type: 'boolean',
      default: false,
      description: 'Force recomputing stats even if valid precomputed stats cache exists.',
    },
    {
      displayName: 'Infer Boolean',
      name: 'inferBoolean',
      type: 'boolean',
      default: false,
      description: 'Infer boolean data type. This automatically enables the --cardinality option. When a column\'s cardinality is 2, and the 2 values\' are in the true/false patterns specified by --boolean-patterns, the data type is inferred as boolean.',
    },
    {
      displayName: 'Infer Dates',
      name: 'inferDates',
      type: 'boolean',
      default: false,
      description: 'Infer date/datetime data types. This is an expensive option and should only be used when you know there are date/datetime fields. Also, if timezone is not specified in the data, it\'ll be set to UTC.',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      description: 'The number of jobs to run in parallel. This works only when the given CSV has an index. Note that a file handle is opened for each job. When not set, the number of jobs is set to the number of CPUs detected.',
    },
    {
      displayName: 'Jsonl',
      name: 'jsonl',
      type: 'boolean',
      default: false,
      description: 'Emit the stats to stdout as JSON Lines (NDJSON) - one JSON object per column - instead of CSV. This is the same per-column shape the --stats-jsonl sidecar file uses, but streamed to stdout. Respects --output (the NDJSON is written to the file instead). Cannot be combined with --stats-jsonl or --pretty-json.',
    },
    {
      displayName: 'Mad',
      name: 'mad',
      type: 'boolean',
      default: false,
      description: 'Compute the median absolute deviation (MAD). https://en.wikipedia.org/wiki/Median_absolute_deviation',
    },
    {
      displayName: 'Median',
      name: 'median',
      type: 'boolean',
      default: false,
      description: 'Compute the median. Loads & sorts all the selected columns\' data in memory. https://en.wikipedia.org/wiki/Median',
    },
    {
      displayName: 'Memcheck',
      name: 'memcheck',
      type: 'boolean',
      default: false,
      description: 'Use CONSERVATIVE heuristics for the in-memory load check (file size vs. available + free_swap × platform factor − headroom), instead of the default NORMAL check (file size vs. total memory − headroom). The CONSERVATIVE check is stricter and trips OOM far more readily. Ignored when computing default, streaming statistics. (See also: QSV_MEMORY_CHECK env var, equivalent to passing --memcheck.) Independently of this flag, the in-memory load check runs whenever stats takes the non-parallel path with non-streaming columns. On OOM (in either NORMAL or CONSERVATIVE mode), qsv auto-creates an index when no index exists (skipped for stdin) AND switches to approx quantile + approx cardinality methods (DataSketches t-digest and HyperLogLog) where compatible. The sketch fallback can also fire when an index is already present and the OOM still trips (e.g., when jobs is pinned to 1 on a pre-indexed file). A wwarn is emitted listing the auto-enabled estimators.',
    },
    {
      displayName: 'Mode',
      name: 'mode',
      type: 'boolean',
      default: false,
      description: 'Compute the mode/s & antimode/s. Multimodal-aware. If there are multiple modes/antimodes, they are separated by the QSV_STATS_SEPARATOR environment variable. If not set, the default separator is "|". Uses memory proportional to the cardinality of each column.',
    },
    {
      displayName: 'Mode Cardinality Cap',
      name: 'modeCardinalityCap',
      type: 'string',
      default: '',
      description: 'Bound mode-tracking memory on high-cardinality columns. When > 0, if a column\'s mode tracker grows past <n> UNIQUE values (true cardinality, for both unweighted and weighted runs), qsv drops it and emits sentinel values instead of exact modes and cardinality. The cap is a direct memory bound on the tracker, which stores one entry per unique value. Sentinel output: * mode columns: "*HIGH_CARDINALITY" * cardinality column: ">=<n>" (the ">=" prefix DOES break downstream parsers expecting a plain integer; cap is opt-in only). Under --cardinality-method approx, the cardinality column ignores this cap (HLL gives an approximate estimate at fixed memory, ~1.5% RSE) — only mode/antimode columns are gated. Useful on wide tables with many ID/UUID/timestamp columns where tracking exact cardinality is wasted work. [default: 0]',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      description: 'When set, the first row will NOT be interpreted as column names. i.e., They will be included in statistics.',
    },
    {
      displayName: 'Nulls',
      name: 'nulls',
      type: 'boolean',
      default: false,
      description: 'Include NULLs in the population size for computing mean and standard deviation.',
    },
    {
      displayName: 'Percentile List',
      name: 'percentileList',
      type: 'string',
      default: '',
      description: 'Comma-separated list of percentiles to compute. For example, "5,10,40,60,90,95" will compute percentiles 5th, 10th, 40th, 60th, 90th, and 95th. Multiple percentiles are separated by the QSV_STATS_SEPARATOR environment variable. If not set, the default separator is "|". It is ignored if --percentiles is not set. Special values "deciles" and "quintiles" are automatically expanded to "10,20,30,40,50,60,70,80,90" and "20,40,60,80" respectively. [default: 5,10,40,60,90,95]',
    },
    {
      displayName: 'Percentiles',
      name: 'percentiles',
      type: 'boolean',
      default: false,
      description: 'Compute custom percentiles using the nearest rank method. https://en.wikipedia.org/wiki/Percentile#The_nearest-rank_method',
    },
    {
      displayName: 'Prefer Dmy',
      name: 'preferDmy',
      type: 'boolean',
      default: false,
      description: 'Parse dates in dmy format. Otherwise, use mdy format. Ignored if --infer-dates is false.',
    },
    {
      displayName: 'Pretty Json',
      name: 'prettyJson',
      type: 'boolean',
      default: false,
      description: 'Like --jsonl, but emit a single pretty-printed JSON array of the per-column objects instead of newline-delimited objects. Cannot be combined with --stats-jsonl or --jsonl.',
    },
    {
      displayName: 'Quantile Method',
      name: 'quantileMethod',
      type: 'string',
      default: '',
      description: 'Algorithm used to compute the median, quartiles and custom percentiles. Choices: exact  - load all values into memory and sort (current behavior). O(N) memory per numeric column, exact deterministic results. approx - use t-digest (Apache DataSketches port, based on Dunning\'s MergingDigest). O(K) memory per numeric column (K~200 centroids), O(1) quantile reads. Approximate (~1% rank error, more accurate at the tails). Restrictions: * --mad is disabled with a warning under approx. * --weight is rejected; the upstream datasketches crate does not expose weighted-update. * Results may differ slightly across runs with different --jobs values. * Requires a little-endian target. Apache DataSketches does not support big-endian platforms (e.g., s390x); on those builds, this choice is rejected. [default: exact]',
    },
    {
      displayName: 'Quartiles',
      name: 'quartiles',
      type: 'boolean',
      default: false,
      description: 'Compute the quartiles (using method 3), the IQR, the lower/upper, inner/outer fences and skewness. https://en.wikipedia.org/wiki/Quartile#Method_3',
    },
    {
      displayName: 'Round',
      name: 'round',
      type: 'string',
      default: '',
      description: 'Round statistics to <decimal_places>. Rounding is done following Midpoint Nearest Even (aka "Bankers Rounding") rule. https://docs.rs/rust_decimal/latest/rust_decimal/enum.RoundingStrategy.html If set to the sentinel value 9999, no rounding is done. For dates - range, stddev & IQR are rounded to 1e-5 day precision (sub-second), with trailing zeros trimmed in the displayed output. [default: 4]',
    },
    {
      displayName: 'Select',
      name: 'select',
      type: 'string',
      default: '',
      description: 'Select a subset of columns to compute stats for. See \'qsv select --help\' for the format details. This is provided here because piping \'qsv select\' into \'qsv stats\' will prevent the use of indexing.',
    },
    {
      displayName: 'Stats Jsonl',
      name: 'statsJsonl',
      type: 'boolean',
      default: false,
      description: 'Also write the stats in JSONL format. If set, the stats will be written to <FILESTEM>.stats.csv.data.jsonl. Note that this option used internally by other qsv "smart" commands (see https://github.com/dathere/qsv/blob/master/docs/PERFORMANCE.md#stats-cache) to load cached stats to make them work smarter & faster. You can preemptively create the stats-jsonl file by using this option BEFORE running "smart" commands and they will automatically use it.',
    },
    {
      displayName: 'Typesonly',
      name: 'typesonly',
      type: 'boolean',
      default: false,
      description: 'Infer data types only and do not compute statistics. Note that if you want to infer dates and boolean types, you\'ll still need to use the --infer-dates & --infer-boolean options. BOOLEAN INFERENCING:',
    },
    {
      displayName: 'Vis Whitespace',
      name: 'visWhitespace',
      type: 'boolean',
      default: false,
      description: 'Visualize whitespace characters in the output. See https://github.com/dathere/qsv/wiki/Aggregation-and-Statistics#whitespace-markers for the list of whitespace markers.',
    },
    {
      displayName: 'Weight',
      name: 'weight',
      type: 'string',
      default: '',
      description: 'Compute weighted statistics using the specified column as weights. The weight column must be numeric. When specified, all statistics (mean, stddev, variance, median, quartiles, mode, etc.) will be computed using weighted algorithms. The weight column is automatically excluded from statistics computation. Missing or non-numeric weights default to 1.0. Zero and negative weights are ignored and do not contribute to the statistics. The output filename will be <FILESTEM>.stats.weighted.csv to distinguish from unweighted statistics. DATE INFERENCING:',
    },
    {
      displayName: 'Zero Padded Numeric',
      name: 'zeroPaddedNumeric',
      type: 'boolean',
      default: false,
      description: 'Add a "zero_padded_numeric" column that is "true" when a column\'s leading/padding zeros would be lost if it were cast to a number. Qualifies when the inferred type is String AND every non-null value is numeric (an all-digit integer or a zero-padded decimal code), with at least one carrying a leading zero — e.g. US zip codes, barcodes, zero-padded IDs, and zero-padded decimal codes like 007.1, 05.10 (as in ICD-9, Dewey Decimal & Harmonized System classification codes). qsv keeps all of these as text to preserve their leading zeros, so they are not mistakenly loaded/cast as integer/float. Note that ordinary fractions (0.5) and pure trailing-zero codes (7.10) are not flagged. The cell is empty when the column is not zero-padded numeric. Automatically enabled with --everything. NUMERIC & DATE/DATETIME STATS THAT REQUIRE IN-MEMORY SORTING: The following statistics are only computed for numeric & date/datetime columns & require loading & sorting ALL the selected columns\' data in memory FIRST before computing the statistics.',
    },
    ],
  },
];
