import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv stats' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const StatsDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned as JSON/stdout.",
  },
  {
    displayName: "Select",
    name: "select",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Select a subset of columns to compute stats for. See 'qsv select --help' for the format details. This is provided here because piping 'qsv select' into 'qsv stats' will prevent the use of indexing.",
  },
  {
    displayName: "Everything",
    name: "everything",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description: "Compute all statistics available.",
  },
  {
    displayName: "Typesonly",
    name: "typesonly",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Infer data types only and do not compute statistics. Note that if you want to infer dates and boolean types, you'll still need to use the --infer-dates & --infer-boolean options.",
  },
  {
    displayName: "Infer Boolean",
    name: "inferBoolean",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Infer boolean data type. This automatically enables the --cardinality option. When a column's cardinality is 2, and the 2 values' are in the true/false patterns specified by --boolean-patterns, the data type is inferred as boolean.",
  },
  {
    displayName: "Boolean Patterns",
    name: "booleanPatterns",
    type: "string",
    default: "1:0,t*:f*,y*:n*",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      'Comma-separated list of boolean pattern pairs in the format "true_pattern:false_pattern". Each pattern can be a string of any length. The patterns are case-insensitive. If a pattern ends with a "*", it is treated as a prefix. For example, "t*:f*,y*:n*" will match "true", "truthy", "Truth" as boolean true values so long as the corresponding false pattern (e.g. False, f, etc.) is also matched & cardinality is 2. Ignored if --infer-boolean is false. [default: 1:0,t*:f*,y*:n*]',
  },
  {
    displayName: "Mode",
    name: "mode",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      'Compute the mode/s & antimode/s. Multimodal-aware. If there are multiple modes/antimodes, they are separated by the QSV_STATS_SEPARATOR environment variable. If not set, the default separator is "|". Uses memory proportional to the cardinality of each column.',
  },
  {
    displayName: "Cardinality",
    name: "cardinality",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Compute the cardinality and the uniqueness ratio. This is automatically enabled if --infer-boolean is enabled. https://en.wikipedia.org/wiki/Cardinality_(SQL_statements) Uses memory proportional to the number of unique values in each column.",
  },
  {
    displayName: "Zero Padded Numeric",
    name: "zeroPaddedNumeric",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      'Add a "zero_padded_numeric" column that is "true" when a column\'s leading/padding zeros would be lost if it were cast to a number. Qualifies when the inferred type is String AND every non-null value is numeric (an all-digit integer or a zero-padded decimal code), with at least one carrying a leading zero — e.g. US zip codes, barcodes, zero-padded IDs, and zero-padded decimal codes like 007.1, 05.10 (as in ICD-9, Dewey Decimal & Harmonized System classification codes). qsv keeps all of these as text to preserve their leading zeros, so they are not mistakenly loaded/cast as integer/float. Note that ordinary fractions (0.5) and pure trailing-zero codes (7.10) are not flagged. The cell is empty when the column is not zero-padded numeric. Automatically enabled with --everything.',
  },
  {
    displayName: "Median",
    name: "median",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Compute the median. Loads & sorts all the selected columns' data in memory. https://en.wikipedia.org/wiki/Median",
  },
  {
    displayName: "Mad",
    name: "mad",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Compute the median absolute deviation (MAD). https://en.wikipedia.org/wiki/Median_absolute_deviation",
  },
  {
    displayName: "Quartiles",
    name: "quartiles",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Compute the quartiles (using method 3), the IQR, the lower/upper, inner/outer fences and skewness. https://en.wikipedia.org/wiki/Quartile#Method_3",
  },
  {
    displayName: "Percentiles",
    name: "percentiles",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Compute custom percentiles using the nearest rank method. https://en.wikipedia.org/wiki/Percentile#The_nearest-rank_method",
  },
  {
    displayName: "Percentile List",
    name: "percentileList",
    type: "string",
    default: "5,10,40,60,90,95",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      'Comma-separated list of percentiles to compute. For example, "5,10,40,60,90,95" will compute percentiles 5th, 10th, 40th, 60th, 90th, and 95th. Multiple percentiles are separated by the QSV_STATS_SEPARATOR environment variable. If not set, the default separator is "|". It is ignored if --percentiles is not set. Special values "deciles" and "quintiles" are automatically expanded to "10,20,30,40,50,60,70,80,90" and "20,40,60,80" respectively. [default: 5,10,40,60,90,95]',
  },
  {
    displayName: "Quantile Method",
    name: "quantileMethod",
    type: "string",
    default: "exact",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Algorithm used to compute the median, quartiles and custom percentiles. Choices: exact  - load all values into memory and sort (current behavior). O(N) memory per numeric column, exact deterministic results. approx - use t-digest (Apache DataSketches port, based on Dunning's MergingDigest). O(K) memory per numeric column (K~200 centroids), O(1) quantile reads. Approximate (~1% rank error, more accurate at the tails). Restrictions: * --mad is disabled with a warning under approx. * --weight is rejected; the upstream datasketches crate does not expose weighted-update. * Results may differ slightly across runs with different --jobs values. * Requires a little-endian target. Apache DataSketches does not support big-endian platforms (e.g., s390x); on those builds, this choice is rejected. [default: exact]",
  },
  {
    displayName: "Cardinality Method",
    name: "cardinalityMethod",
    type: "string",
    default: "exact",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      'Algorithm used to compute the --cardinality column. Choices: exact  - track every unique value in a frequency map (current behavior). O(cardinality) memory per column. Subject to --mode-cardinality-cap, which emits the ">=<n>" sentinel on overflow. approx - use HyperLogLog (Apache DataSketches port, lg_k=12). O(1) memory per column (~5KB), ~1.5% relative standard error. Notes: * --mode-cardinality-cap no longer affects the cardinality column under approx; the ">=<n>" sentinel is never emitted. * The cap STILL governs mode/antimode tracking (mode columns still emit "*HIGH_CARDINALITY" on overflow). * --infer-boolean forces exact (boolean inference needs cardinality == 2 exactness); a one-time warning is emitted. * Reproducible across --jobs values: the HLL union used at merge time is associative and order-invariant, so chunk completion order does not affect the final estimate. * Requires a little-endian target. Apache DataSketches does not support big-endian platforms (e.g., s390x); on those builds, this choice is rejected. [default: exact]',
  },
  {
    displayName: "Mode Cardinality Cap",
    name: "modeCardinalityCap",
    type: "string",
    default: "0",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      'Bound mode-tracking memory on high-cardinality columns. When > 0, if a column\'s mode tracker grows past <n> UNIQUE values (true cardinality, for both unweighted and weighted runs), qsv drops it and emits sentinel values instead of exact modes and cardinality. The cap is a direct memory bound on the tracker, which stores one entry per unique value. Sentinel output: * mode columns: "*HIGH_CARDINALITY" * cardinality column: ">=<n>" (the ">=" prefix DOES break downstream parsers expecting a plain integer; cap is opt-in only). Under --cardinality-method approx, the cardinality column ignores this cap (HLL gives an approximate estimate at fixed memory, ~1.5% RSE) — only mode/antimode columns are gated. Useful on wide tables with many ID/UUID/timestamp columns where tracking exact cardinality is wasted work. [default: 0]',
  },
  {
    displayName: "Round",
    name: "round",
    type: "string",
    default: "4",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      'Round statistics to <decimal_places>. Rounding is done following Midpoint Nearest Even (aka "Bankers Rounding") rule. https://docs.rs/rust_decimal/latest/rust_decimal/enum.RoundingStrategy.html If set to the sentinel value 9999, no rounding is done. For dates - range, stddev & IQR are rounded to 1e-5 day precision (sub-second), with trailing zeros trimmed in the displayed output. [default: 4]',
  },
  {
    displayName: "Nulls",
    name: "nulls",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Include NULLs in the population size for computing mean and standard deviation.",
  },
  {
    displayName: "Weight",
    name: "weight",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Compute weighted statistics using the specified column as weights. The weight column must be numeric. When specified, all statistics (mean, stddev, variance, median, quartiles, mode, etc.) will be computed using weighted algorithms. The weight column is automatically excluded from statistics computation. Missing or non-numeric weights default to 1.0. Zero and negative weights are ignored and do not contribute to the statistics. The output filename will be <FILESTEM>.stats.weighted.csv to distinguish from unweighted statistics.",
  },
  {
    displayName: "Infer Dates",
    name: "inferDates",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Infer date/datetime data types. This is an expensive option and should only be used when you know there are date/datetime fields. Also, if timezone is not specified in the data, it'll be set to UTC.",
  },
  {
    displayName: "Dates Whitelist",
    name: "datesWhitelist",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "The comma-separated, case-insensitive patterns to look for when shortlisting fields for date inferencing. i.e. if the field's name has any of these patterns, it is shortlisted for date inferencing.",
  },
  {
    displayName: "Prefer Dmy",
    name: "preferDmy",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Parse dates in dmy format. Otherwise, use mdy format. Ignored if --infer-dates is false.",
  },
  {
    displayName: "Force",
    name: "force",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Force recomputing stats even if valid precomputed stats cache exists.",
  },
  {
    displayName: "Jobs",
    name: "jobs",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "The number of jobs to run in parallel. This works only when the given CSV has an index. Note that a file handle is opened for each job. When not set, the number of jobs is set to the number of CPUs detected.",
  },
  {
    displayName: "Stats Jsonl",
    name: "statsJsonl",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      'Also write the stats in JSONL format. If set, the stats will be written to <FILESTEM>.stats.csv.data.jsonl. Note that this option used internally by other qsv "smart" commands (see https://github.com/dathere/qsv/blob/master/docs/PERFORMANCE.md#stats-cache) to load cached stats to make them work smarter & faster. You can preemptively create the stats-jsonl file by using this option BEFORE running "smart" commands and they will automatically use it.',
  },
  {
    displayName: "Jsonl",
    name: "jsonl",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Emit the stats to stdout as JSON Lines (NDJSON) - one JSON object per column - instead of CSV. This is the same per-column shape the --stats-jsonl sidecar file uses, but streamed to stdout. Respects --output (the NDJSON is written to the file instead). Cannot be combined with --stats-jsonl or --pretty-json.",
  },
  {
    displayName: "Pretty Json",
    name: "prettyJson",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Like --jsonl, but emit a single pretty-printed JSON array of the per-column objects instead of newline-delimited objects. Cannot be combined with --stats-jsonl or --jsonl.",
  },
  {
    displayName: "Cache Threshold",
    name: "cacheThreshold",
    type: "string",
    default: "5000",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Controls the creation of stats cache files. * when greater than 1, the threshold in milliseconds before caching stats results. If a stats run takes longer than this threshold, the stats results will be cached. * 0 to suppress caching. * 1 to force caching. * a negative number to automatically create an index when the input file size is greater than abs(arg) in bytes. If the negative number ends with 5, it will delete the index file and the stats cache file after the stats run. Otherwise, the index file and the cache files are kept. [default: 5000]",
  },
  {
    displayName: "Vis Whitespace",
    name: "visWhitespace",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description:
      "Visualize whitespace characters in the output. See https://github.com/dathere/qsv/wiki/Aggregation-and-Statistics#whitespace-markers for the list of whitespace markers.",
  },
  {
    displayName: "Output",
    name: "output",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description: "Write output to <file> instead of stdout.",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description: "When set, the first row will NOT be interpreted",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description: "The field delimiter for READING CSV data.",
  },
  {
    displayName: "Memcheck",
    name: "memcheck",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["stats"],
      },
    },
    description: "Use CONSERVATIVE heuristics for the in-memory load",
  },
];
