import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv synthesize' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const SynthesizeDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Dictionary',
      name: 'dictionary',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Data Dictionary JSON file produced by',
    },
    {
      displayName: 'Infer Content Type',
      name: 'inferContentType',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Generate the Data Dictionary on the fly by invoking',
    },
    {
      displayName: 'Rows',
      name: 'rows',
      type: 'string',
      default: '100',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Number of synthetic rows to generate. [default: 100]',
    },
    {
      displayName: 'Seed',
      name: 'seed',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'RNG seed for fully reproducible output.',
    },
    {
      displayName: 'Locale',
      name: 'locale',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Locale for faker-backed columns. Case-insensitive.',
    },
    {
      displayName: 'Freq Limit',
      name: 'freqLimit',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Frequency pool depth passed to the internal `frequency`',
    },
    {
      displayName: 'Stats Options',
      name: 'statsOptions',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Extra options appended to the internal `stats` run.',
    },
    {
      displayName: 'Consistent Fakes',
      name: 'consistentFakes',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'For structured-faker columns with bounded cardinality',
    },
    {
      displayName: 'No Relationships',
      name: 'noRelationships',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Disable inter-column relationship modeling. Every',
    },
    {
      displayName: 'Joint Cardinality Cap',
      name: 'jointCardinalityCap',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Maximum number of distinct value-tuples a',
    },
    {
      displayName: 'Correlation Threshold',
      name: 'correlationThreshold',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Minimum absolute Spearman correlation for a',
    },
    {
      displayName: 'Strict Relationships',
      name: 'strictRelationships',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Abort instead of warning-and-degrading when a',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'Number of jobs to use for the internal `stats` and',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['synthesize'],
        },
      },
      description: 'The field delimiter for reading the input CSV.',
    },
];
