import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv template' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const TemplateDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Template',
      name: 'template',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'MiniJinja template string to use (alternative to --template-file)',
    },
    {
      displayName: 'Template File',
      name: 'templateFile',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'MiniJinja template file to use',
    },
    {
      displayName: 'Globals Json',
      name: 'globalsJson',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'A JSON file containing global variables to make available in templates. The JSON properties can be accessed in templates using the "qsv_g" namespace (e.g. {{qsv_g.school_name}}, {{qsv_g.year}}). This allows sharing common values across all template renders.',
    },
    {
      displayName: 'Outfilename',
      name: 'outfilename',
      type: 'string',
      default: 'QSV_ROWNO',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'MiniJinja template string to use to create the filename of the output files to write to <outdir>. If set to just QSV_ROWNO, the filestem is set to the current rowno of the record, padded with leading zeroes, with the ".txt" extension (e.g. 001.txt, 002.txt, etc.) Note that all the fields, including QSV_ROWNO, are available when defining the filename template. [default: QSV_ROWNO]',
    },
    {
      displayName: 'Outsubdir Size',
      name: 'outsubdirSize',
      type: 'string',
      default: '1000',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'The number of files per subdirectory in <outdir>. [default: 1000]',
    },
    {
      displayName: 'Customfilter Error',
      name: 'customfilterError',
      type: 'string',
      default: '<FILTER_ERROR>',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'The value to return when a custom filter returns an error. Use "<empty string>" to return an empty string. [default: <FILTER_ERROR>]',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'The number of jobs to run in parallel. When not set, the number of jobs is set to the number of CPUs detected.',
    },
    {
      displayName: 'Batch',
      name: 'batch',
      type: 'string',
      default: '50000',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'The number of rows per batch to load into memory, before running in parallel. Set to 0 to load all rows in one batch. [default: 50000]',
    },
    {
      displayName: 'Timeout',
      name: 'timeout',
      type: 'string',
      default: '30',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'Timeout for downloading lookups on URLs. [default: 30]',
    },
    {
      displayName: 'Cache Dir',
      name: 'cacheDir',
      type: 'string',
      default: '~/.qsv-cache',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'The directory to use for caching downloaded lookup resources. If the directory does not exist, qsv will attempt to create it. If the QSV_CACHE_DIR envvar is set, it will be used instead. [default: ~/.qsv-cache]',
    },
    {
      displayName: 'Ckan Api',
      name: 'ckanApi',
      type: 'string',
      default: 'https://data.dathere.com/api/3/action',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'The URL of the CKAN API to use for downloading lookup resources with the "ckan://" scheme. If the QSV_CKAN_API envvar is set, it will be used instead. [default: https://data.dathere.com/api/3/action]',
    },
    {
      displayName: 'Ckan Token',
      name: 'ckanToken',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'The CKAN API token to use. Only required if downloading private resources. If the QSV_CKAN_TOKEN envvar is set, it will be used instead.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'When set, the first row will not be interpreted as headers. Templates must use numeric 1-based indices with the "_c" prefix. (e.g. col1: {{_c1}} col2: {{_c2}})',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: ',',
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'Field separator for reading CSV [default: ,]',
    },
    {
      displayName: 'Progressbar',
      name: 'progressbar',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['template'],
        },
      },
      description: 'Show progress bars. Not valid for stdin.',
    },
];
