import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv to' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const ToDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Print Package",
    name: "printPackage",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Print statistics as datapackage, by default will print field summary.",
  },
  {
    displayName: "Dump",
    name: "dump",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Create database dump file for use with `psql` or `sqlite3` command line tools (postgres/sqlite only).",
  },
  {
    displayName: "Stats",
    name: "stats",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Produce extra statistics about the data beyond just type guessing.",
  },
  {
    displayName: "Stats Csv",
    name: "statsCsv",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description: "Output stats as CSV to specified file.",
  },
  {
    displayName: "Quiet",
    name: "quiet",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description: "Do not print out field summary.",
  },
  {
    displayName: "Schema",
    name: "schema",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description: "The schema to load the data into. (postgres only).",
  },
  {
    displayName: "Infer Len",
    name: "inferLen",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "The number of rows to use for schema inference (parquet only). Note that even if a pschema.json file exists for an input file, explicitly specifying infer-len will cause qsv to ignore the pschema.json and infer the schema from the CSV data instead, including when set to 0. Set to 0 to infer from all rows (not recommended for large files).",
  },
  {
    displayName: "Try Parse Dates",
    name: "tryParseDates",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Attempt to parse date/datetime columns with polars' date inference logic. This may result in more accurate date parsing, but can be slower on large files. (parquet only).",
  },
  {
    displayName: "Drop",
    name: "drop",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Drop tables before loading new data into them (postgres/sqlite only).",
  },
  {
    displayName: "Evolve",
    name: "evolve",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "If loading into existing db, alter existing tables so that new data will load. (postgres/sqlite only).",
  },
  {
    displayName: "Pipe",
    name: "pipe",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Adjust output format for piped data (omits row counts and field format columns).",
  },
  {
    displayName: "Table",
    name: "table",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      'Use this as the table/sheet/file name (postgres/sqlite/xlsx/ods/parquet). Overrides the default name derived from the input filename. When reading from stdin, the default table name is "stdin". Only valid with a single input file. For postgres/sqlite: must start with a letter or underscore, contain only alphanumeric characters and underscores (max 63). For xlsx/ods: used as sheet name (max 31 chars, cannot contain \\ / * [ ] : ?).',
  },
  {
    displayName: "Separator",
    name: "separator",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "For xlsx, use this character to help truncate xlsx sheet names. Defaults to space.",
  },
  {
    displayName: "Compression",
    name: "compression",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Parquet compression codec (parquet only). Valid values: zstd (default), gzip, snappy, lz4raw, uncompressed.",
  },
  {
    displayName: "Compress Level",
    name: "compressLevel",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "Compression level (parquet only). For gzip: 1-9 (default: 6). For zstd: -7 to 22 (default: 3). Ignored for other codecs.",
  },
  {
    displayName: "All Strings",
    name: "allStrings",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description: "Convert all fields to strings.",
  },
  {
    displayName: "Jobs",
    name: "jobs",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "The number of jobs to run in parallel. When not set, the number of jobs is set to the number of CPUs detected.",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["to"],
      },
    },
    description:
      "The field delimiter for reading CSV data. Must be a single character. (default: ,)",
  },
];
