import type { INodeProperties } from 'n8n-workflow';

/**
 * Property definitions for 'qsv tojsonl' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const TojsonlDescription: INodeProperties[] = [
    {
      displayName: 'Input CSV File Path',
      name: 'inputPath',
      type: 'string',
      default: '',
      required: true,
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'The absolute or relative file path to the input CSV file',
    },
    {
      displayName: 'Output File Path',
      name: 'outputPath',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'Path where the output will be saved. If empty, result may be returned in stdout/JSON.',
    },
    {
      displayName: 'Trim',
      name: 'trim',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'Trim leading and trailing whitespace from fields',
    },
    {
      displayName: 'No Boolean',
      name: 'noBoolean',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'Do not infer boolean fields.',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'The number of jobs to run in parallel.',
    },
    {
      displayName: 'Batch',
      name: 'batch',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'The number of rows per batch to load into memory,',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'The field delimiter for reading CSV data.',
    },
    {
      displayName: 'Memcheck',
      name: 'memcheck',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'Check if there is enough memory to load the entire',
    },
    {
      displayName: 'Quiet',
      name: 'quiet',
      type: 'boolean',
      default: false,
      displayOptions: {
        show: {
          operation: ['tojsonl'],
        },
      },
      description: 'Do not display enum/const list inferencing messages.',
    },
];
