import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv transpose' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const TransposeDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["transpose"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["transpose"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "Multipass",
    name: "multipass",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["transpose"],
      },
    },
    description:
      "Process the transpose by making multiple passes over the dataset. Consumes memory relative to the number of rows. Note that in general it is faster to process the transpose in memory. Useful for really big datasets as the default is to read the entire dataset into memory.",
  },
  {
    displayName: "Select",
    name: "select",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["transpose"],
      },
    },
    description:
      "Select a subset of columns to transpose. When used with --long, this filters which columns become attribute rows (the field columns are unaffected). See 'qsv select --help' for the full selection syntax.",
  },
  {
    displayName: "Long",
    name: "long",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["transpose"],
      },
    },
    description: 'Convert wide-format CSV to "long" format.',
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["transpose"],
      },
    },
    description:
      "The field delimiter for reading CSV data. Must be a single character. (default: ,)",
  },
  {
    displayName: "Memcheck",
    name: "memcheck",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["transpose"],
      },
    },
    description:
      "Check if there is enough memory to load the entire CSV into memory using CONSERVATIVE heuristics. Ignored when --multipass or --long option is enabled.",
  },
];
