import type { INodeProperties } from 'n8n-workflow';

export const ValidateDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['validate'],
      },
    },
  },
  {
    displayName: 'JSON Schema Path / URL',
    name: 'jsonSchema',
    type: 'string',
    required: false,
    default: '',
    description: 'Optional path or URL to JSON Schema. If omitted, performs standard RFC 4180 validation.',
    displayOptions: {
      show: {
        operation: ['validate'],
      },
    },
  },

  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv validate (Docs: https://github.com/dathere/qsv/blob/master/docs/help/validate.md)',
    displayOptions: {
      show: {
        operation: ['validate'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['validate'],
      },
    },
    options: [
    {
      displayName: 'Backtrack Limit',
      name: 'backtrackLimit',
      type: 'string',
      default: '',
      description: 'Set the approximate number of backtracking steps allowed. This is only used when --fancy-regex is set. [default: 1000000] OPTIONS FOR BOTH REGEX ENGINES:',
    },
    {
      displayName: 'Batch',
      name: 'batch',
      type: 'string',
      default: '',
      description: 'The number of rows per batch to load into memory, before running in parallel. Automatically determined for CSV files with more than 50000 rows. Set to 0 to load all rows in one batch. Set to 1 to force batch optimization even for files with less than 50000 rows. [default: 50000]',
    },
    {
      displayName: 'Cache Dir',
      name: 'cacheDir',
      type: 'string',
      default: '',
      description: 'The directory to use for caching downloaded dynamicEnum resources. If the directory does not exist, qsv will attempt to create it. If the QSV_CACHE_DIR envvar is set, it will be used instead. Not available on qsvlite. [default: ~/.qsv-cache]',
    },
    {
      displayName: 'Ckan Api',
      name: 'ckanApi',
      type: 'string',
      default: '',
      description: 'The URL of the CKAN API to use for downloading dynamicEnum resources with the "ckan://" scheme. If the QSV_CKAN_API envvar is set, it will be used instead. Not available on qsvlite. [default: https://data.dathere.com/api/3/action]',
    },
    {
      displayName: 'Ckan Token',
      name: 'ckanToken',
      type: 'string',
      default: '',
      description: 'The CKAN API token to use. Only required if downloading private resources. If the QSV_CKAN_TOKEN envvar is set, it will be used instead. Not available on qsvlite.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      description: 'The field delimiter for reading CSV data. Must be a single character.',
    },
    {
      displayName: 'Dfa Size Limit',
      name: 'dfaSizeLimit',
      type: 'string',
      default: '',
      description: 'Set the approximate capacity, in megabytes, of the cache of transitions used by the engine\'s lazy Discrete Finite Automata. [default: 10]',
    },
    {
      displayName: 'Email Display Text',
      name: 'emailDisplayText',
      type: 'boolean',
      default: false,
      description: 'Allow display text in emails. e.g. "John Doe <john.doe@example.com>" is INVALID if this option is NOT set.',
    },
    {
      displayName: 'Email Domain Literal',
      name: 'emailDomainLiteral',
      type: 'boolean',
      default: false,
      description: 'Allow domain literals in emails. e.g. "john.doe@[127.0.0.1]" is VALID if this option is set.',
    },
    {
      displayName: 'Email Min Subdomains',
      name: 'emailMinSubdomains',
      type: 'string',
      default: '',
      description: 'Minimum number of subdomains required in the email. e.g. "jdoe@example.com" is INVALID if this option is set to 3, but "jdoe@sub.example.com" is VALID. [default: 2]',
    },
    {
      displayName: 'Email Required Tld',
      name: 'emailRequiredTld',
      type: 'boolean',
      default: false,
      description: 'Require the email to have a valid Top-Level Domain (TLD) (e.g. .com, .org, .net, etc.). e.g. "john.doe@example" is VALID if this option is NOT set.',
    },
    {
      displayName: 'Fail Fast',
      name: 'failFast',
      type: 'boolean',
      default: false,
      description: 'Stops on first error.',
    },
    {
      displayName: 'Fancy Regex',
      name: 'fancyRegex',
      type: 'boolean',
      default: false,
      description: 'Use the fancy regex engine instead of the default regex engine for validation. The fancy engine supports advanced regex features such as lookaround and backreferences, but is not as performant as the default regex engine which guarantees linear-time matching, prevents DoS attacks, and is more efficient for simple patterns.',
    },
    {
      displayName: 'Invalid',
      name: 'invalid',
      type: 'string',
      default: 'invalid',
      description: 'Invalid record output file suffix. [default: invalid]',
    },
    {
      displayName: 'Jobs',
      name: 'jobs',
      type: 'string',
      default: '',
      description: 'The number of jobs to run in parallel. When not set, the number of jobs is set to the number of CPUs detected.',
    },
    {
      displayName: 'Json',
      name: 'json',
      type: 'boolean',
      default: false,
      description: 'When validating without a JSON Schema, return the RFC 4180 check as a JSON file instead of a message.',
    },
    {
      displayName: 'No Format Validation',
      name: 'noFormatValidation',
      type: 'boolean',
      default: false,
      description: 'Disable JSON Schema format validation. Ignores all JSON Schema "format" keywords (e.g. date,email, uri, currency, etc.). This is useful when you want to validate the structure of the CSV file w/o worrying about the data types and domain/range of the fields.',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      description: 'When set, the first row will not be interpreted as headers. It will be validated with the rest of the rows. Otherwise, the first row will always appear as the header row in the output. Note that this option is only valid when running in RFC 4180 validation mode as JSON Schema validation requires headers.',
    },
    {
      displayName: 'Pretty Json',
      name: 'prettyJson',
      type: 'boolean',
      default: false,
      description: 'Same as --json, but pretty printed.',
    },
    {
      displayName: 'Progressbar',
      name: 'progressbar',
      type: 'boolean',
      default: false,
      description: 'Show progress bars. Not valid for stdin.',
    },
    {
      displayName: 'Quiet',
      name: 'quiet',
      type: 'boolean',
      default: false,
      description: 'Do not display validation summary message.',
    },
    {
      displayName: 'Size Limit',
      name: 'sizeLimit',
      type: 'string',
      default: '',
      description: 'Set the approximate size limit, in megabytes, of a compiled regex. [default: 50]',
    },
    {
      displayName: 'Split Ragged',
      name: 'splitRagged',
      type: 'boolean',
      default: false,
      description: 'Opt-in mode: instead of aborting on the first row with the wrong number of columns (a "ragged" row), write well-formed rows to the \'<input>.<valid>\' file and the ragged rows to the \'<input>.<invalid>\' file, with a report appended to \'<input>.validation-errors.tsv\'. Returns a non-zero exit code when any ragged row is found. Only column-count mismatches are diverted; malformed quoting and non-UTF-8 data still abort validation. Works in both RFC 4180 and JSON Schema validation modes. The split files are written next to each input file, so this is intended for on-disk file input(s).',
    },
    {
      displayName: 'Timeout',
      name: 'timeout',
      type: 'string',
      default: '',
      description: 'Timeout for downloading json-schemas on URLs and for \'dynamicEnum\' lookups on URLs. If 0, no timeout is used. [default: 30]',
    },
    {
      displayName: 'Trim',
      name: 'trim',
      type: 'boolean',
      default: false,
      description: 'Trim leading and trailing whitespace from fields before validating.',
    },
    {
      displayName: 'Valid',
      name: 'valid',
      type: 'string',
      default: 'valid',
      description: 'Valid record output file suffix. [default: valid]',
    },
    {
      displayName: 'Valid Output',
      name: 'validOutput',
      type: 'string',
      default: '',
      description: 'Change validation mode behavior so if ALL rows are valid, to pass it to output, return exit code 1, and set stderr to the number of valid rows. Setting this will override the default behavior of creating a valid file only when there are invalid records. To send valid records to stdout, use `-` as the filename.',
    },
    ],
  },
];
