import type { INodeProperties } from "n8n-workflow";

/**
 * Property definitions for 'qsv viz' operation.
 * Auto-generated by scripts/generate-qsv-nodes.ts
 */
export const VizDescription: INodeProperties[] = [
  {
    displayName: "Input CSV File Path",
    name: "inputPath",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "The absolute or relative file path to the input CSV file",
  },
  {
    displayName: "Output File Path",
    name: "outputPath",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "Path where the output will be saved. If empty, result may be returned in stdout/JSON.",
  },
  {
    displayName: "X",
    name: "x",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Column for the x-axis / category / bin / group.",
  },
  {
    displayName: "Y",
    name: "y",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Column for the y-axis / value.",
  },
  {
    displayName: "Z",
    name: "z",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "The z column: a heatmap pivot value (with --x and --y), or",
  },
  {
    displayName: "Cols",
    name: "cols",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Columns to use. For heatmap: numeric columns for the",
  },
  {
    displayName: "Series",
    name: "series",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Column to split into multiple series (one trace per",
  },
  {
    displayName: "Color",
    name: "color",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "For scatter/scatter3d/map/geo: a numeric column to encode as",
  },
  {
    displayName: "Size",
    name: "size",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "For scatter/scatter3d/map/geo: a numeric column to encode as",
  },
  {
    displayName: "Donut",
    name: "donut",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Render a pie chart as a donut (with a center hole).",
  },
  {
    displayName: "Ohlc Open",
    name: "ohlcOpen",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Open-price column for candlestick/ohlc charts.",
  },
  {
    displayName: "High",
    name: "high",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "High-price column for candlestick/ohlc charts.",
  },
  {
    displayName: "Low",
    name: "low",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Low-price column for candlestick/ohlc charts.",
  },
  {
    displayName: "Close",
    name: "close",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Close-price column for candlestick/ohlc charts.",
  },
  {
    displayName: "Source",
    name: "source",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Source node column for a sankey diagram.",
  },
  {
    displayName: "Target",
    name: "target",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Target node column for a sankey diagram.",
  },
  {
    displayName: "Value",
    name: "value",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Flow value column for a sankey diagram. When omitted,",
  },
  {
    displayName: "Sankey Value Order",
    name: "sankeyValueOrder",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Order sankey nodes by total flow (largest at the top of each",
  },
  {
    displayName: "Bins",
    name: "bins",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Number of bins. For histogram: bins along the x-axis",
  },
  {
    displayName: "Agg",
    name: "agg",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "For bar/line, aggregate the y values when the x value",
  },
  {
    displayName: "Box Points",
    name: "boxPoints",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Which sample points to draw alongside a box. Reading the",
  },
  {
    displayName: "Lat",
    name: "lat",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Latitude column for a map (decimal degrees, -90 to 90).",
  },
  {
    displayName: "Lon",
    name: "lon",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Longitude column for a map (decimal degrees, -180 to 180).",
  },
  {
    displayName: "Text",
    name: "text",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Column whose value labels each point on hover.",
  },
  {
    displayName: "Density",
    name: "density",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Render a density heatmap (DensityMap) instead of points.",
  },
  {
    displayName: "Style",
    name: "style",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "MapLibre basemap style (all render without an access token):",
  },
  {
    displayName: "Projection",
    name: "projection",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Map projection for `viz geo`. One of: natural-earth (the",
  },
  {
    displayName: "Locations",
    name: "locations",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Column holding the region key for each row (an ISO-3 country",
  },
  {
    displayName: "Location Mode",
    name: "locationMode",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "How --locations values are matched to regions. One of: iso3",
  },
  {
    displayName: "Color Scale",
    name: "colorScale",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "Colorscale for the region fill. One of: viridis (the default),",
  },
  {
    displayName: "Map",
    name: "map",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "Render on a token-free MapLibre tile basemap (a ChoroplethMap)",
  },
  {
    displayName: "Geojson",
    name: "geojson",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "Custom region polygons as a local file path or an http(s) URL",
  },
  {
    displayName: "Feature Id Key",
    name: "featureIdKey",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Property path in each GeoJSON feature whose value matches an",
  },
  {
    displayName: "Feature Name Key",
    name: "featureNameKey",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "GeoJSON property path whose value is shown as the",
  },
  {
    displayName: "Denominator Key",
    name: "denominatorKey",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "GeoJSON property path holding each region's DENOMINATOR",
  },
  {
    displayName: "Denominator Unit",
    name: "denominatorUnit",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "<u>",
  },
  {
    displayName: "Denominator",
    name: "denominator",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Column holding each region's DENOMINATOR, as an alternative",
  },
  {
    displayName: "Geocode",
    name: "geocode",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Derive the region codes by reusing qsv's geocode engine",
  },
  {
    displayName: "Geocode Country",
    name: "geocodeCountry",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "<col>",
  },
  {
    displayName: "Geocode Admin1",
    name: "geocodeAdmin1",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "<col>",
  },
  {
    displayName: "No Snap",
    name: "noSnap",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "For point-in-polygon binning (lat/lon points binned into a",
  },
  {
    displayName: "Snap Max Dist",
    name: "snapMaxDist",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "For point-in-polygon binning: the farthest (in km) an outside",
  },
  {
    displayName: "Max Charts",
    name: "maxCharts",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "Maximum number of panels in the Data Schematic. 0 (the default)",
  },
  {
    displayName: "Grid Cols",
    name: "gridCols",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "Number of columns in the Data Schematic grid for the per-column",
  },
  {
    displayName: "Preview Threshold",
    name: "previewThreshold",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Row threshold for the interactive data viewer drawer of",
  },
  {
    displayName: "Heatmap Density",
    name: "heatmapDensity",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "For the `viz smart` map panel: at or above <n> mappable",
  },
  {
    displayName: "Cluster",
    name: "cluster",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "For the `viz smart` map panel: whether to offer an",
  },
  {
    displayName: "Photos",
    name: "photos",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "For the `viz smart` map panel: when a column holds image URLs",
  },
  {
    displayName: "Limit",
    name: "limit",
    type: "string",
    default: "10",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Top-N categories per frequency bar chart. [default: 10]",
  },
  {
    displayName: "No Nulls",
    name: "noNulls",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      'Omit the "(NULL)" bar (empty cells) from frequency bar charts.',
  },
  {
    displayName: "No Other",
    name: "noOther",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      'Omit the "Other (N)" aggregate bar from frequency bar charts. It',
  },
  {
    displayName: "Smarter",
    name: "smarter",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "Before building the Data Schematic, run `qsv moarstats --advanced`",
  },
  {
    displayName: "Hierarchy Style",
    name: "hierarchyStyle",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "For `smart`, the chart used for the categorical part-to-whole",
  },
  {
    displayName: "Dictionary",
    name: "dictionary",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "Use a describegpt Data Dictionary to guide panel selection from",
  },
  {
    displayName: "Dictionary Context",
    name: "dictionaryContext",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Path to a file with extra context about the dataset",
  },
  {
    displayName: "Dict Info",
    name: "dictInfo",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "When a usable Data Dictionary is available (per --dictionary), add",
  },
  {
    displayName: "Dataset Pid",
    name: "datasetPid",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description:
      "A persistent identifier (PID) for the dataset - typically a full",
  },
  {
    displayName: "Bivariate",
    name: "bivariate",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Add two pairwise-association overview panels driven by",
  },
  {
    displayName: "Log Scale",
    name: "logScale",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Use a logarithmic y-axis for panels with a high dynamic",
  },
  {
    displayName: "Violin",
    name: "violin",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Draw distribution panels as violins (a box plot",
  },
  {
    displayName: "Title",
    name: "title",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Chart title.",
  },
  {
    displayName: "X Title",
    name: "xTitle",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "X-axis title. (defaults to the x column name)",
  },
  {
    displayName: "Y Title",
    name: "yTitle",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Y-axis title. (defaults to the y column name)",
  },
  {
    displayName: "Y Range",
    name: "yRange",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Fix the y-axis to an explicit min:max range (two colon-",
  },
  {
    displayName: "Rangeslider",
    name: "rangeslider",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Add a draggable range-slider (a navigator strip) under the",
  },
  {
    displayName: "Slider",
    name: "slider",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Animate the chart over a column: each distinct value of the",
  },
  {
    displayName: "Slider Speed",
    name: "sliderSpeed",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Milliseconds each animation frame is shown while playing.",
  },
  {
    displayName: "Slider Cumulative",
    name: "sliderCumulative",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Accumulate rows across frames: frame N includes every row",
  },
  {
    displayName: "Annotation",
    name: "annotation",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Caption note drawn at the bottom of the plot (e.g. to note",
  },
  {
    displayName: "Theme",
    name: "theme",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Plotly theme that drives the chart's overall look",
  },
  {
    displayName: "Language",
    name: "language",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Render the Data Schematic UI in this language. Accepts a",
  },
  {
    displayName: "Width",
    name: "width",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Image width in pixels for static export. Default 1000;",
  },
  {
    displayName: "Height",
    name: "height",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Image height in pixels for static export. Default 600;",
  },
  {
    displayName: "Scale",
    name: "scale",
    type: "string",
    default: "1.0",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Image scale factor (static export). [default: 1.0]",
  },
  {
    displayName: "Open",
    name: "open",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "Open the generated chart in the default browser/viewer.",
  },
  {
    displayName: "Delimiter",
    name: "delimiter",
    type: "string",
    default: "",
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "The field delimiter for reading CSV data.",
  },
  {
    displayName: "No Headers",
    name: "noHeaders",
    type: "boolean",
    default: false,
    displayOptions: {
      show: {
        operation: ["viz"],
      },
    },
    description: "When set, the first row will not be interpreted",
  },
];
