import type { INodeProperties } from 'n8n-workflow';

export const VizDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['viz'],
      },
    },
  },

  {
    displayName: 'Output File Path',
    name: 'outputPath',
    type: 'string',
    default: '',
    description: 'Optional path to write output file directly to disk (if omitted, results are returned in node output)',
    displayOptions: {
      show: {
        operation: ['viz'],
      },
    },
  },
  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv viz (Docs: https://github.com/dathere/qsv/blob/master/docs/help/viz.md)',
    displayOptions: {
      show: {
        operation: ['viz'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['viz'],
      },
    },
    options: [
    {
      displayName: 'Agg',
      name: 'agg',
      type: 'string',
      default: '',
      description: 'How to combine values. For bar/line, aggregate the y values when the x value repeats: one of sum, mean, count, min, max. For treemap/sunburst/icicle, only the additive aggregations apply: count (the default) or sum (which requires --value). For choropleth, how rows sharing a region are combined: sum when --value is given, else count; pass mean for an intensive measure (a density, rate, index or per-capita figure), since summing those is meaningless and the count/sum hover\'s "share of total" line would be too. On a bubble animation (see the slider option), it collapses each entity x frame cell to a single bubble and defaults to mean, the cell centroid; count is rejected there, since a row count is not a position.',
    },
    {
      displayName: 'Annotation',
      name: 'annotation',
      type: 'string',
      default: '',
      description: 'Caption note drawn at the bottom of the plot (e.g. to note a clipped outlier). Cartesian charts only.',
    },
    {
      displayName: 'Bins',
      name: 'bins',
      type: 'string',
      default: '',
      description: 'Number of bins. For histogram: bins along the x-axis (default: auto). For contour: the per-axis resolution of the density grid (default: 20).',
    },
    {
      displayName: 'Bivariate',
      name: 'bivariate',
      type: 'boolean',
      default: false,
      description: 'Add two pairwise-association overview panels driven by `qsv moarstats --bivariate`: a normalized mutual information (NMI) heatmap over every column pair (numeric AND categorical, unlike the Pearson-only correlation heatmap), plus a ranked "top relationships" bar of the strongest pairs when there are more than 8 chartable columns. Identifier / PII / free-text columns (per the --dictionary option) and map lat/lon columns are excluded. It TURNS ON --smarter, plus --dictionary infer when --dictionary isn\'t already set. Capped at 50 columns (1,225 pairs); wider datasets skip these panels with a warning. Only affects `smart`. See https://github.com/dathere/qsv/wiki/Visualization#bivariate',
    },
    {
      displayName: 'Box Points',
      name: 'boxPoints',
      type: 'string',
      default: '',
      description: 'Which sample points to draw alongside a box or violin. Reading the raw values lets plotly render true Tukey whiskers (1.5*IQR) with the points beyond the fences as outliers. One of: outliers (only the outliers), all (every point, jittered), suspected (mark suspected outliers), none (no points, but still real Tukey whiskers). Applies to `viz box`, `viz violin` AND `viz smart`. For `viz box` the default is outliers; for `viz smart` an explicit mode OVERRIDES a size-based heuristic and is applied to every panel. `none` only hides a violin\'s points, since its KDE needs the values anyway; the cache-only escape hatch is `--violin off` with this set to none. For the heuristic\'s thresholds, see https://github.com/dathere/qsv/wiki/Visualization#distribution-panels',
    },
    {
      displayName: 'Check Geojson Key',
      name: 'checkGeojsonKey',
      type: 'boolean',
      default: false,
      description: 'Diagnostic mode. Instead of rendering, score EVERY candidate feature-id path in --geojson against the distinct values of the locations column and print them ranked by overlap - use it when a region map shades nothing while exiting 0. Requires --geojson and --locations, with a concrete source for the former (path, URL or shortcut); every automatic Census spec is refused, since automatic resolution picks the key itself.',
    },
    {
      displayName: 'Close',
      name: 'close',
      type: 'string',
      default: '',
      description: 'Close-price column for candlestick/ohlc charts.',
    },
    {
      displayName: 'Cluster',
      name: 'cluster',
      type: 'string',
      default: '',
      description: 'For the `viz smart` map panel: whether to offer an in-map "Clusters/Points" toggle that collapses dense points into native MapLibre count bubbles (which expand back into individual, hoverable points on zoom-in). The map always OPENS as individual points. One of: auto, on, off. "auto" offers the toggle for a plain-marker core (no density heatmap, no bubble-size measure) once it reaches 1,000 points; "on" offers it whenever the core draws as markers; "off" omits it. Only affects `smart`. [default: auto]',
    },
    {
      displayName: 'Color',
      name: 'color',
      type: 'string',
      default: '',
      description: 'For scatter/scatter3d/map/geo: a numeric column to encode as marker color (a continuous colorscale with a colorbar). For categorical coloring, use the --series option instead. Cannot be combined with --series. In map density mode, this column is the heatmap weight.',
    },
    {
      displayName: 'Color Scale',
      name: 'colorScale',
      type: 'string',
      default: '',
      description: 'Colorscale for the region fill. One of: viridis (the default), cividis, greys, greens, blues, reds, ylgnbu, ylorrd, bluered, rdbu, portland, electric, jet, hot, blackbody, earth, picnic, rainbow. [default: viridis]',
    },
    {
      displayName: 'Cols',
      name: 'cols',
      type: 'string',
      default: '',
      description: 'Columns to use. For heatmap: numeric columns for the correlation matrix (default: all numeric). For radar: the numeric axes to plot. For treemap/sunburst/icicle: the categorical dimensions that form the hierarchy levels, outermost first (e.g. region,category,subcategory). For splom: the numeric columns to cross-plot (default: all numeric). For parcats: the categorical dimensions to flow across (best with 3-4).',
    },
    {
      displayName: 'Dataset Pid',
      name: 'datasetPid',
      type: 'string',
      default: '',
      description: 'A persistent identifier (PID) for the dataset - typically a full URL such as a DOI (https://doi.org/10.1234/abc) or other citable link. When set, a "PID" row is added to the metadata table at the top of the Data Schematic. http(s) and mailto values become a clickable link; any other scheme is shown as plain text. HTML output only. Only affects `smart`.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Denominator',
      name: 'denominator',
      type: 'string',
      default: '',
      description: 'Column holding each region\'s DENOMINATOR, as an alternative to reading it from the GeoJSON. Its value must be constant within a region (it describes the region, not the row). `viz choropleth` only, and only with a --locations region column - not with the --geocode flag or lat/lon binning. Valid with the default count aggregation and with --agg sum; the other aggregations are already intensive, so a denominator is rejected there. In `viz smart`, declare it in the data dictionary instead, via x-qsv.denominator (see --dictionary). The value `census` is RESERVED (a column of that name cannot be used): it fetches US population from the Census Data API for a per-capita rate with nothing supplied, and being a source rather than a column it works on `viz smart` too. Region codes must be 5-digit county FIPS, 2-digit state FIPS, or 2-letter state codes. The newest published ACS 5-year release is used and is always stated beneath the map; pin one with @<year>, e.g. census@2019. Uncovered regions are excluded and reported. Cached for 30 days (QSV_VIZ_DENOMINATOR_CACHE_TTL_DAYS). REQUIRES a Census API key in QSV_CENSUS_API_KEY - free at https://api.census.gov/data/key_signup.html',
    },
    {
      displayName: 'Denominator Key',
      name: 'denominatorKey',
      type: 'string',
      default: '',
      description: 'GeoJSON property path holding each region\'s DENOMINATOR (e.g. properties.POP2020), addressed like --feature-id-key. Turns a raw-count region map into a RATE map: in `viz choropleth` the map itself becomes the rate; in `viz smart` a rate panel is added BESIDE the count panel. Regions whose denominator is missing or non-positive are excluded and reported; the per-region scale (per 1,000 / 10,000 / 100,000 / 1,000,000 / 1,000,000,000) is chosen automatically. See https://github.com/dathere/qsv/wiki/Visualization#rate-maps',
    },
    {
      displayName: 'Denominator Unit',
      name: 'denominatorUnit',
      type: 'string',
      default: '',
      description: ' Unit the denominator values are IN, so qsv can convert and name them. One of: m2, km2 (also spelled m², km², sqm, sqkm). Values in m2 are converted to km², so the map reads "per km²". NEVER inferred from a field name - real boundary files carry land area in square METRES, which divided raw reads as "per 100,000 AREALAND" at approximately zero everywhere. Boundaries fetched by `--geojson auto` declare their own units and need no flag.',
    },
    {
      displayName: 'Density',
      name: 'density',
      type: 'boolean',
      default: false,
      description: 'Render a density heatmap (DensityMap) instead of points. Weighted by the --color or --size column when given, else by a uniform weight. Cannot be combined with --series.',
    },
    {
      displayName: 'Dict Info',
      name: 'dictInfo',
      type: 'boolean',
      default: false,
      description: 'When a usable Data Dictionary is available (per --dictionary), add a "Data Schematic" link beneath the page title and an info icon on each panel title: hovering shows that column\'s description, clicking opens a human-friendly rendering of the dictionary in a side drawer NEXT TO the plots, scrolled to that column\'s entry. The drawer carries a table of contents, per-column "View chart" links, download buttons bundling every sidecar this run READ (each under 4 MB), and a record of what the Data Schematic LEFT OUT. Everything is embedded in the HTML, so no extra file is written. HTML output only; ignored with a note when no dictionary is available or when exporting an image. Only affects `smart`. See https://github.com/dathere/qsv/wiki/Visualization#dict-info',
    },
    {
      displayName: 'Dictionary',
      name: 'dictionary',
      type: 'string',
      default: '',
      description: 'Use a describegpt Data Dictionary to guide panel selection from each field\'s semantic role/concept (falling back to its content type) instead of relying on column statistics alone: dimensions and numeric codes (ward, census_tract, zone) become bars, measures get box/correlation/trend panels, date/datetime columns feed the time-series panel, identifiers / PII / free-text are skipped, and lat/lon feed the map. Field labels are shown as panel subtitles. Columns the dictionary cannot classify still use the statistical heuristic. <src> is either "infer", to run describegpt on the input now (requires an LLM configured), or a path to an existing describegpt dictionary file (jsonschema or json). With "infer", the generated dictionary is saved beside the input as <stem>.schema.json; if that file already exists it is REUSED as-is, skipping the LLM. An inferred dictionary is a DRAFT, not an oracle: re-inferring the same data can assign a column a different role, and role drives panel selection, so a re-infer can hand you a structurally different Data Schematic. The saved sidecar is therefore the artifact of record - review it, correct it, and keep it beside the data. Set QSV_VIZ_DICT_FRESH=1 to ignore it and bypass describegpt\'s completion cache, forcing a fresh inference that overwrites the sidecar on success. Generation/read failures soft-fall back to the stats-only Data Schematic. qsv re-verifies every hint below on read, so a hand-edit can correct the model but cannot smuggle in a claim the data does not support. Per-field hints live in a property\'s "x-qsv" object: gauge_range [min,max] - render the KPI tile as a GAUGE on that canonical scale; kept only when the observed value is inside it target <goal> - add a "vs target" DELTA (value minus target). A goal you supply, so "infer" never emits one currency <ISO-4217> - prefix the KPI tile with that currency\'s symbol ($192B); an unknown code renders verbatim ("XOF 1.2B") unit <UCUM code> - suffix a NON-monetary measure with the unit symbol ("18.4 °C"), in KPI tiles, axis titles and hovers. Checked CASE-SENSITIVELY against ~44 common units (UCUM distinguishes "m" from the "M" mega prefix); an off-table code is dropped. Mutually exclusive with currency aggregation sum|mean - declare how the measure combines across a group, overriding qsv\'s extensive-vs-intensive guess either way denominator {column, unit?, level?} - on a REGION-CODE column, name the column holding each region\'s population to add a RATE panel beside the raw-count region map. "unit" converts an area given in m2 or km2; "level" names the AREAL unit those values describe as a "geo." concept token, and a level naming a COARSER geography than the region column is refused The dictionary is also the ONLY source of the pipeline panel, declared in the DATASET-level "x-qsv" object as a "relationships" entry with "kind": "pipeline". Stages may be held in separate columns ("members", widest/upstream first) or as values of one category column ("stage_column" plus "stages", with an optional "value_column"). Declared order is authoritative and is never re-sorted by size: it draws as a funnel while the stage totals never grow, and as a BRIDGE when one outruns its predecessor. For the hint semantics, the pipeline encodings and worked JSON, see https://github.com/dathere/qsv/wiki/Visualization#data-dictionary Only affects `smart`.',
    },
    {
      displayName: 'Dictionary Context',
      name: 'dictionaryContext',
      type: 'string',
      default: '',
      description: 'Path to a file with extra context about the dataset (a glossary, README, data dictionary, PDF, etc.) forwarded to describegpt as --context-file when `--dictionary infer` generates the dictionary. Better context yields better role/concept/label tags, hence a better Data Schematic. Ignored unless `--dictionary infer` is used. Only affects `smart`.',
    },
    {
      displayName: 'Donut',
      name: 'donut',
      type: 'boolean',
      default: false,
      description: 'Render a pie chart as a donut (with a center hole).',
    },
    {
      displayName: 'Feature Id Key',
      name: 'featureIdKey',
      type: 'string',
      default: '',
      description: 'Property path in each GeoJSON feature whose value matches an entry in the locations column, or that labels each binned region (e.g. id, properties.fips). [default: id]',
    },
    {
      displayName: 'Feature Name Key',
      name: 'featureNameKey',
      type: 'string',
      default: '',
      description: 'GeoJSON property path whose value is shown as the human-readable region label in choropleth hover (e.g. properties.name). When omitted, common name keys are auto-detected; falls back to the feature id when absent.',
    },
    {
      displayName: 'Geocode',
      name: 'geocode',
      type: 'boolean',
      default: false,
      description: 'Derive the region codes with qsv\'s geocode engine (needs a build with the geocode feature): either reverse-geocode the lat/lon points, or forward-geocode the locations name column. Only valid with location modes iso3 or usa-states. `viz choropleth` also reuses --value, --agg, --style and the lat/lon options. Combined with `--geojson auto` it forward-geocodes a column of city/place NAMES to their containing US county FIPS and fetches those counties; lat/lon is REJECTED there, since reverse geocoding finds the nearest populated place, not the containing county. Each distinct name is a full engine lookup, so a column with thousands of them resolves slowly; unresolvable names are reported with a denser-index remedy.',
    },
    {
      displayName: 'Geocode Admin1',
      name: 'geocodeAdmin1',
      type: 'string',
      default: '',
      description: ' Column holding each row\'s expected admin1 (state/province), either as a qualified Geonames code (US.AL) or a bare subdivision code (AL) qualified by the country. Narrows a place-name search for names ambiguous on their own - there are dozens of US Springfields. Spelled-out names are REJECTED: admin1 names match by prefix, so `AL` would silently accept Alaska. Valid only with a locations name column, not with lat/lon points.',
    },
    {
      displayName: 'Geocode Country',
      name: 'geocodeCountry',
      type: 'string',
      default: '',
      description: ' Column holding each row\'s expected country, as an ISO-3166-1 alpha-2 code (e.g. US, GB, BR). Without it a place-name search spans every country, so US city names have resolved to Pakistan and a point near a border takes the nearest FOREIGN place. Rows whose match falls outside the hint are counted and reported, never silently dropped. Country NAMES are not accepted. With location-mode usa-states the country defaults to `us`. Applies to both geocode sources.',
    },
    {
      displayName: 'Geojson',
      name: 'geojson',
      type: 'string',
      default: '',
      description: 'Custom region polygons: a local file path, an http(s) URL to a GeoJSON FeatureCollection, or a shortcut name from the QSV_GEOJSON_SHORTCUTS env var (whose id sets --feature-id-key when you don\'t pass one). Use `auto` (or `census`) to fetch US boundaries from Census TIGERweb automatically; force a layer with census:county, census:zcta, census:tract or census:place (incorporated places AND CDPs), and pin a vintage with @<year>, e.g. census:county@2021. That path sets feature-id-key to properties.GEOID and caches under ~/.qsv-cache for 30 days (QSV_VIZ_BOUNDARY_CACHE_TTL_DAYS); it reads the codes from the --locations column, so in `viz smart` it needs a --dictionary naming the region column. A column of city/place NAMES also needs --geocode. Required for --map and for the geojson-id location mode; with --lat/--lon it instead enables point-in-polygon binning. See https://github.com/dathere/qsv/wiki/Visualization#census-boundaries',
    },
    {
      displayName: 'Grid Cols',
      name: 'gridCols',
      type: 'string',
      default: '',
      description: 'Number of columns in the Data Schematic grid for the per-column distribution panels. Overview panels (map/geo, correlation, time-series) always span the full width. [default: 2]',
    },
    {
      displayName: 'Heatmap Density',
      name: 'heatmapDensity',
      type: 'string',
      default: '',
      description: 'For the `viz smart` map panel: at or above <n> mappable points, draw the core as a density heatmap (DensityMap) instead of markers, keeping per-point hover. Defaults to 0 (disabled): dense point maps instead open as individual points with an in-map "Clusters/Points" toggle rather than aggregating into a static heat surface. Set a positive <n> to opt back in. [default: 0]',
    },
    {
      displayName: 'Height',
      name: 'height',
      type: 'string',
      default: '',
      description: 'Image height in pixels for static export. Default 600; for `smart`, auto-scaled to the number of panel rows.',
    },
    {
      displayName: 'Hierarchy Style',
      name: 'hierarchyStyle',
      type: 'string',
      default: '',
      description: 'For `smart`, the chart used for the categorical part-to-whole hierarchy panel (built when 2+ low-cardinality dimensions exist). One of: auto (default), treemap, sunburst, icicle. auto follows best practice - a treemap for a shallow 2-level hierarchy (accurate size comparison) and a sunburst for a deep 3-level one (parent/child structure); icicle is an opt-in level-aligned alternative. An explicit style also bypasses the association screen that would otherwise skip an uninformative panel. Only affects `smart`.',
    },
    {
      displayName: 'High',
      name: 'high',
      type: 'string',
      default: '',
      description: 'High-price column for candlestick/ohlc charts.',
    },
    {
      displayName: 'Language',
      name: 'language',
      type: 'string',
      default: '',
      description: 'Render the Data Schematic UI in this language. Accepts a BCP-47/ISO 639 code (es, spa) or an English language name (Spanish). Overrides the language detected in a data dictionary, and is also forwarded to describegpt when inferring one. Curated: en, es, fr, de, it, pt-BR, ja, zh-CN. [default: auto]',
    },
    {
      displayName: 'Lat',
      name: 'lat',
      type: 'string',
      default: '',
      description: 'Latitude column for a map (decimal degrees, -90 to 90).',
    },
    {
      displayName: 'Limit',
      name: 'limit',
      type: 'number',
      default: 10,
      description: 'Top-N categories per frequency bar chart. [default: 10]',
    },
    {
      displayName: 'Location Mode',
      name: 'locationMode',
      type: 'string',
      default: '',
      description: 'How --locations values are matched to regions. One of: iso3 (the default, ISO-3166-1 alpha-3 country codes), usa-states (2-letter US state codes), country-names (full country names), geojson-id (match a --geojson feature id). [default: iso3]',
    },
    {
      displayName: 'Locations',
      name: 'locations',
      type: 'string',
      default: '',
      description: 'Column holding the region key for each row (an ISO-3 country code, a 2-letter US state code, a country name, or a GeoJSON feature id, per --location-mode). With --geocode, this instead names a place-name column to forward-geocode into region codes.',
    },
    {
      displayName: 'Log Scale',
      name: 'logScale',
      type: 'string',
      default: '',
      description: 'Use a logarithmic y-axis for panels with a high dynamic range: frequency bar panels whose tallest bar dwarfs the rest (e.g. a large "(NULL)" or "Other (N)" bucket), so the small categories stay visible; and box panels of an all-positive column whose observed max/min ratio is huge. One of: auto, on, off. "auto" switches a panel to a log y-axis only when its dynamic range is high; "on" forces it on every frequency panel and every all-positive box panel; "off" keeps the linear axes. Only affects `smart`. [default: auto]',
    },
    {
      displayName: 'Lon',
      name: 'lon',
      type: 'string',
      default: '',
      description: 'Longitude column for a map (decimal degrees, -180 to 180).',
    },
    {
      displayName: 'Low',
      name: 'low',
      type: 'string',
      default: '',
      description: 'Low-price column for candlestick/ohlc charts.',
    },
    {
      displayName: 'Map',
      name: 'map',
      type: 'boolean',
      default: false,
      description: 'Render on a token-free MapLibre tile basemap (a ChoroplethMap) instead of the default projection basemap. Requires --geojson; feature-id-key defaults to id. Reuses --style for the basemap.',
    },
    {
      displayName: 'Max Charts',
      name: 'maxCharts',
      type: 'string',
      default: '',
      description: 'Maximum number of panels in the Data Schematic. 0 (the default) means auto: draw every eligible column (up to 64), for both HTML and static image export. Up to 8 cartesian panels render as one typed subplot grid; beyond 8, HTML switches to an inline-div grid and static export uses domain-positioned axes to fit one image. Set a positive <n> to cap the panel count instead; eligible columns beyond the cap are reported but not drawn. [default: 0]',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      description: 'When set, the first row will not be interpreted as headers. Columns can then only be selected by index.',
    },
    {
      displayName: 'No Nulls',
      name: 'noNulls',
      type: 'boolean',
      default: false,
      description: 'Omit the "(NULL)" bar (empty cells) from frequency bar charts. By default `viz smart` shows a "(NULL)" bar, like `qsv frequency`.',
    },
    {
      displayName: 'No Other',
      name: 'noOther',
      type: 'boolean',
      default: false,
      description: 'Omit the "Other (N)" aggregate bar from frequency bar charts. It collects the categories beyond --limit (N = how many distinct categories were rolled up) and is shown by default. When just ONE category is left over, it is charted under its own name instead of as an opaque "Other (1)" bar.',
    },
    {
      displayName: 'No Snap',
      name: 'noSnap',
      type: 'boolean',
      default: false,
      description: 'For point-in-polygon binning: do not snap at all - drop every point that falls outside every region. By default an outside point snaps to its nearest region when within the snap-distance limit (see --snap-max-dist). Applies to both `viz choropleth` and the `viz smart` GeoJSON choropleth panel; coverage is reported on stderr and beneath the map either way.',
    },
    {
      displayName: 'Ohlc Open',
      name: 'ohlcOpen',
      type: 'string',
      default: '',
      description: 'Open-price column for candlestick/ohlc charts.',
    },
    {
      displayName: 'Open',
      name: 'open',
      type: 'boolean',
      default: false,
      description: 'Open the generated chart in the default browser/viewer.',
    },
    {
      displayName: 'Photos',
      name: 'photos',
      type: 'boolean',
      default: false,
      description: 'For the `viz smart` map panel: when a column holds image URLs (detected from the stats cache), embed each point\'s image URL so that dwelling on a map point for 2 seconds opens that row\'s photo in a preview card beside the pointer (arrow keys page through a row\'s photos; Escape dismisses). OFF by default, and deliberately so: images load from whatever third-party host the DATA names, so enabling this makes everyone who opens the Data Schematic request those URLs directly, revealing their IP to that host. Nothing is fetched until a viewer dwells. HTML output only, tile-basemap map panel only, `smart` only.',
    },
    {
      displayName: 'Preview Threshold',
      name: 'previewThreshold',
      type: 'string',
      default: '',
      description: 'Row threshold for the interactive data viewer drawer of HTML dashboards. Next to the row count in the metadata table, an "(Explore)" link opens the underlying table in a bottom drawer (with global, per-column and builder search) when the dataset has at most <n> rows and ALL rows are embedded; above <n>, only the first <n> rows are embedded and the link reads "(Preview)". Embedded rows grow the HTML file, and browser memory, in proportion to rows x columns. Set to 0 to disable the data viewer entirely (no link, no embedded data). `smart` HTML only. [default: 50000]',
    },
    {
      displayName: 'Projection',
      name: 'projection',
      type: 'string',
      default: '',
      description: 'Map projection for `viz geo`. One of: natural-earth (the default), mercator, orthographic, equirectangular, albers-usa, robinson, winkel-tripel, mollweide, hammer, azimuthal-equal-area. `viz geo` also reuses the lat, lon, text, color, size and series options from `map`. [default: natural-earth]',
    },
    {
      displayName: 'Rangeslider',
      name: 'rangeslider',
      type: 'boolean',
      default: false,
      description: 'Add a draggable range-slider (a navigator strip) under the x-axis for panning and zooming. Best for an ordered x-axis (time series, line, candlestick/ohlc). Applies to cartesian charts (bar/line/scatter/histogram/box/violin/candlestick/ ohlc); off by default.',
    },
    {
      displayName: 'Region State',
      name: 'regionState',
      type: 'string',
      default: '',
      description: 'Column holding each row\'s state, for a --locations column of county NAMES rather than codes. Accepts a USPS code (PA), a 2-digit state FIPS (42) or the full state name (Pennsylvania). 422 county names are carried by more than one county - Washington County exists in 30 states - so without this, a column containing any of them is refused rather than resolved to an arbitrary state. `viz choropleth --geojson auto` only; in `viz smart` the state column comes from the data dictionary. A county FIPS column needs none of this.',
    },
    {
      displayName: 'Sankey Value Order',
      name: 'sankeyValueOrder',
      type: 'boolean',
      default: false,
      description: 'Order sankey nodes by total flow (largest at the top of each column) instead of plotly\'s default crossing-minimizing "snap" order. Either way the chart carries an on-screen "node order" button to flip between the two layouts, and link ribbons are always colored by their source node. Applies to the `sankey` chart AND the `smart` Data Schematic flow panel.',
    },
    {
      displayName: 'Scale',
      name: 'scale',
      type: 'number',
      default: 1.0,
      description: 'Image scale factor (static export). [default: 1.0]',
    },
    {
      displayName: 'Series',
      name: 'series',
      type: 'string',
      default: '',
      description: 'Column to split into multiple series (one trace per distinct value). Applies to bar, line, scatter, scatter3d, radar, map and geo.',
    },
    {
      displayName: 'Size',
      name: 'size',
      type: 'string',
      default: '',
      description: 'For scatter/scatter3d/map/geo: a numeric column to encode as marker size, producing a bubble chart (values are rescaled to a readable pixel range). Cannot be combined with --series, EXCEPT on an animated scatter (see the --slider option), where the --series column names the entity and this column is the third data variable. In map density mode, this column is the heatmap weight.',
    },
    {
      displayName: 'Slider',
      name: 'slider',
      type: 'string',
      default: '',
      description: 'Animate the chart over a column: each distinct value of the given column becomes an animation frame, with a Play/Pause button and a slider to scrub through the frames (Gapminder- style). Supported for bar/line/scatter and geo, and may be split into animated traces with --series. NOT supported for `viz map`, whose MapLibre basemap can\'t animate - use `viz geo` for an animated point map. A slider column that parses as dates is auto-bucketed to a readable number of frames; any other column frames on its distinct values. Axis ranges are pinned across frames so nothing jumps. On `viz scatter`, a slider with --series AND --size builds a Gapminder BUBBLE ANIMATION: --series is the entity, --x/--y the measure pair and --size the third variable (bubble area). Each entity x frame cell collapses to one bubble via --agg (mean by default), scaled once across all frames so sizes stay comparable. For `smart`, this instead takes auto, on or off, controlling whether ONE animated relationship-over-time panel is added - a drifting numeric pair, an animated geo map of dated points, or a Gapminder entity-bubble chart (at most one; the bubble wins, then the geo map, then the pair). auto requires a strong signal (a date column and enough time buckets); on lowers the bar to two buckets but still requires a genuinely drifting relationship; off never does.',
    },
    {
      displayName: 'Slider Cumulative',
      name: 'sliderCumulative',
      type: 'boolean',
      default: false,
      description: 'Accumulate rows across frames: frame N includes every row whose --slider value is at or below the Nth value, so the animation builds up cumulatively instead of replacing each step. Applies to bar/line/scatter and geo. On a bubble animation there is only ever one bubble per entity per frame, so nothing piles up on screen; instead each bubble shows a RUNNING aggregate over all frames up to that point, and so drifts less and less as the animation plays.',
    },
    {
      displayName: 'Slider Speed',
      name: 'sliderSpeed',
      type: 'string',
      default: '',
      description: 'Milliseconds each animation frame is shown while playing. [default: 800]',
    },
    {
      displayName: 'Smarter',
      name: 'smarter',
      type: 'boolean',
      default: false,
      description: 'Before building the Data Schematic, run `qsv moarstats --advanced` to enrich the stats cache with distribution-shape statistics (bimodality, entropy, skewness, outlier share, Gini). This unlocks histograms for bimodal columns, frequency bars for concentrated high-cardinality columns, skew/outlier hints on box panels, and Lorenz curves for the most unequal additive measures. Costs one extra pass and writes <stem>.stats.csv, its sidecars and an .idx index. On geocode-enabled builds it also adds the US FIPS code to map hovers. Applied only with default parsing; an input using the --no-headers or --delimiter flags falls back to the standard Data Schematic. Only affects `smart`.',
    },
    {
      displayName: 'Snap Max Dist',
      name: 'snapMaxDist',
      type: 'string',
      default: '',
      description: 'For point-in-polygon binning: the farthest (in km, an equirectangular approximation) an outside point may snap to a region\'s boundary; points with no region within it are dropped. When omitted the cap is AUTO-DERIVED from the GeoJSON\'s median region size and the lat/lon coordinate precision, clamped to 0.1-100 km; a fixed 10 km is used only when neither signal is available. The coverage notes state the cap and how it was derived. Pass a large value for effectively unbounded snapping; cannot be combined with --no-snap. See https://github.com/dathere/qsv/wiki/Visualization#point-in-polygon',
    },
    {
      displayName: 'Source',
      name: 'source',
      type: 'string',
      default: '',
      description: 'Source node column for a sankey diagram.',
    },
    {
      displayName: 'Style',
      name: 'style',
      type: 'string',
      default: '',
      description: 'MapLibre basemap style (all render without an access token): open-street-map (the default), carto-positron, carto-darkmatter, carto-voyager, white-bg, basic, streets, outdoors, light, dark, satellite, satellite-streets. The three carto styles also have label-free "-nolabels" variants (e.g. carto-positron-nolabels) that keep basemap place names from competing with a dense data overlay. [default: open-street-map]',
    },
    {
      displayName: 'Target',
      name: 'target',
      type: 'string',
      default: '',
      description: 'Target node column for a sankey diagram.',
    },
    {
      displayName: 'Text',
      name: 'text',
      type: 'string',
      default: '',
      description: 'Column whose value labels each point on hover.',
    },
    {
      displayName: 'Theme',
      name: 'theme',
      type: 'string',
      default: '',
      description: 'Plotly theme that drives the chart\'s overall look (background, fonts, axis styling). One of: default, plotly_white, plotly_dark, seaborn, seaborn_whitegrid, seaborn_dark, matplotlib, plotnine (case-insensitive; hyphens accepted). When omitted, qsv\'s built-in look is used. Applies to all chart types, including `smart`.',
    },
    {
      displayName: 'Title',
      name: 'title',
      type: 'string',
      default: '',
      description: 'Chart title.',
    },
    {
      displayName: 'Tour Audience',
      name: 'tourAudience',
      type: 'string',
      default: '',
      description: 'Who the guided Tour should talk to. Forwarded to describegpt when `--dictionary infer` generates the dictionary, so the inferred dictionary carries an "x-qsv.tour" narration written for that audience (e.g. "Explain like I\'m 10" - the default - or "a board of directors", "data journalists"). The audience shapes ONLY the tour prose; field labels and descriptions keep their normal register. Ignored unless a FRESH `--dictionary infer` actually runs: when an existing <stem>.schema.json sidecar is reused, delete it (or set QSV_VIZ_DICT_FRESH=1) to re-infer with a new audience. Only affects `smart`.',
    },
    {
      displayName: 'Tour Steps',
      name: 'tourSteps',
      type: 'string',
      default: '',
      description: 'How many chart panels the guided tour of a `smart` HTML dashboard spotlights. This budgets the per-panel steps only - the introduction, the Data Dictionary drawer chapter, the data viewer chapter and the conclusion are always included. Set to 0 to suppress the tour entirely - no tour, no "Tour" button, no first-visit hint beacons. Left at its default (8) the budget is SOFT: an all-overview dashboard gains one extra step so a frequency distribution is always spotlighted. An explicit value makes it a HARD cap, substituting rather than adding. A dictionary\'s dataset-level "x-qsv" "tour" object can refine the narration - see https://github.com/dathere/qsv/wiki/Visualization#guided-tour `smart` HTML only.',
    },
    {
      displayName: 'Value',
      name: 'value',
      type: 'string',
      default: '',
      description: 'Flow value column for a sankey diagram. When omitted, each row counts as a flow of 1. For treemap/sunburst/icicle: a numeric measure summed per sector (when omitted, each row counts as 1).',
    },
    {
      displayName: 'Violin',
      name: 'violin',
      type: 'string',
      default: '',
      description: 'Draw distribution panels as violins (a box plot wrapped in a KDE density silhouette - a strict superset of a plain box) instead of boxes. One of: auto, on, off. "auto" draws a violin for every continuous column EXCEPT those on a log value axis (the KDE is estimated in linear space, which a log axis would distort) and those with too few distinct values or observations for a meaningful KDE; both keep an honest box. "on" also violins those; "off" never draws violins. KDEs are clamped to each column\'s observed range, so a bounded or discrete measure can\'t show density past a natural limit. Above a size threshold a violin is drawn from a deterministic strided sample, carries no point overlay and is titled "(sampled)"; that budget scales with QSV_VIZ_MAX_POINTS. For the thresholds and how this interacts with the box-points option, see https://github.com/dathere/qsv/wiki/Visualization#distribution-panels Only affects `smart`. [default: auto]',
    },
    {
      displayName: 'Width',
      name: 'width',
      type: 'string',
      default: '',
      description: 'Image width in pixels for static export. Default 1000; for `smart`, auto-scaled to the grid\'s column count.',
    },
    {
      displayName: 'X',
      name: 'x',
      type: 'string',
      default: '',
      description: 'Column for the x-axis / category / bin / group.',
    },
    {
      displayName: 'X Title',
      name: 'xTitle',
      type: 'string',
      default: '',
      description: 'X-axis title. (defaults to the x column name)',
    },
    {
      displayName: 'Y',
      name: 'y',
      type: 'string',
      default: '',
      description: 'Column for the y-axis / value.',
    },
    {
      displayName: 'Y Range',
      name: 'yRange',
      type: 'string',
      default: '',
      description: 'Fix the y-axis to an explicit min:max range (two colon- separated numbers, e.g. -10:55) instead of autoscaling; points outside are clipped from view. Handy when one extreme outlier squashes the rest. Applies to cartesian charts (bar/line/scatter/histogram/box/violin/heatmap/ contour). Pass a negative min with `=`: --y-range=-10:55.',
    },
    {
      displayName: 'Y Title',
      name: 'yTitle',
      type: 'string',
      default: '',
      description: 'Y-axis title. (defaults to the y column name)',
    },
    {
      displayName: 'Z',
      name: 'z',
      type: 'string',
      default: '',
      description: 'The z column: a heatmap pivot value (with --x and --y), or the third numeric axis for scatter3d.',
    },
    ],
  },
];
