import type { INodeProperties } from 'n8n-workflow';

export const VizDescription: INodeProperties[] = [
  {
    displayName: 'Input CSV File Path',
    name: 'inputPath',
    type: 'string',
    required: true,
    default: '',
    description: 'Path to input CSV file on disk or host filesystem',
    displayOptions: {
      show: {
        operation: ['viz'],
      },
    },
  },

  {
    displayName: 'Output File Path',
    name: 'outputPath',
    type: 'string',
    default: '',
    description: 'Optional path to write output file directly to disk (if omitted, results are returned in node output)',
    displayOptions: {
      show: {
        operation: ['viz'],
      },
    },
  },
  {
    displayName: 'Additional Flags',
    name: 'additionalArgs',
    type: 'string',
    default: '',
    description: 'Additional raw command line arguments to pass to qsv viz (Docs: https://github.com/dathere/qsv/blob/master/docs/help/viz.md)',
    displayOptions: {
      show: {
        operation: ['viz'],
      },
    },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        operation: ['viz'],
      },
    },
    options: [
    {
      displayName: 'Agg',
      name: 'agg',
      type: 'string',
      default: '',
      description: 'For bar/line, aggregate the y values when the x value repeats. One of: sum, mean, count, min, max. For treemap/sunburst/icicle, only additive aggregations apply: count (default) or sum (requires --value). For choropleth, how rows sharing a region are combined: sum when --value is given, else count. Pass mean for an intensive measure (a density, rate, index or per-capita figure) — summing those is meaningless, and the count/sum hover adds a "share of total" line that would be too. For a bubble animation (see --slider), collapses each entity x frame cell to a single bubble; defaults to mean (the cell centroid). count is rejected there, since a row count is not a position.',
    },
    {
      displayName: 'Annotation',
      name: 'annotation',
      type: 'string',
      default: '',
      description: 'Caption note drawn at the bottom of the plot (e.g. to note a clipped outlier). Cartesian charts only.',
    },
    {
      displayName: 'Bins',
      name: 'bins',
      type: 'string',
      default: '',
      description: 'Number of bins. For histogram: bins along the x-axis (default: auto). For contour: the per-axis resolution of the density grid (default: 20).',
    },
    {
      displayName: 'Bivariate',
      name: 'bivariate',
      type: 'boolean',
      default: false,
      description: 'Add two pairwise-association overview panels driven by `qsv moarstats --bivariate`: a normalized mutual information (NMI) heatmap over every column pair (works for numeric AND categorical columns, unlike the Pearson-only correlation heatmap), plus a ranked "top relationships" bar of the strongest pairs when there are more than 8 chartable columns. The ranked bar (not the heatmap, which still shows every pair) requires a pair\'s co-occurring row count to be at least 10% of the best-supported pair\'s, so a technically-perfect NMI from two sparsely-populated columns that only ever co-occur in a narrow row slice can\'t crowd out a more broadly meaningful association; each bar\'s hover shows its co-occurring row count. A numeric pair whose Spearman rank correlation diverges sharply from its Pearson correlation is flagged "nonlinear" in the hover. Identifier / PII / free-text columns (per --dictionary) and map lat/lon columns are excluded. This automatically turns on --smarter, and when --dictionary isn\'t already set, also turns on --dictionary infer (so the PII/identifier exclusion has semantic signal to work with). Capped at 50 columns (1,225 pairs); wider datasets skip these panels with a warning (run `qsv moarstats --bivariate` directly for the full pairwise output). Only affects `smart`.',
    },
    {
      displayName: 'Box Points',
      name: 'boxPoints',
      type: 'string',
      default: '',
      description: 'Which sample points to draw alongside a box. Reading the raw values lets plotly render true Tukey whiskers (1.5*IQR) with the points beyond the fences as outliers. One of: outliers (only the outliers), all (every point, jittered), suspected (mark suspected outliers), none (no points, but still real Tukey whiskers). For `viz box` the default is outliers. For `viz smart` this flag OVERRIDES the default size-based heuristic, which overlays all points on a column with few non-null values (<=1,000) — unless the Data Schematic has more than 8 panels, where all-points cells turn to noise, so the overlay drops to outliers-only — and only the outliers for a medium one (<=10,000 values). Above that, a column that HAS outliers shows them as points on a precomputed quartile box (a single pass collects only the out-of-fence values, capped); a column with no outliers stays a fast cache-only quartile summary with no data re-scan. An explicit mode is applied to every box panel (one batched pass to read the values), except `none`, which keeps the cache-only box for BOX panels. A smart violin panel still renders under `none`, just with no sample points — its KDE needs the values anyway; combine with the violin option\'s `off` mode for the cache-only escape hatch. The same modes also pick the sample points drawn beside a violin, for `viz violin` and for the violin panels of `viz smart` — though a smart violin panel skips the size-based `all` upgrade (its KDE silhouette already shows the distribution) and overlays only the outliers unless an explicit mode is given.',
    },
    {
      displayName: 'Close',
      name: 'close',
      type: 'string',
      default: '',
      description: 'Close-price column for candlestick/ohlc charts.',
    },
    {
      displayName: 'Cluster',
      name: 'cluster',
      type: 'string',
      default: '',
      description: 'For the `viz smart` map panel: whether to offer an in-map "Clusters/Points" toggle that collapses dense points into native MapLibre count bubbles (which expand back into individual, hoverable points on zoom-in). Hovering a bubble shows its point count; clicking it zooms to where that cluster breaks apart. The map always OPENS as individual points; the toggle switches clustering on. One of: auto, on, off. "auto" (the default) offers the toggle for a plain-marker core (no density heatmap, no bubble-size measure) once it reaches 1,000 points. "on" offers it whenever the core draws as markers, regardless of point count or a bubble-size measure. "off" omits the toggle, so points are always drawn plainly. Only affects `smart`. [default: auto]',
    },
    {
      displayName: 'Color',
      name: 'color',
      type: 'string',
      default: '',
      description: 'For scatter/scatter3d/map/geo: a numeric column to encode as marker color (a continuous colorscale with a colorbar). For categorical coloring, use the --series option instead. Cannot be combined with --series. In map density mode, this column is the heatmap weight.',
    },
    {
      displayName: 'Color Scale',
      name: 'colorScale',
      type: 'string',
      default: '',
      description: 'Colorscale for the region fill. One of: viridis (the default), cividis, greys, greens, blues, reds, ylgnbu, ylorrd, bluered, rdbu, portland, electric, jet, hot, blackbody, earth, picnic, rainbow. [default: viridis]',
    },
    {
      displayName: 'Cols',
      name: 'cols',
      type: 'string',
      default: '',
      description: 'Columns to use. For heatmap: numeric columns for the correlation matrix (default: all numeric). For radar: the numeric axes to plot. For treemap/sunburst/icicle: the categorical dimensions that form the hierarchy levels, outermost first (e.g. region,category,subcategory). For splom: the numeric columns to cross-plot (default: all numeric). For parcats: the categorical dimensions to flow across (best with 3-4).',
    },
    {
      displayName: 'Dataset Pid',
      name: 'datasetPid',
      type: 'string',
      default: '',
      description: 'A persistent identifier (PID) for the dataset - typically a full URL such as a DOI (https://doi.org/10.1234/abc) or other citable link. When set, a "PID" row is added to the metadata table at the top of the Data Schematic. http(s) and mailto values become a clickable link (opened in a new tab); any other scheme is shown as plain text rather than linked. HTML output only. Only affects `smart`.',
    },
    {
      displayName: 'Delimiter',
      name: 'delimiter',
      type: 'string',
      default: '',
      description: 'The field delimiter for reading CSV data. Must be a single character. (default: ,)',
    },
    {
      displayName: 'Denominator',
      name: 'denominator',
      type: 'string',
      default: '',
      description: 'Column holding each region\'s DENOMINATOR, as an alternative to reading it from the GeoJSON. The value must be constant within a region (it describes the region, not the row). `viz choropleth` only, and only with a --locations region column (not with --geocode or lat/lon binning). Valid with the default count aggregation and with --agg sum; the other aggregations are already intensive, so a denominator is rejected. In `viz smart`, declare the column in the data dictionary instead, via x-qsv.denominator (see --dictionary). The value `census` is RESERVED (a column of that name cannot be used): it fetches US population from the Census Data API and divides by it, giving a per-capita rate with nothing supplied. It works on `viz smart` too, being a source rather than a column. Region codes must be 5-digit county FIPS, 2-digit state FIPS, or 2-letter state codes. The newest published ACS 5-year release is used; append @<year> to pin one, e.g. `census@2019`. The release is always stated beneath the map, since a rate means something different against a different one. Regions the release does not cover are excluded and reported. Results are cached under ~/.qsv-cache, so a repeated command makes no network request; freshness defaults to 30 days, overridable with QSV_VIZ_DENOMINATOR_CACHE_TTL_DAYS. REQUIRES a Census API key in QSV_CENSUS_API_KEY - request a free one at https://api.census.gov/data/key_signup.html. (The Bureau redirects unkeyed requests to a "Missing Key" page rather than refusing them, so qsv asks for the key up front.)',
    },
    {
      displayName: 'Denominator Key',
      name: 'denominatorKey',
      type: 'string',
      default: '',
      description: 'GeoJSON property path holding each region\'s DENOMINATOR (e.g. properties.POP2020), using the same addressing as the --feature-id-key flag. Turns a raw-count region map into a RATE map: without it, a region map of row counts redraws where the people are (a populous region tallies more rows), so the biggest region wins on size, not on intensity. In `viz choropleth` the map itself becomes the rate; in `viz smart` a rate panel is added BESIDE the count panel. Regions whose denominator is missing or non-positive are excluded from the rate and reported. The per-region scale (per 1,000 / 10,000 / 100,000 / 1,000,000 / 1,000,000,000) is chosen automatically.',
    },
    {
      displayName: 'Denominator Unit',
      name: 'denominatorUnit',
      type: 'string',
      default: '',
      description: ' Unit the denominator values are IN, so qsv can convert them and name them. Without this, an area denominator is divided in its raw unit and labelled with its raw field name — real boundary files carry land area in square METRES, which reads as "per 100,000 AREALAND" at approximately zero everywhere. One of: m2, km2 (also spelled m², km², sqm, sqkm). Values in m2 are converted to km², so the map reads "per km²". Never inferred from a field name; boundaries fetched by `--geojson auto` declare their own units and need no flag.',
    },
    {
      displayName: 'Density',
      name: 'density',
      type: 'boolean',
      default: false,
      description: 'Render a density heatmap (DensityMap) instead of points. Weighted by the --color or --size column when given, else by a uniform weight. Cannot be combined with --series.',
    },
    {
      displayName: 'Dict Info',
      name: 'dictInfo',
      type: 'boolean',
      default: false,
      description: 'When a usable Data Dictionary is available (per --dictionary), add a "Data Dictionary" link beneath the Data Schematic title and an info icon on each panel title: hovering shows that column\'s dictionary description; clicking opens a human-friendly rendering of the dictionary in a side drawer NEXT TO the plots (embedded in the Data Schematic file - no extra file is written), scrolled to and highlighting that column\'s entry. The drawer is open by default on load and can be dismissed with its close button or Esc. The dictionary page carries a role-tinted table of contents and per-column "View chart" links back to the panels, plus a row of download buttons: the dictionary itself as JSON Schema, the frequency counts the Data Schematic actually charted, and every generated sidecar this run read (the stats cache and its metadata, the frequency cache when it was reused, and the bivariate stats CSV when freshly written). A sidecar qsv wrote but viz never read - the human-readable <stem>.stats.csv - is NOT offered, since nothing can show it describes the same computation the Data Schematic used. Every file is BUNDLED into the HTML, so anyone you send the Data Schematic to can download them with no access to your machine; absolute local paths are stripped from the embedded metadata so sharing a Data Schematic doesn\'t disclose your directory layout. Sidecars over 4 MB are skipped with a note. The drawer also explains what the Data Schematic LEFT OUT, so the omissions travel with the file instead of scrolling past in the terminal: a column `viz smart` did not chart carries a "not charted" note giving the reason it reported (an identifier, all-empty, high-cardinality text, a duplicate of a sibling column that IS charted, or simply capped by --max-charts), and is dimmed in the table of contents. A skipped column the dictionary never described still gets an entry, so nothing disappears silently. Panels qsv declined to draw - a hierarchy panel whose dimensions are statistically independent, a refused funnel, an association panel - are listed together under "Panels not drawn". The drawer\'s popout button opens the same document in its own browser tab instead (needs a browser that allows user-initiated pop-ups). HTML output only; ignored with a note when no dictionary is available or when exporting an image. Only affects `smart`.',
    },
    {
      displayName: 'Dictionary',
      name: 'dictionary',
      type: 'string',
      default: '',
      description: 'Use a describegpt Data Dictionary to guide panel selection from each field\'s semantic role/concept (falling back to its content type) instead of relying on column statistics alone: dimensions and numeric codes (ward, census_tract, zone) become bars, measures get box/correlation/trend panels, date/datetime columns feed the time-series panel (not noisy frequency bars), identifiers / PII / free-text are skipped, and lat/lon feed the map. Field labels are shown as panel subtitles beneath the field-name titles. Columns the dictionary cannot classify still use the statistical heuristic. <src> is one of: "infer" to run describegpt on the input now (with description, infer-content-type, two-pass and jsonschema output; requires an LLM configured) and use its output; or a path to an existing describegpt dictionary file (jsonschema or json). With "infer", the generated dictionary is saved beside the input as <stem>.schema.json so you can fine-tune it; if that file already exists, it is reused as-is (skipping the LLM) - edit it to fine-tune, or delete it to force a fresh re-infer. An inferred dictionary is a DRAFT, not an oracle. It comes from an LLM, so re-inferring the SAME data can assign a column a different role or concept - and role drives panel selection, so a re-infer can hand you a structurally different Data Schematic. The saved sidecar is therefore the artifact of record: review it, correct what the model got wrong, and keep it beside the data (commit it, if the data is versioned). Every later run then reuses it and renders reproducibly - only deleting it, or setting QSV_VIZ_DICT_FRESH=1, re-rolls the model. Curating that sidecar once is the human-in-the-loop half of the Data Schematic; qsv re-verifies the hints below on read, so a hand-edit can correct the model but cannot smuggle in a hint the data does not support. Set QSV_VIZ_DICT_FRESH=1 to ignore an existing sidecar and bypass describegpt\'s completion cache, forcing a genuinely fresh inference that overwrites the sidecar on success. Generation/read failures soft-fall back to the stats-only Data Schematic. The dictionary also drives the KPI overview row via four optional per-field hints in a property\'s "x-qsv" object (edit them in the saved schema to fine-tune). A "gauge_range" of [min, max] on a continuous numeric measure renders its KPI tile as a GAUGE on that canonical scale (e.g. [0,1] for a ratio, [0,100] for a percent); qsv keeps it only when the observed data lies within the range, so a mis-scaled range can\'t draw a misleading dial, and "infer" emits it for canonical-scale measures. A "target" number on a measure renders a "vs target" DELTA against that goal (value minus target) - a GOAL you supply, never a fabricated prior-period baseline, so "infer" never emits it; hand-author it. A "currency" ISO-4217 alpha-3 code (e.g. "USD", "EUR") on a monetary measure prefixes its KPI tile with that currency\'s symbol ($192B) and names the currency in the panel subtitle; an unrecognized code renders verbatim ("XOF 1.2B"). "infer" emits it for money columns, which it also tags with the "measure.money" concept. An "aggregation" of "sum" or "mean" on a numeric measure declares how that column combines across a group, and OVERRIDES qsv\'s own extensive-vs-intensive guess in both directions. Use it when a measure does not add up - a unit price, a temperature, a rating - or when a measure whose NAME reads non-additive genuinely does sum. qsv\'s guess reads column names and is English-first, so this hint is the reliable way to state it, in any language. "infer" emits it for numeric measures. A "denominator" of {"column": "<name>"} on a REGION-CODE column (a zip, county, state or fips column) names the column holding each region\'s population - or households, area, fleet size - and adds a RATE panel beside the region map\'s raw-count panel. Without one, a region map colored by row counts mostly redraws where the people are, so the busiest region wins on size rather than on intensity; the count panel says so in its subtitle. The named column must hold the same value on every row of a region (it describes the region, not the row); when it does not, qsv notes why and charts raw counts only. Add a "unit" beside the "column" - {"column": "land_area", "unit": "m2"} - when the values are an area in square metres, so qsv converts them and names the rate "per km2" instead of dividing by metres and printing the raw column name. Prefer the denominator-key flag when the boundary file already carries the figure. Note that on ENGLISH pages large numbers use the financial convention (1e9 reads "1B", not the SI "1G") consistently across KPI tiles, bar value labels and axis ticks. Other languages keep the SI prefixes. The dictionary is also the ONLY source of the pipeline panel (drawn as a funnel while the stage TOTALS never increase, otherwise as a bridge; row-wise containment is measured & disclosed in the subtitle, but does not decide the form), declared in the dataset-level "x-qsv" object as a "relationships" entry with "kind": "pipeline". Two encodings, both hand-editable: stages as COLUMNS - "members" lists the stage columns in process order, WIDEST/UPSTREAM FIRST (note this is the opposite direction from a "kind":"ordered" group, which ascends), e.g. {"kind":"pipeline", "members":["planned_amt","committed_amt","spent_amt"]} stages as ROW VALUES - "stage_column" names the category column, "stages" lists its values in process order, and an optional "value_column" names the measure to sum per stage (omit it to count rows), e.g. {"kind":"pipeline","members":["stage","revenue"], "stage_column":"stage", "stages":["Impression","Click","Lead","Conversion"], "value_column":"revenue"} Declared order is authoritative and is never re-sorted by size, so a stage that outruns its predecessor stays visible instead of being quietly reordered away - it switches the panel to a bridge rather than drawing a funnel that widens. A declaration naming a missing column, or a stage that is an average/rate rather than a summable amount, is skipped with a note rather than erroring. Only affects `smart`.',
    },
    {
      displayName: 'Dictionary Context',
      name: 'dictionaryContext',
      type: 'string',
      default: '',
      description: 'Path to a file with extra context about the dataset (a glossary, README, data dictionary, PDF, etc.) forwarded to describegpt as --context-file when `--dictionary infer` generates the dictionary. Better context yields better role/concept/label/grain tags, hence a better Data Schematic. Ignored unless `--dictionary infer` is used (it does not apply when reading an existing dictionary file). Only affects `smart`.',
    },
    {
      displayName: 'Donut',
      name: 'donut',
      type: 'boolean',
      default: false,
      description: 'Render a pie chart as a donut (with a center hole).',
    },
    {
      displayName: 'Feature Id Key',
      name: 'featureIdKey',
      type: 'string',
      default: '',
      description: 'Property path in each GeoJSON feature whose value matches an entry in the locations column, or that labels each binned region (e.g. id, properties.fips). [default: id]',
    },
    {
      displayName: 'Feature Name Key',
      name: 'featureNameKey',
      type: 'string',
      default: '',
      description: 'GeoJSON property path whose value is shown as the human-readable region label in choropleth hover (e.g. properties.name). When omitted, common name keys are auto-detected; falls back to the feature id when absent.',
    },
    {
      displayName: 'Geocode',
      name: 'geocode',
      type: 'boolean',
      default: false,
      description: 'Derive the region codes by reusing qsv\'s geocode engine (needs a build with the geocode feature). Either reverse-geocode the lat/lon points, or forward-geocode the locations name column. Only valid with location modes iso3 or usa-states. `viz choropleth` also reuses --value, --agg, --style and the lat/lon options.',
    },
    {
      displayName: 'Geocode Admin1',
      name: 'geocodeAdmin1',
      type: 'string',
      default: '',
      description: ' Column holding each row\'s expected admin1 (state/province), either as a qualified Geonames code (US.AL) or a bare subdivision code (AL) qualified by the country. Narrows a place-name search within a country, for names that are ambiguous on their own (there are dozens of US Springfields). Spelled-out names are rejected: admin1 names are matched by prefix, so `AL` would silently accept Alaska. Valid only with a locations name column, not with lat/lon points.',
    },
    {
      displayName: 'Geocode Country',
      name: 'geocodeCountry',
      type: 'string',
      default: '',
      description: ' Column holding each row\'s expected country, as an ISO-3166-1 alpha-2 code (e.g. US, GB, BR). Without it a place-name search spans every country, so US city names have resolved to Pakistan and the UK, and a point near a border takes the nearest FOREIGN place. Rows whose match falls outside the hint are counted and reported, never silently dropped. Country NAMES are not accepted, only codes. With location-mode usa-states the country defaults to `us`, so no hint is needed there. Applies to both geocode sources.',
    },
    {
      displayName: 'Geojson',
      name: 'geojson',
      type: 'string',
      default: '',
      description: 'Custom region polygons as a local file path or an http(s) URL to a GeoJSON FeatureCollection. May also be a shortcut name defined in the QSV_GEOJSON_SHORTCUTS env var (a JSON map of name to {path, id}); the shortcut\'s id sets --feature-id-key when you don\'t pass one. The source is validated up front. Use `auto` (or `census`) to fetch US county, ZIP Code Tabulation Area, census tract or place boundaries from the Census TIGERweb service automatically. County FIPS and ZIP codes are both 5-digit, so qsv probes the layers and picks whichever your codes resolve against, reporting them when it cannot tell; force one with `census:county`, `census:zcta`, `census:tract` or `census:place`. Sets the feature-id-key to properties.GEOID. It needs to know which column holds the region codes: `viz choropleth` reads the column named by --locations, while `viz smart` takes the region column its data dictionary names — so there it needs a --dictionary. An existing local file named `auto` takes precedence over the keyword. Boundaries are re-drawn between vintages (Connecticut replaced its 8 counties with 9 planning regions in the 2022 vintages, sharing no GEOID), so append @<year> to pin one, e.g. `census:county@2021`. When nothing matches the newest vintage, qsv probes older ones and names the vintage that does match. Fetched boundaries are cached under ~/.qsv-cache, so a repeated command makes no network request at all; the cache path can be passed back as an explicit --geojson for an archival run. Freshness defaults to 30 days, overridable with QSV_VIZ_BOUNDARY_CACHE_TTL_DAYS. Required for --map, and for the geojson-id location mode. Also enables point-in-polygon binning: with --lat/--lon (and without --geocode), each row\'s point is binned into the region whose polygon contains it (exact, no geocoding) and colored by --value/--agg or counts. In `viz smart`, it also overlays the region boundaries on the map, labelling each with its --feature-name-key value (falling back to its id) — as on-map text on the projection/static map, or as a centroid hover marker on the interactive tile map (which culls on-map text). Labels are omitted above 60 regions.',
    },
    {
      displayName: 'Grid Cols',
      name: 'gridCols',
      type: 'string',
      default: '',
      description: 'Number of columns in the Data Schematic grid for the per-column distribution panels. Overview panels (map/geo, correlation, time-series) always span the full width. [default: 2]',
    },
    {
      displayName: 'Heatmap Density',
      name: 'heatmapDensity',
      type: 'string',
      default: '',
      description: 'For the `viz smart` map panel: at or above <n> mappable points, draw the core as a density heatmap (DensityMap) instead of markers. The heatmap keeps per-point hover (coordinates, plus the point\'s label). Defaults to 0 (disabled): dense point maps instead open as individual points with an in-map "Clusters/Points" toggle (collapse the dense areas into interactive count bubbles on demand) rather than aggregating into a static heat surface. Set a positive <n> to opt back into the heatmap above that point count. [default: 0]',
    },
    {
      displayName: 'Height',
      name: 'height',
      type: 'string',
      default: '',
      description: 'Image height in pixels for static export. Default 600; for `smart`, auto-scaled to the number of panel rows.',
    },
    {
      displayName: 'Hierarchy Style',
      name: 'hierarchyStyle',
      type: 'string',
      default: '',
      description: 'For `smart`, the chart used for the categorical part-to-whole hierarchy panel (built when 2+ low-cardinality dimensions exist). One of: auto (default), treemap, sunburst, icicle. auto follows best practice — a treemap for a shallow 2-level hierarchy (accurate size comparison) and a sunburst for a deep 3-level one (parent child structure); icicle is an opt-in level-aligned alternative. Only affects `smart`.',
    },
    {
      displayName: 'High',
      name: 'high',
      type: 'string',
      default: '',
      description: 'High-price column for candlestick/ohlc charts.',
    },
    {
      displayName: 'Language',
      name: 'language',
      type: 'string',
      default: '',
      description: 'Render the Data Schematic UI in this language. Accepts a BCP-47/ISO 639 code (es, spa) or an English language name (Spanish). Overrides the language detected in a data dictionary, and is also forwarded to describegpt when inferring one. Curated: en, es, fr, de, it, pt-BR, ja, zh-CN. [default: auto]',
    },
    {
      displayName: 'Lat',
      name: 'lat',
      type: 'string',
      default: '',
      description: 'Latitude column for a map (decimal degrees, -90 to 90).',
    },
    {
      displayName: 'Limit',
      name: 'limit',
      type: 'number',
      default: 10,
      description: 'Top-N categories per frequency bar chart. [default: 10]',
    },
    {
      displayName: 'Location Mode',
      name: 'locationMode',
      type: 'string',
      default: '',
      description: 'How --locations values are matched to regions. One of: iso3 (the default, ISO-3166-1 alpha-3 country codes), usa-states (2-letter US state codes), country-names (full country names), geojson-id (match a --geojson feature id). [default: iso3]',
    },
    {
      displayName: 'Locations',
      name: 'locations',
      type: 'string',
      default: '',
      description: 'Column holding the region key for each row (an ISO-3 country code, a 2-letter US state code, a country name, or a GeoJSON feature id, per --location-mode). With --geocode, this instead names a place-name column to forward-geocode into region codes.',
    },
    {
      displayName: 'Log Scale',
      name: 'logScale',
      type: 'string',
      default: '',
      description: 'Use a logarithmic y-axis for panels with a high dynamic range: frequency bar panels whose tallest bar dwarfs the rest (e.g. a large "(NULL)" or "Other (N)" bucket), so the small categories stay visible; and box panels of an all-positive column whose observed max/min ratio is huge (a box otherwise squashed against its extremes). One of: auto, on, off. "auto" (the default) switches a panel to a log y-axis only when its dynamic range is high; "on" forces a log y-axis on every frequency panel and every all-positive box panel; "off" keeps the linear axes. Only affects `smart`. [default: auto]',
    },
    {
      displayName: 'Lon',
      name: 'lon',
      type: 'string',
      default: '',
      description: 'Longitude column for a map (decimal degrees, -180 to 180).',
    },
    {
      displayName: 'Low',
      name: 'low',
      type: 'string',
      default: '',
      description: 'Low-price column for candlestick/ohlc charts.',
    },
    {
      displayName: 'Map',
      name: 'map',
      type: 'boolean',
      default: false,
      description: 'Render on a token-free MapLibre tile basemap (a ChoroplethMap) instead of the default projection basemap. Requires --geojson; feature-id-key defaults to id. Reuses --style for the basemap.',
    },
    {
      displayName: 'Max Charts',
      name: 'maxCharts',
      type: 'string',
      default: '',
      description: 'Maximum number of panels in the Data Schematic. 0 (the default) means auto: draw every eligible column (up to 64), for both HTML and static image export (png/svg/pdf/...). Up to 8 cartesian panels render as one typed subplot grid; beyond 8, HTML switches to an inline-div grid of independent plots, and static image export uses domain-positioned axes to fit them in one image. Set a positive <n> to cap the panel count instead. Eligible columns beyond the cap are reported but not drawn. [default: 0]',
    },
    {
      displayName: 'No Headers',
      name: 'noHeaders',
      type: 'boolean',
      default: false,
      description: 'When set, the first row will not be interpreted as headers. Columns can then only be selected by index.',
    },
    {
      displayName: 'No Nulls',
      name: 'noNulls',
      type: 'boolean',
      default: false,
      description: 'Omit the "(NULL)" bar (empty cells) from frequency bar charts. By default `viz smart` shows a "(NULL)" bar, like `qsv frequency`.',
    },
    {
      displayName: 'No Other',
      name: 'noOther',
      type: 'boolean',
      default: false,
      description: 'Omit the "Other (N)" aggregate bar from frequency bar charts. It collects the categories beyond --limit (N = how many distinct categories were rolled up) and is shown by default. When just ONE category is left over, it is charted under its own name instead of as an opaque "Other (1)" bar.',
    },
    {
      displayName: 'No Snap',
      name: 'noSnap',
      type: 'boolean',
      default: false,
      description: 'For point-in-polygon binning (lat/lon points binned into a custom GeoJSON without geocoding): do not snap at all — drop every point that falls outside every region. By default an outside point instead snaps to its nearest region when within the snap-distance limit (see --snap-max-dist). Applies to both the `viz choropleth` command and the `viz smart` GeoJSON choropleth panel. A stderr note reports coverage either way; each snapping region\'s hover tallies the points it absorbed from outside, and snapped or dropped points are reported in a note beneath the map (or in the smart panel\'s title).',
    },
    {
      displayName: 'Ohlc Open',
      name: 'ohlcOpen',
      type: 'string',
      default: '',
      description: 'Open-price column for candlestick/ohlc charts.',
    },
    {
      displayName: 'Open',
      name: 'open',
      type: 'boolean',
      default: false,
      description: 'Open the generated chart in the default browser/viewer.',
    },
    {
      displayName: 'Photos',
      name: 'photos',
      type: 'boolean',
      default: false,
      description: 'For the `viz smart` map panel: when a column holds image URLs (detected from the stats cache - an http(s) value ending in a common image extension), embed each point\'s image URL so that dwelling on a map point for 2 seconds opens that row\'s photo in a small preview card beside the pointer (arrow keys page through a row with several photos; Escape dismisses the card). Points that have photos say so in their hover label. When the image host allows cross-origin reads, fetched images are cached in the browser\'s IndexedDB, so re-dwelling a point or reloading the page serves them locally; otherwise the preview falls back to a normal image load served by the ordinary browser cache. OFF by default, and deliberately so: images load from whatever third-party host the DATA names, so enabling this makes everyone who opens the Data Schematic request those URLs directly (revealing their IP to that host). Nothing is fetched until a viewer dwells. Embedding every mapped point\'s URLs also grows the HTML. Applies to HTML output only - static image exports (PNG/SVG/PDF) are unaffected - and only on the tile-basemap map panel. Only affects `smart`.',
    },
    {
      displayName: 'Preview Threshold',
      name: 'previewThreshold',
      type: 'string',
      default: '',
      description: 'Row threshold for the interactive data viewer drawer of HTML dashboards. Next to the row count in the Data Schematic metadata, an "(Explore)" link opens the underlying table in a bottom drawer (with global, per-column and builder search) when the dataset has at most <n> rows and ALL rows are embedded in the page; above <n>, only the first <n> rows are embedded and the link reads "(Preview)". Note that embedded rows grow the HTML file (and browser memory) in proportion to rows x columns. Set to 0 to disable the data viewer entirely (no link, no embedded data). Only affects `smart` HTML output. [default: 50000]',
    },
    {
      displayName: 'Projection',
      name: 'projection',
      type: 'string',
      default: '',
      description: 'Map projection for `viz geo`. One of: natural-earth (the default), mercator, orthographic, equirectangular, albers-usa, robinson, winkel-tripel, mollweide, hammer, azimuthal-equal-area. `viz geo` also reuses the lat, lon, text, color, size and series options from `map`. [default: natural-earth]',
    },
    {
      displayName: 'Rangeslider',
      name: 'rangeslider',
      type: 'boolean',
      default: false,
      description: 'Add a draggable range-slider (a navigator strip) under the x-axis for panning and zooming. Best for an ordered x-axis (time series, line, candlestick/ohlc). Applies to cartesian charts (bar/line/scatter/histogram/box/violin/candlestick/ ohlc); off by default.',
    },
    {
      displayName: 'Sankey Value Order',
      name: 'sankeyValueOrder',
      type: 'boolean',
      default: false,
      description: 'Order sankey nodes by total flow (largest at the top of each column). By DEFAULT nodes use plotly\'s crossing-minimizing "snap" order, which packs the diagram more compactly; this opts into the flow-ranked initial ordering instead. Either way the rendered chart carries an on-screen "node order" button to flip between the two layouts, and link ribbons are always colored by their source node. Applies to the `sankey` chart and the `smart` Data Schematic flow panel.',
    },
    {
      displayName: 'Scale',
      name: 'scale',
      type: 'number',
      default: 1.0,
      description: 'Image scale factor (static export). [default: 1.0]',
    },
    {
      displayName: 'Series',
      name: 'series',
      type: 'string',
      default: '',
      description: 'Column to split into multiple series (one trace per distinct value). Applies to bar, line, scatter, scatter3d, radar, map and geo.',
    },
    {
      displayName: 'Size',
      name: 'size',
      type: 'string',
      default: '',
      description: 'For scatter/scatter3d/map/geo: a numeric column to encode as marker size, producing a bubble chart (values are rescaled to a readable pixel range). Cannot be combined with --series, EXCEPT on an animated scatter (see the --slider option), where the --series column names the entity and this column is the third data variable. In map density mode, this column is the heatmap weight.',
    },
    {
      displayName: 'Slider',
      name: 'slider',
      type: 'string',
      default: '',
      description: 'Animate the chart over a column: each distinct value of the given column becomes an animation frame, with a Play/Pause button and a slider to scrub through the frames (Gapminder- style). Supported for bar/line/scatter and geo, and may be split into animated traces with the --series option. (Not supported for `viz map` — the MapLibre basemap can\'t animate; use `viz geo` for an animated point map.) On `viz scatter`, combining a slider with --series AND --size builds a Gapminder BUBBLE ANIMATION: --series is the entity (one colored bubble each), --x/--y the measure pair and --size the third data variable (bubble area). Each entity x frame cell collapses to one bubble via --agg (mean by default); bubble sizes are scaled once across all frames so they stay comparable. A slider column that parses as dates is auto-bucketed to a readable number of frames; any other column frames on its distinct values. For `smart`, this controls whether one animated relationship-over-time panel is added: the numeric pair whose per-time-bucket centroid path bends the most (a trailing-window scatter colored by time bucket), or an animated geo map of global-extent dated points, or a Gapminder entity-bubble chart (at most one is shown; when several qualify the bubble wins, then the geo map, then the pair). auto (default) adds one only on a strong signal (a date column and enough time buckets); on lowers the bar (as few as two buckets) but still requires a genuinely drifting or animatable relationship; off never does. Axis ranges are pinned across frames so nothing jumps.',
    },
    {
      displayName: 'Slider Cumulative',
      name: 'sliderCumulative',
      type: 'boolean',
      default: false,
      description: 'Accumulate rows across frames: frame N includes every row whose --slider value is at or below the Nth value, so the animation builds up cumulatively instead of replacing each step. Applies to bar/line/scatter and geo. On a bubble animation there is only ever one bubble per entity per frame, so nothing piles up on screen; instead each bubble shows a RUNNING aggregate over all frames up to that point, and so drifts less and less as the animation plays.',
    },
    {
      displayName: 'Slider Speed',
      name: 'sliderSpeed',
      type: 'string',
      default: '',
      description: 'Milliseconds each animation frame is shown while playing. [default: 800]',
    },
    {
      displayName: 'Smarter',
      name: 'smarter',
      type: 'boolean',
      default: false,
      description: 'Before building the Data Schematic, run `qsv moarstats --advanced` to enrich the stats cache with distribution-shape statistics (bimodality, entropy, skewness, outlier share, Gini). This unlocks histograms for bimodal columns, frequency bars for concentrated high-cardinality columns, skew/outlier hints on box panels, and Lorenz curves for the most unequal additive measures (high Gini). Costs one extra pass over the data and writes <stem>.stats.csv, its sidecars, and an .idx index (like running `qsv moarstats` manually). On geocode-enabled builds it also enriches map point hovers with the US FIPS code and annotates the spatial-extent summary with the country\'s continent; the county is always shown in map hovers, with or without --smarter. Only affects `smart`. Applied only with default parsing; inputs using --no-headers or a custom --delimiter fall back to the standard Data Schematic.',
    },
    {
      displayName: 'Snap Max Dist',
      name: 'snapMaxDist',
      type: 'string',
      default: '',
      description: 'For point-in-polygon binning: the farthest (in km) an outside point may snap to a region\'s boundary; points with no region within this distance are dropped. Distance is an equirectangular km approximation. When omitted, the cap is auto-derived from the GeoJSON\'s median region size (10% of the median bbox diagonal) and the lat/lon coordinate precision (coarse, few-decimal coordinates raise the cap to cover their quantization error), clamped to 0.1-100 km; a fixed 10 km is used only when neither signal is available. Applies to both the `viz choropleth` command and the `viz smart` GeoJSON choropleth panel; the coverage notes state the cap applied and how it was derived. Pass a large value for effectively unbounded snapping; cannot be combined with --no-snap.',
    },
    {
      displayName: 'Source',
      name: 'source',
      type: 'string',
      default: '',
      description: 'Source node column for a sankey diagram.',
    },
    {
      displayName: 'Style',
      name: 'style',
      type: 'string',
      default: '',
      description: 'MapLibre basemap style (all render without an access token): open-street-map (the default), carto-positron, carto-darkmatter, carto-voyager, white-bg, basic, streets, outdoors, light, dark, satellite, satellite-streets. The three carto styles also have label-free "-nolabels" variants (e.g. carto-positron-nolabels) that keep basemap place names from competing with a dense data overlay. [default: open-street-map]',
    },
    {
      displayName: 'Target',
      name: 'target',
      type: 'string',
      default: '',
      description: 'Target node column for a sankey diagram.',
    },
    {
      displayName: 'Text',
      name: 'text',
      type: 'string',
      default: '',
      description: 'Column whose value labels each point on hover.',
    },
    {
      displayName: 'Theme',
      name: 'theme',
      type: 'string',
      default: '',
      description: 'Plotly theme that drives the chart\'s overall look (background, fonts, axis styling). One of: default, plotly_white, plotly_dark, seaborn, seaborn_whitegrid, seaborn_dark, matplotlib, plotnine (case-insensitive; hyphens accepted). When omitted, qsv\'s built-in look is used. Applies to all chart types, including `smart`.',
    },
    {
      displayName: 'Title',
      name: 'title',
      type: 'string',
      default: '',
      description: 'Chart title.',
    },
    {
      displayName: 'Value',
      name: 'value',
      type: 'string',
      default: '',
      description: 'Flow value column for a sankey diagram. When omitted, each row counts as a flow of 1. For treemap/sunburst/icicle: a numeric measure summed per sector (when omitted, each row counts as 1).',
    },
    {
      displayName: 'Violin',
      name: 'violin',
      type: 'string',
      default: '',
      description: 'Draw distribution panels as violins (a box plot wrapped in a KDE density silhouette — a strict superset of a plain box) instead of boxes. One of: auto, on, off. "auto" (the default) draws a violin for every continuous column EXCEPT those on a log value axis (the KDE is estimated in linear space, which a log axis would geometrically distort) and those with fewer than 20 distinct values or fewer than 50 non-null observations (too few for a meaningful KDE — the curve would be smoothing artifact) — all keep an honest box; "on" also violins those; "off" never draws violins. Violin KDEs are clamped to each column\'s observed range (Plotly spanmode "hard") so a bounded or discrete measure can\'t show density past a natural limit. A column with at most 10,000 non-null values gets an exact violin (with outlier points, like a raw box); up to 30,000 values (one-fifth of the smart point budget, so it scales with QSV_VIZ_MAX_POINTS) still draws an exact violin but drops the point overlay; a larger column draws its silhouette and inner box from a deterministic sample of at most that many evenly strided values, carries no point overlay (a sample misses the true extremes), and is titled "(sampled)". An explicit all, outliers or suspected mode given via the box-points option instead collects every value for every panel, violins included; that option\'s `none` mode just hides a violin\'s points. Only affects `smart`. [default: auto]',
    },
    {
      displayName: 'Width',
      name: 'width',
      type: 'string',
      default: '',
      description: 'Image width in pixels for static export. Default 1000; for `smart`, auto-scaled to the grid\'s column count.',
    },
    {
      displayName: 'X',
      name: 'x',
      type: 'string',
      default: '',
      description: 'Column for the x-axis / category / bin / group.',
    },
    {
      displayName: 'X Title',
      name: 'xTitle',
      type: 'string',
      default: '',
      description: 'X-axis title. (defaults to the x column name)',
    },
    {
      displayName: 'Y',
      name: 'y',
      type: 'string',
      default: '',
      description: 'Column for the y-axis / value.',
    },
    {
      displayName: 'Y Range',
      name: 'yRange',
      type: 'string',
      default: '',
      description: 'Fix the y-axis to an explicit min:max range (two colon- separated numbers, e.g. -10:55) instead of autoscaling; points outside are clipped from view. Handy when one extreme outlier squashes the rest. Applies to cartesian charts (bar/line/scatter/histogram/box/violin/heatmap/ contour). Pass a negative min with `=`: --y-range=-10:55.',
    },
    {
      displayName: 'Y Title',
      name: 'yTitle',
      type: 'string',
      default: '',
      description: 'Y-axis title. (defaults to the y column name)',
    },
    {
      displayName: 'Z',
      name: 'z',
      type: 'string',
      default: '',
      description: 'The z column: a heatmap pivot value (with --x and --y), or the third numeric axis for scatter3d.',
    },
    ],
  },
];
